### ISSUE TITLE
Branches compat. events

### ISSUE THREAD

**Issue by timoniq** [vkbottle/vkbottle#10]
Прекрасно бы было увидеть возможность совмещения бранчей со всеми событиями, таким образом можно будет создавать такие конструкции как:
- Даю тебе задание написать комментарий "[комментарий]" под записью [запись]
- *Пишет комментарий [комментарий] под записью [запись]*
- Спасибо!

It's going to be great if branches are compatible with all types of events;
- My task for you: write comment [comment] for post [post]
- *Manage task. Write comment [comment] for post [post]*
- Thank you!

**Comment by markelovstyle** [comment]
Still waiting...

**Comment by markelovstyle** [comment]
This is suitable for vkbottle 3.0. Add this issue to the v3.0 milestone

**Comment by InspectorDue** [comment]
Как это должно выглядеть в коде? 
Можно где-то хранить состояние пользователя: НЕ_ВЫПОЛНЯЛ, ПОЛУЧИЛ_ЗАДАНИЕ, ВЫПОЛНИЛ_ЗАДАНИЕ. 
Я не вникал в бибилиотеку vkbottle, но накидал такой пример. Надеюсь, я смог передать идею. 
```python
bot = Bot(...)
db = ...

class TaskStates(enum.IntEnum):
  NOT_COMPLETED = 0
  GOT_TASK = 1
  FINISHED_TASK = 2 

@bot.on.message('/task')
async def _(message):
  user_id = message.user_id
  if db[user_id].state == TaskStates.FINISHED_TASK:
    await bot.send_message(user_id, "You already complete task")
  else:
    await bot.send_message(user_id, "Like pinned post in my group and")
    
@bot.on.like_add(my_pinned_post)
async def _(event):
  user_id = event.liker_id
  if db[user_id].state == TaskStates.GOT_TASK:
    await bot.send_message(user_id, "Thanks!")
    db[user_id].set_state(TaskStates.FINISHED_TASK)
  ```
