### ISSUE TITLE
Longpoll не всегда стабильный и возвращает старые сообщения в случае потери соединения

### ISSUE THREAD

**Issue by Riobener** [vkbottle/vkbottle#1045]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

Добрый вечер, сделал бота для беседы, который просто слушает личные сообщения сообщества и пересылает attachment'ы в Дискорд.
Сразу скажу, возможно во всем виноват ВК, но честно, не уверен так ли это на самом деле.

В общем, заметил проблему, что если при перезапуске бота или, как сегодня вечером, начнет чудить ВК и библиотека постоянно будет пытаться наладить соединение с Longpoll сервером, то в ответ постоянно начинает срабатывать listener на @bot.on.private_message именно на какую-то рандомную старую группу сообщений.

 Если по порядку, бот переслал сообщения 1, 2 и 3. Теряет соединение с longpoll сервером и как только его восстанавливает, опять пересылает сообщения 1,2 и 3 и может так сделать 3 раза подряд с интервалами. 

Из решений, конечно, я могу запоминать, какие сообщения он уже прислал и обрабатывать со своей стороны. Но, все же, поведение самого longpoll'а остается под вопросом правильности. Было бы круто иметь галочку "Не слушать старые сообщения", если он получает запрос после рестарта соединения. 

В моем примере часто дергается handle_message в случае перезапуска/возобновления соединения с longpoll сервером

### Пример кода

```python3
if __name__ == '__main__':
    vk = API(token=settings['vk_token'])
    bot = Bot(api=vk)
    logger = logging.getLogger('vkbottle')
    logger.setLevel(level=logging.ERROR)


    @bot.on.private_message(FromUserRule())
    async def handle_message(message: Message):
        await process_message(message)


    bot.run_forever()
```

### Логи

Стандартные логи на потерю соединения longpoll сервера. К сожалению с сервера не сохранились

**Comment by Tblkva** [comment]
из то информации что у меня есть, по моим личным ботам
1) Упал бот лп (юзер лп вероятно тоже)
2) вместо нормальных запросов приходила вот такая ерунда {'failed': 1, 'ts': 19890985}
3) Примерно в 9 мск я написал в тп и через минут 20 боты починились сами собой
проблема с вероятностью 99% была на стороне вк, увы.
