### ISSUE TITLE
Изменение работы бранчей

### ISSUE THREAD

**Issue by markelovstyle** [vkbottle/vkbottle#105]
**Запрос на возможность связан с проблемой? Если да, опишите**
На данный момент бранчи работают не так, как хотелось бы. Допустим мне нужно поместить в бранч только определенного юзера из беседы, чтобы для остальных пользователей хэндлеры не блокировались. Но есть проблема, в `AsyncHandleManager._processor` обрабатывается только `peer_id`. 

**Опишите решение, которое вы бы хотели видеть**
В `AbstractBranchGenerator` можно добавить метод `contains`, который будет принимать 1 аргумент в качестве списка из целых чисел `typing.List[int]` и проходить циклом по очереди `self.branch.queue`. Если ключ из очереди есть в списке из аргумента, то возвращаем его `return key`

**Опишите решения, которые вы временно предприняли для решения этого вопроса**
Описано выше

**[Дополнительно] Пример псевдокода**
```python
from typing import List, Optional
from typing_extensions import final


class AbstractBranchGenerator(ABC):
    ...
    @final
    def contains(self, keys: List[int]) -> Optional[int]:
        for key in self.branch.queue:
            if key in keys:
                return key


async def _processor(self, obj: dict, client_info: dict):
    ...

    key = self.branch.contains([message.peer_id, message.from_id])
    if key:
        await self._branched_processor(key, obj, client_info, middleware_args)


async def _branched_processor(
       self,
       key: int,
       obj: dict, 
       client_info: dict, 
       middleware_args: list
    ):

```

**Comment by timoniq** [comment]
Решено, закрываю
