### ISSUE TITLE
Не работают бранчи в блупринтах

### ISSUE THREAD

**Issue by axd1x8a** [vkbottle/vkbottle#106]
**Опишите баг**
Бранчи не работают в блупринтах

**Что должно было случится**
Бранчи работают в блупринтах

**Ваш код**
![image](https://user-images.githubusercontent.com/26704473/82156205-97e8ac80-9882-11ea-91a5-805183733bc4.png)![image](https://user-images.githubusercontent.com/26704473/82156270-d67e6700-9882-11ea-9148-40ad84a84a0b.png)![image](https://user-images.githubusercontent.com/26704473/82156404-923f9680-9883-11ea-96c3-16ab52d75e69.png)
![image](https://user-images.githubusercontent.com/26704473/82156609-cd8e9500-9884-11ea-93ea-422563648736.png)

main.py / routes/test_branch.py / проверка / вывод консоли

**Заполните поля:**
 - OS: Windows 10 x64
 - Version of vkbottle: 2.7.4

**Дополнительная информация**
...

**Comment by timoniq** [comment]
Можете пожалуйста прислать код через pastebin

**Comment by axd1x8a** [comment]
https://pastebin.com/PKmwSQ7e
