### ISSUE TITLE
В `wall.*` методах используется неправильная модель ответа

### ISSUE THREAD

**Issue by Bizordec** [vkbottle/vkbottle#1069]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

В схеме версии 5.199 у метода `wall.getById` с параметром `extended=1` указана неправильная модель ответа `wall_wall_item` , хотя должна быть `wall_wallpost_full`. 
https://github.com/VKCOM/vk-api-schema/blame/d95ffb2c3c9245751c1228cb714da4bc314af1fd/wall/responses.json#L56
Из-за этого пропало много полей, которые на самом деле в JSON возвращаются, например `attachments` и `geo`.

Можно ли как-то запатчить это в `vkbottle_types`, чтобы использовалась модель `WallWallpostFull`? 
https://github.com/vkbottle/types/blob/5974270721231314469c6d69fd8d912ce68690a2/vkbottle_types/codegen/responses/wall.py#L36

Ну и судя по [старой схеме](https://github.com/vkbottle/types/blob/320b976f0cdebf654b8bbd787ffe2d220dc78a98/vkbottle_types/responses/wall.py), везде, где используется `WallWallItem`, нужно поменять на `WallWallpostFull`.

**Comment by luwqz1** [comment]
привет, к сожалению, в самом кодгене никак этого не сделать, но спасибо за репорт, я руками исправлю в файле `responses/wall.py`, чтобы в райнтайме перезаписать на другой тип
