### ISSUE TITLE
Обработка всех непрочитанных сообщений 

### ISSUE THREAD

**Issue by Doncode** [vkbottle/vkbottle#107]
**Запрос на возможность связан с проблемой? Если да, опишите**
Сейчас бот получает сообщения только с момента когда он запущен.
Если сделать перезапуск бота когда пользователи ему пишут, то сообщения останутся непрочитанными и неотвеченными.

**Опишите решение, которое вы бы хотели видеть**
При запуске бот получается все непрочитанные сообщения и обрабатывает их.
Возможно это какой-то параметр при запуске

**Comment by timoniq** [comment]
Есть параметр skip_updates который позволяет обработать все полученные сообщения. Добавьте флаг при запуске бота:
`bot.run_polling(skip_updates=False)`

**Comment by Doncode** [comment]
Это будут все сообщения или все непрочитанные?

**Comment by axd1x8a** [comment]
Все неотвеченные, если они проходят по хендлеру.

**Comment by timoniq** [comment]
> Это будут все сообщения или все непрочитанные?

Из всех неотвеченных диалогов обработаются последние сообщения
