### ISSUE TITLE
Поддержка скрытых методов VK API

### ISSUE THREAD

**Issue by NousadS** [vkbottle/vkbottle#1086]
### Описание

В _VK API_ есть скрытые методы, такие как `messages.changeConversationMemberRestrictions` которые не описаны в официальной документации и не поддерживаются SDK. Для работы с ними можно либо узнавать их вручную (что требует усилий), либо использовать динамический метод `__getattr__` и модуль `requests` (либо его аналог).

Метод `messages.changeConversationMemberRestrictions` доступен на [api.vk.com/method/messages.changeConversationMemberRestrictions](https://api.vk.com/method/messages.changeConversationMemberRestrictions) и определяет мут для юзера.

Параметры:
- peer_id - id чата
- member_ids - id пользователей через запятую
- for - время в секундах
- action: ro - наложить мут
- action: rw - снять мут

**Comment by luwqz1** [comment]
привет, спасибо за вопрос. в vkbottle не планируется поддержка скрытых методов, так как их сложно поддерживать, vkbottle с трудом поддерживает известные api методы из-за халатности vk dev. 

> либо использовать динамический метод `__getattr__` и модуль `requests` (либо его аналог).

не совсем понял о чем речь, в vkbottle у класса API имеется методы, которые могут сделать запрос в vk api, указав туда название метода и его параметры, он вернет сырой ответ (`dict`)

```python
api = API(...)
response = await api.request("messages.changeConversationMemberRestrictions", {})
```
