### ISSUE TITLE
Добавление FSM

### ISSUE THREAD

**Issue by Vast-Nectarine** [vkbottle/vkbottle#113]
Почему бы не добавить fsm  [как в aiogram](https://aiogram.readthedocs.io/en/latest/examples/finite_state_machine_example.html)
И сделать какую-то интеграцию с кнопками?

**Comment by timoniq** [comment]
1. FSM = бранчи
2. Что? 2 генератора клавиатуры - мало?

**Comment by Vast-Nectarine** [comment]
1. Не увидел.
2. Не увидел, но приведу пример. 
Допустим, я пишу бота, основанного на кнопках. 
Пользователь начинает беседу с ботом, видит меню, состоящее из 3-ех кнопок: "Пойти налево", "Пойти прямо", "Пойти направо". С payload-ми: "left", "straight", "right" соответственно. Допустим, пользователь нажал на вторую кнопку. Как мне это обрабатывать, используя бранчи, потому что payload можно свой собственный написать (messages.send)?  Т.е. я могу нажать на кнопку "Пойти прямо", выполнится какое-то действие (т.е. кнопку "Пойти налево" я нажать не могу), но через метод messages.send я могу отправить payload "left" (упрощенно, на самом деле, там должен быть json). Как с этим быть?

**Comment by markelovstyle** [comment]
> Допустим, пользователь нажал на вторую кнопку. Как мне это обрабатывать

```python
from vkbottle.bot import Bot, Message
from vkbottle.branch import ClsBranch, rule_disposal
from vkbottle.rule import PayloadRule


class Test(ClsBranch):
    @rule_disposal(PayloadRule({"command": "right"}))
    async def turn_right(self, ans: Message):
        await ans("You turned right.")

    @rule_disposal(PayloadRule({"command": "left"}))
    async def turn_left(self, ans: Message):
        await ans("You turned left.")
```

**Comment by Vast-Nectarine** [comment]
Как же тогда бороться с тем, что можно свой payload написать и отправить через messages.send?

**Comment by timoniq** [comment]
> Как же тогда бороться с тем, что можно свой payload написать и отправить через messages.send?

Его в любом случае можно отправить самому, те же кнопки. Хендлеры в бранче не будут обрабатываться если пользователь не в бранче, мне кажется это очевидно.

**Comment by Vast-Nectarine** [comment]
Извините, что туплю, но ведь код выше не использует бранчи.

**Comment by timoniq** [comment]
> Извините, что туплю, но ведь код выше не использует бранчи.

Как это, именно что использует. `ClsBranch` самая удобная имплементация бранчей, прочитайте [документацию](https://github.com/timoniq/vkbottle/blob/master/docs/branches.ru.md) пожалуйста
