### ISSUE TITLE
Возникла проблема при использование vkbottle uploader

### ISSUE THREAD

**Issue by kitag4wa** [vkbottle/vkbottle#120]
Делаю бота через vkbottle.bot в группе. 
Суть заключается в том, что человек пишет в лс группы "привет" и прикрепляет картинку к сообщению, бот же должен сохранить ссылку на вложение и отослать на другой сайт, после оттуда сохранить к себе и отправить(загрузить) тому человеку, который прислал её в лс группы.

Код скрипта с python на pastebin: https://pastebin.com/TzHHYra2

также прикрепляю скрин ошибки в консоли

![Screenshot_10](https://user-images.githubusercontent.com/51799819/83572959-36d40080-a533-11ea-8401-db1c81e68ea6.png)

Прошу помочь! Как это исправить/решить?

**Comment by markelovstyle** [comment]
`photo_uploader = PhotoUploader(api=bot.api, generate_attachment_strings=True)`

**Comment by kitag4wa** [comment]
> photo_uploader = PhotoUploader(api=bot.api, generate_attachment_strings=True)

Спасибо!
