### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by LooPeKa** [vkbottle/vkbottle#122]
**Опишите баг**
Please check your internet connection

**Что должно было случится**
Пишу боту, но выходит такая ошибка 

**Ваш код**
https://pastebin.com/B11cWBxh

**Заполните поля:**
 - OS: Pythonanywhere
 - Version of vkbottle: 2.7.5

**Дополнительная информация**
[https://vk.com/photo589229003_457240189](https://vk.com/photo589229003_457240189)

**Comment by LooPeKa** [comment]
https://vk.com/photo589229003_457240189

Pythonanywhere*

**Comment by timoniq** [comment]
Ничего хорошего не работает на pythonanywhere, воспользуйтесь нормальными бесплатными хостингами например [heroku](https://www.heroku.com/). К теме багов это никак не относится

**Comment by LooPeKa** [comment]
> Ничего хорошего не работает на pythonanywhere, воспользуйтесь нормальными бесплатными хостингами например [heroku](https://www.heroku.com/). К теме багов это никак не относится

Хорошо , спасибо!)
