### ISSUE TITLE
Ошибка валидации модели GetIdByModel

### ISSUE THREAD

**Issue by markelovstyle** [vkbottle/vkbottle#129]
**Опишите баг**
Возникает ошибка валидации поля в `GetIdByModel`. 

**Ваш код**
https://pastebin.com/YX5wG8SW

**Заполните поля:**
 - OS: Windows
 - Version of vkbottle: Latest

**Дополнительная информация**
Такое происходит при отправке плейлиста

**Comment by matvey-istomin** [comment]
Каков attachment['type']? Отправил плейлист, получил type=link. link есть в перечислении.

**Comment by markelovstyle** [comment]
Принтани результат запроса от `messages.get_by_id`

UPD: Type=audio_playlist

**Comment by matvey-istomin** [comment]
[вот](https://pastebin.com/pMkxa1iW)
Версия 5.107. Запрос делал через веб-версию
А vkbottle работает на 5.103

**Comment by matvey-istomin** [comment]
Проверил с ботом, всё точно также.

**Comment by dhvcc** [comment]
Ещё не пофикшено?
