### ISSUE TITLE
Опечатка в документации

### ISSUE THREAD

**Issue by dwapper** [vkbottle/vkbottle#134]

**Comment by dwapper** [comment]
Так же в [README лицензии](https://github.com/timoniq/vkbottle/blob/master/README.md#%D0%BB%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F) указана GPL 3.0, когда судя по [LICENCE](https://github.com/timoniq/vkbottle/blob/master/LICENSE) лицензия на самом деле **MIT**

**Comment by timoniq** [comment]
Спасибо за бдительность, скоро исправим!
