### ISSUE TITLE
Баг в работе с бранч

### ISSUE THREAD

**Issue by Doncode** [vkbottle/vkbottle#139]
**Опишите баг**
- заходим в branch1 `await bot.branch.add(ans.peer_id, 'branch1')`
- пользователь отвечает на сообщения и вызывается код branch1
- `await bot.branch.exit(ans.peer_id)`
- `await bot.branch.add(ans.peer_id, 'branch2')`
- пользователь пишет сообщение, но снова попадает в branch1

**Что должно было случится**
Пользователь должен попадать в branch2

**Заполните поля:**
 - Version of vkbottle-2.7.5
 `pip install git+https://github.com/timoniq/vkbottle.git`

**Дополнительная информация**
мой код успешно работает на vkbottle-2.7.3  но ломается на vkbottle-2.7.5

**Comment by markelovstyle** [comment]
`await bot.branch.exit()` -- принимает идентификатор пользователя/чата, а не название бранча.

**Comment by Doncode** [comment]
Да. В коде у меня используется `await bot.branch.exit(ans.peer_id)` и это не работает
Поправил описание в первом сообщении

**Comment by Doncode** [comment]
Полный код
```python
@bot.on.message(text='go')
async def go_handler(ans: Message):
    await bot.branch.add(ans.peer_id, 'branch1')
    await ans('you are in branch1')


@bot.branch.simple_branch('branch1')
async def branch1_branch_handler(ans: Message):
    await bot.branch.exit(ans.peer_id)
    await bot.branch.add(ans.peer_id, 'branch2')
    await ans('exit branch1.\nyou are in branch2')


@bot.branch.simple_branch('branch2')
async def branch2_branch_handler(ans: Message):
    await bot.branch.exit(ans.peer_id)
    await ans('exit branch2')


@bot.on.message()
async def menu_handler(ans: Message):
    await ans('menu')
```

Результат
> [me] go
> [bot] you are in branch1
> [me] ok1
> [bot] exit branch1. 
> [bot] you are in branch2
> [me] ok2
> [bot] exit branch1. 
> [bot] you are in branch2

**Comment by markelovstyle** [comment]
Попробуй сначала `add`, а потом уже `exit`

**Comment by Doncode** [comment]
@timoniq проблема решена?

**Comment by timoniq** [comment]
Да

**Comment by timoniq** [comment]
Нет, закрыл из-за неактивности. Вы пользуетесь database или обычными бранчами?

**Comment by Doncode** [comment]
Обычный. без database

**Comment by timoniq** [comment]
Сделал фикс, проверяйте, обновив с мастера
