### ISSUE TITLE
KeyError: 'client_info'

### ISSUE THREAD

**Issue by tsivx** [vkbottle/vkbottle#14]
![изображение](https://user-images.githubusercontent.com/40364630/70828930-3c674e00-1e0e-11ea-9834-f2dc14b864b7.png)

Видимо, с веб версии ВКонтакте client_info не высылается и бот совсем отказывается работать.

**Comment by ghost** [comment]
Версия API - **5.103**? Если нет - укажите её в настройках Longpoll. Без этого бот работать не будет.

**Comment by tsivx** [comment]
> 
> 
> Версия API - **5.103**? Если нет - укажите её в настройках Longpoll. Без этого бот работать не будет.

Ах, да, забыл об этом. Указал нужную версию, теперь всё работает. Спасибо!
