### ISSUE TITLE
Множество акков с лонгполлом

### ISSUE THREAD

**Issue by json1c** [vkbottle/vkbottle#153]
.

**Comment by petrarka** [comment]
Привет!
Опиши проблему подробнее.
Если ты хочешь несколько инстансов одного бота с разными токенами и эти боты не связаны между собой, то ты можешь использовать docker и передавать токен как аргумент при создании контейнера.
Если боты на разных аккаунтах должны быть связаны, то используй общую базу данных для синхронизацией между контейнерами (например redis)
