### ISSUE TITLE
data как атрибут класса, а не его экземпляра

### ISSUE THREAD

**Issue by DarklyZ** [vkbottle/vkbottle#16]
В VBMLRule (и других правилах) self.data является атрибутом самого класса, а надо чтобы она была атрибутом его экземпляров, к примеру сейчас не работают команды в кол-ве > 1.
Следует заменить self.data['pattern'] = patterns на self.data = {'pattern': patterns} (и так для каждого правила соответственно), тогда для каждого экземпляра класса будет существовать своя data и баг будет пофиксен. С уважением, пользователь vkbottle!

**Comment by timoniq** [comment]
Фикс поступит в ближайшее время!
