### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by LooPeKa** [vkbottle/vkbottle#166]
Как сделать так, чтоб юзер бот отвечал в беседах?

**Comment by LooPeKa** [comment]
Я пытался, не работает

**Comment by core-p** [comment]
Бот отвечает на личные сообщения? Какой хендлер используете для обработки сообщений в беседе?

**Comment by simonoffcc** [comment]
Всё в беседе работает. Попробуйте данный код:
```
from vkbottle.user import User, Message

user = User(login='логин', password="пароль")  # Или с помощью логина и пароля

@user.on.chat_message(text="привет", lower=True)
async def wrapper(ans: Message):
    await ans("че надо")


user.run_polling()

**Comment by axd1x8a** [comment]
Используйте @bot.on.message_handler()
Это позволяет отвечать боту и в личных сообщениях и в беседах

**Comment by LooPeKa** [comment]
ок.
