### ISSUE TITLE
Как обрабатывать неизвестные боту команды?

### ISSUE THREAD

**Issue by simonoffcc** [vkbottle/vkbottle#170]
Хочу сделать обработку сообщений, хендлеров которых нет в программе, грубо говоря команды, которые бот не знает.

Может быть я невнимательно прочитал документацию и есть какой-то конкретизированный способ это сделать, но я его не нашел. Возможно это можно сделать через обработку исключений? Если можно, то как?

Единственно до чего я додумался, так это поставить "пустой" хендлер, без аргументов, самым последним хендлером в программе. 
Помогите пожалуйста. 

Вот мое решение:
@bot.on.message()
async def wrapper(ans: Message):
    await ans('Я вас не понимаю :(')

**Comment by axd1x8a** [comment]
Это и есть решение

**Comment by simonoffcc** [comment]
Понял, спасибо.

**Comment by quick-wq** [comment]
```
@bot.on.message(text="!<command>")
async def wrapper(ans: Message):
    await ans("Мне неизвестна данная команда. /n"
              "Напишите !помощь чтобы посмотреть все команды")
```
