### ISSUE TITLE
Какая версия Longpoll API

### ISSUE THREAD

**Issue by ustokan** [vkbottle/vkbottle#172]
Подскажите пожалуйста, какую нужно использовать версию Longpool API?
Я получаю ошибку
vkbottle.utils.exceptions.VKError: (29, 'Rate limit reached', , {'group_id': 189220845})
Возможно ли это из-за версии 5.50?

**Comment by ustokan** [comment]
Я получаю ошибку 
vkbottle.utils.exceptions.VKError: (29, 'Rate limit reached', <Method GroupsGetLongPollServer>, {'group_id': 189220845})
Возможно ли это из-за версии 5.50?

**Comment by TheBakerCat** [comment]
Рекомендуется ставить 5.103

**Comment by ustokan** [comment]
Спасибо
