### ISSUE TITLE
29 ошибка при запуске бота (первом)

### ISSUE THREAD

**Issue by ustokan** [vkbottle/vkbottle#173]
**Опишите баг**
При запуске бота сразу вылезает ошибка 29

**Заполните поля:**
 - OS: [Windows 10]
 - Version of vkbottle: [2.7.5]

Longpool API 5.103
![скриншот cmd](https://user-images.githubusercontent.com/55207603/88374606-a7183900-cda2-11ea-83c7-2c64d571242b.png)

**Comment by TheBakerCat** [comment]
Попробуй обновиться с мастера

**Comment by ustokan** [comment]
Как понять?

**Comment by TheBakerCat** [comment]
> Как понять?

​pip install https://github.com/timoniq/vkbottle/archive/master.zip --upgrade

**Comment by ustokan** [comment]
Такая же ошибка
![cmd_ef80iP5JhO](https://user-images.githubusercontent.com/55207603/88376072-67068580-cda5-11ea-9a4f-cba8b1eab009.png)

**Comment by timoniq** [comment]
> Такая же ошибка
> ![cmd_ef80iP5JhO](https://user-images.githubusercontent.com/55207603/88376072-67068580-cda5-11ea-9a4f-cba8b1eab009.png)

Вы достигли какого-то лимита по запросам на вашу группу, попробуйте запустить без `skip_updates=False`

**Comment by TheBakerCat** [comment]
> Такая же ошибка

Значит дело скорее всего в токене
![Screenshot_20200724-140846_Chrome.png](https://user-images.githubusercontent.com/49706608/88376836-9f16c400-cdb7-11ea-8e86-6f6441d9b6e7.png)

**Comment by ustokan** [comment]
Создание нового токена не помогло, `skip_updates=False` убрал, тоже не помогло
