### ISSUE TITLE
Сделал свой декоратор, есть проблема

### ISSUE THREAD

**Issue by simonoffcc** [vkbottle/vkbottle#175]
Для одного декоратора сообщений сделал свой собственный декоратор, для того чтобы бот отвечал только тем людям, id которых есть в списке. Остальным он отвечал "Access Denied".
Вот его код:
```jsx
def auth(func):

    async def wrapper(ans):
        if ans.peer_id != [123456789, 987654321, 321456987]:
            return await ans('Access Denied')
        return await func(ans)

    return wrapper
```
Он прекрасно работает, отвечает только людям в списке. 
Проблема вот в чем: если боту напишет кто-то, кого нет в списке, то бот ему сначала ответит "Access Denied" (собственно, как и задумывалось), но после бот присылает еще одно сообщение: число, и как я понял это id сообщения в диалоге. Почему так происходит?

Вот как использую этот декоратор вместе с декоратором сообщений:
```jsx
@bot.on.message(text=['админ'], lower=True)
@auth
async def admin(ans: Message):
    await ans('Режим админа.')
```

**Comment by ghost** [comment]
При вызове ans используется метод **messages.send**, возвращающий число — идентификатор сообщения. Обьект, находящийся в return также используется в качестве текста сообщения.

**Comment by ghost** [comment]
Советую использовать мидлвари вместо собственных декораторов. Однако, если ситуация требует использовать такие решения, то следуйте совету ниже.

**Comment by axd1x8a** [comment]
Все из-за того, что вы используете `return await ans`
вы отправляете сообщение, а функция ans() возвращает его ид, который отправляется через return.
Если вам нужна отправка через ans, то вам поможет это:
await ans("text")
return

**Comment by simonoffcc** [comment]
Спасибо большое, помогло.
