### ISSUE TITLE
Не обрабатывается событие on.message

### ISSUE THREAD

**Issue by k0zwa** [vkbottle/vkbottle#184]
Не обрабатывается событие on.message, при отправке личного сообщения боту, через мобильный клиент и/или мобильную веб-версию, через Chrome, на устройствах под управлением Android 10. Бот крутится на Long Poll, под шindoшs все хорошо и замечательно.

Не уверен за iOS, под рукой нет. Не уверен и в том, что это сильно влияет. Такие дела

**Comment by timoniq** [comment]
1. Какая у вас версия VKBottle?
2. Предоставьте ваши логи если это возможно

**Comment by k0zwa** [comment]
Привет, спасибо за оперативный ответ. Версия 2.7.6, могу попробовать обновиться до текущей в pip, но чуть позже - хаос деплоя. С логами тоже позже

**Comment by timoniq** [comment]
> Привет, спасибо за оперативный ответ. Версия 2.7.6, могу попробовать обновиться до текущей в pip, но чуть позже - хаос деплоя. С логами тоже позже

2.7.6 на данный момент не работает, потому что вконтактеры все поломали добавив поле в енум для всех версий апи. Ставьте 2.7.8, там все хорошо

**Comment by k0zwa** [comment]
Понял, спасибо. Уже сломал всю голову.

**Comment by k0zwa** [comment]
Подтверждаю, на 2.7.8 все заработало. Еще раз спасибо, timoniq.
