### ISSUE TITLE
Client_info не полный

### ISSUE THREAD

**Issue by vayaka** [vkbottle/vkbottle#200]
В документации сказано, что в событие message_new должен присутствовать ключ "carousel", но когда я получаю событие, этот ключ отсутствует. Из-за этого я не могу сделать нормально бота.
Вот, что в client_info
![image](https://user-images.githubusercontent.com/41854595/90952199-60356600-e46a-11ea-81b7-439eff77f9a7.png)
Может у кого-нибудь была такая проблема?

**Comment by timoniq** [comment]
Добавил поле, можете проверять, обновившись с мастера

**Comment by vayaka** [comment]
Поле не появилось, потому, что вы ошиблись

**Comment by vayaka** [comment]
![image](https://user-images.githubusercontent.com/41854595/90963885-5dfff580-e4c4-11ea-8c89-45ccd0cb5983.png)
Строка "carousel" находиться в другом месте

**Comment by vayaka** [comment]
![image](https://user-images.githubusercontent.com/41854595/90964107-4cb7e880-e4c6-11ea-9cfe-64992b72d200.png)
![image](https://user-images.githubusercontent.com/41854595/90964117-622d1280-e4c6-11ea-8641-8e503bc0628f.png)
