### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by LooPeKa** [vkbottle/vkbottle#201]
**Опишите баг**
При установки модуля на ноутбук ( Lenovo G555 ) ( Windows 10 ) вылазит ошибка ( error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/ )

**Что должно было случится**
Установка модуля

**Ваш код**
pip install vkbottle

**Заполните поля:**
 - OS: Windows 10
 - Version of vkbottle: Не скачал

**Дополнительная информация**
Это не ваша вина, но  прошу помогите)

**Comment by timoniq** [comment]
https://github.com/timoniq/vkbottle/issues/47
