### ISSUE TITLE
Bot.loop is None in new versions

### ISSUE THREAD

**Issue by CrabOnTheBeach** [vkbottle/vkbottle#203]
The Bot.loop in None after https://github.com/timoniq/vkbottle/commit/730c8143dcce2a25a28322a6034778d058588dcc#diff-eef9235318e8d85a06766f3daf94071f commit.

We are creating a background task by using Bot.loop.create_task. It worked fine on version 2.7.8. I think that commit https://github.com/timoniq/vkbottle/commit/730c8143dcce2a25a28322a6034778d058588dcc#diff-eef9235318e8d85a06766f3daf94071f broke loop creation in vkbottle/framework/user/user.py line 74.

**Comment by timoniq** [comment]
true. it will be fixed soon in [3.0 release](https://github.com/timoniq/vkbottle/tree/v3.0), please use stable version for now. anyway pull requests are welcome
