### ISSUE TITLE
Вопрос насчёт рассылки

### ISSUE THREAD

**Issue by Nidelon** [vkbottle/vkbottle#204]
Возможно ли на vkbottle сделать рассылку, например я отправил боту текст или сообщение,
далее он это отошлет (Желательно что бы пересылал) в беседу и другим участникам, кто подписан на эту рассылку (Возможно ли это сделать с помощью бранчев?)
Если коротко:
1. Возможно ли пересылать сообщение тем, кто состоит в группе (С фотографией)
2. Возможно ли сделать на бранчах рассылку

**Comment by Nidelon** [comment]
Ох ты, не увидел что можно создать пустой вопрос без "enhancement"

**Comment by dhvcc** [comment]
Рассылку можно сделть, можно и переслать. Посмотрите доки вк
Бранчи зависят от вашего интерфейса, но можно из без них один хендлер сделать
Подписки на рассылку храните в бд, и, когда необходимо, пробегайтесь по бд и делайте `messages.send`
Фотографии тоже можно добавлять

**Comment by dhvcc** [comment]
> Ох ты, не увидел что можно создать пустой вопрос без "enhancement"

Лейблы можно снимать

**Comment by Nidelon** [comment]
Ага, с рассылкой понял и уже сделал, последний вопрос, возможно ли сохранить бранчи в json

**Comment by Nidelon** [comment]
Заранее говорю что использую бранчи не для рассылки

**Comment by timoniq** [comment]
> Ага, с рассылкой понял и уже сделал, последний вопрос, возможно ли сохранить бранчи в json

Этот вопрос уже не относится к теме issue, но ответ - да. Смотрите database-бранчи, вам будет нужно только имплементировать методы чтения и записи вашего json файла
