### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by mazzz3r** [vkbottle/vkbottle#209]
**Опишите баг**
При создании мидлваря у юзера выскакивает ошибка `TypeError: run_middleware() got multiple values for argument 'flag'`

**Что должно было случится**
Ошибка не должна была выскакивать 🤔

**Ваш код**
https://pastebin.com/MnMvnQVQ

**Заполните поля:**
 - OS: Windows 10
 - Version of vkbottle: 2.7.11

**Дополнительная информация**
...

**Comment by timoniq** [comment]
А почему в одном хендлере бот а в другом юзер

**Comment by mazzz3r** [comment]
Это я не тот код закинул на пастбин, отредачил ссылку. Проблема была в том, что я ретарнил true...
