### ISSUE TITLE
Баг(это не баг)

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#218]
Как распознать стикер?

Бот должен был распознать стикер.

![image](https://user-images.githubusercontent.com/60805088/95455465-5b2f6600-0987-11eb-837a-1f2becf4a68d.png)
![image](https://user-images.githubusercontent.com/60805088/95455524-7306ea00-0987-11eb-97e4-7f154e887598.png)

 - OS: windows 7 64-bit
 - Version of vkbottle: 2.7.11

**Comment by hampta** [comment]
> Как распознать стикер?
> 
> Бот должен был распознать стикер.
> 
> ![image](https://user-images.githubusercontent.com/60805088/95455465-5b2f6600-0987-11eb-837a-1f2becf4a68d.png)
> ![image](https://user-images.githubusercontent.com/60805088/95455524-7306ea00-0987-11eb-97e4-7f154e887598.png)
> 
>  - OS: windows 7 64-bit
>  - Version of vkbottle: 2.7.11
> 

Используй StickerRule, полный список рулов тут:
https://www.github.com/timoniq/vkbottle/tree/master/vkbottle%2Fframework%2Fframework%2Frule%2Frule.py

**Comment by Timtaran** [comment]
спасибо

**Comment by hampta** [comment]
> > Как распознать стикер?
> > 
> > Бот должен был распознать стикер.
> > 
> > ![image](https://user-images.githubusercontent.com/60805088/95455465-5b2f6600-0987-11eb-837a-1f2becf4a68d.png)
> > ![image](https://user-images.githubusercontent.com/60805088/95455524-7306ea00-0987-11eb-97e4-7f154e887598.png)
> > 
> >  - OS: windows 7 64-bit
> >  - Version of vkbottle: 2.7.11
> > 
> 
> Используй StickerRule, полный список рулов тут:
> https://www.github.com/timoniq/vkbottle/tree/master/vkbottle%2Fframework%2Fframework%2Frule%2Frule.py

И ошибка у тебя тут(исправленный вариант): async def wrapper(ans: Message)

**Comment by Timtaran** [comment]
> > > Как распознать стикер?
> > > Бот должен был распознать стикер.
> > > ![image](https://user-images.githubusercontent.com/60805088/95455465-5b2f6600-0987-11eb-837a-1f2becf4a68d.png)
> > > ![image](https://user-images.githubusercontent.com/60805088/95455524-7306ea00-0987-11eb-97e4-7f154e887598.png)
> > > 
> > > * OS: windows 7 64-bit
> > > * Version of vkbottle: 2.7.11
> > 
> > 
> > Используй StickerRule, полный список рулов тут:
> > https://www.github.com/timoniq/vkbottle/tree/master/vkbottle%2Fframework%2Fframework%2Frule%2Frule.py
> 
> И ошибка у тебя тут(исправленный вариант): async def wrapper(ans: Message)

уже исправил
