### ISSUE TITLE
В беседах мой бот не отвечает на сообщения, содержащие упоминания. Хочу разобраться, в чём дело. Помогите, пожалуйста

### ISSUE THREAD

**Issue by pavelfoki** [vkbottle/vkbottle#222]
**Опишите баг**
В беседах мой бот не отвечает на сообщения, содержащие упоминания. Хочу разобраться, в чём дело. Помогите, пожалуйста.

**Что должно было случится**
Бот должен был ответить на сообщение, содержащее упоминание.

**Ваш код**
https://pastebin.com/NJGiheG7

**Заполните поля:**
- OS: Windows 10

**Дополнительная информация**
В беседе бот является администратором, команды без упоминаний обрабатываются успешно.

**Comment by timoniq** [comment]
Попробуйте передать `group_id` при создании бота
