### ISSUE TITLE
TaskManager

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#229]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\vkbottle\framework\framework\swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\vkbottle\framework\bot\processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "C:\Users\userAppData\Local\Programs\Python\Python38\lib\site-packages\vkbottle\framework\bot\processor.py", line 81, in message_processor
    task = await rules[0].call(*args, **kwargs)
  File "d:\VSCode codes\tsts\8.py", line 63, in wrapper
    task_manager.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\vkbottle\utils\task.py", line 52, in run
    self.loop.run_forever()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 314, in run_forever
    assert self._self_reading_future is None
AssertionError

выполнение действия в многопотке
async def send(b):
	for i in range(6):
		coin.sendPayment(b, 1)

@bot.on.message(text="group [<skip1>|@<name>]", lower=True)
async def wrapper(ans: Message, skip1, name):
	task_manager = TaskManager()
	await ans('started')
	if ans.from_id == 279161087 or ans.from_id == 549204433:
		f1=time.time()
		if ans.payload == '1':
			offset = 0
			print(0)
			d = name
			a = vk.groups.getMembers(group_id=d, offset=offset)
			c = a
			g = 0
			ng = 1000
			for b in a['items']:
				task_manager.add_task(send(b))
				g += 1
				if g == ng:
					if a['count'] > g:
						offset += 1000
						while True:
							a = vk.groups.getMembers(group_id=d, offset=offset)
							for b in a['items']:
								task_manager.add_task(send(b))
								g += 1
								if c['count'] <= g:
									break
								if g == ng:
									if a['count'] > g:
										offset += 1000
									else:
										break
		else:
			print(1)
			fg = f()
			await ans(""":)
""", keyboard=keyboard_gen(fg.payload_get(name), one_time=False))
	print(2)
	task_manager.run()
	print(3)
	await ans(f'ended\nЗанято {time.time() - f1} секунд')
	print(4)

**Заполните поля:**
 - OS: Windows 7 64-bit
 - Version of vkbottle: 2.7.12

Скинул не весь код

**Comment by dhvcc** [comment]
Трейсбеки и код лучше на pasebin.com закидывать
Читать невозможно

**Comment by dhvcc** [comment]
> @bot.on.message(text="group [|@]", lower=True)

Есть же `on.chat_mention`

**Comment by Timtaran** [comment]
> > @bot.on.message(text="group [|@]", lower=True)
> 
> Есть же `on.chat_mention`

все нормально работало, но не могу добавить асинхронное выполнение команды * количество пользователей в группе ВК

**Comment by timoniq** [comment]
нельзя запускать таск менеджер в хендлере, таск менеджер блокирует луп
просто сделай await

**Comment by Timtaran** [comment]
> Трейсбеки и код лучше на pasebin.com закидывать
> Читать невозможно

https://pastebin.com/pLrRgCx2
https://pastebin.com/ppqeEiBi

**Comment by Timtaran** [comment]
> нельзя запускать таск менеджер в хендлере, таск менеджер блокирует луп
> просто сделай await

спасибо

**Comment by Timtaran** [comment]
> нельзя запускать таск менеджер в хендлере, таск менеджер блокирует луп
> просто сделай await

TypeError: object dict can't be used in 'await' expression 




:(

**Comment by timoniq** [comment]
где код

**Comment by timoniq** [comment]
`await send(b)`
а вообще, вопрос не относится к фреймворку

**Comment by Timtaran** [comment]
> где код

понял проблему, с этим методом не работает await
