### ISSUE TITLE
Новая возможность / Идея

### ISSUE THREAD

**Issue by MrSmitix** [vkbottle/vkbottle#239]
**Проблема (для v3)**
В проекте достаточно много блюпринтов, они используются для удобного разделения функционала. Работы в лс, в беседах, админские команды, системные команды, обработка эвентов от группы и т.д. Постоянно приходится копипастить рулы которые отвечают за эти команды. Выполнять дополнительные проверки. 

**Опишите решение, которое вы бы хотели видеть**
Было бы не плохо каждому блюпринту добавить какие-то общие рулы, где можно было бы указывать общие фильтры. Например если state равен определенному значению. Как самый банальный пример. Тем самым можно увеличить скорость обработки запросов при очень большом кол-ве хендлеров, так как если основные правила блюпринта не прошли проверку, нет смысла проверять хендлеры в нем.

**[Дополнительно] Пример псевдокода**
```python
# Создаём блюпринт
menu_bp = Blueprint('Меню')

# Добавляем общий рул, обработчики блюпринта будут обрабатываться/проверяться
# только если выполнились общие проверки, например что пользователь находится в меню.
menu_bp.router.common_rules = StateRule(state=States.IN_MENU)  # Добавляем общий рул

# Или можно передавать сразу фильтр. Указывая что проверять нужно несколько пунктов.
menu_bp.router.common_rules = filter.and(SomeRule1(), SomeRule2())  # Список рулов
```

**Comment by timoniq** [comment]
Хорошая идея! Сделаю.
Конечно, к роутеру оно не будет привязываться

**Comment by timoniq** [comment]
Решение теперь есть. Используйте `auto_rules`:

```python
bp.labeler.auto_rules = [SomeRule()]
```
