### ISSUE TITLE
Ошибка messages.send(peer_ids)

### ISSUE THREAD

**Issue by kforbro** [vkbottle/vkbottle#257]
Сообщения отправляются, но при этом вылезает ошибка.
https://pastebin.com/54HRUT4N

ласт версия боттла

**Comment by dhvcc** [comment]
> Сообщения отправляются, но при этом вылезает ошибка.
> https://pastebin.com/54HRUT4N
> 
> ласт версия боттла

Попробуй сделать тот же запрос через `api.request`

**Comment by kforbro** [comment]
> > Сообщения отправляются, но при этом вылезает ошибка.
> > https://pastebin.com/54HRUT4N
> > ласт версия боттла
> 
> Попробуй сделать тот же запрос через `api.request`

через api.request ошибки нет

**Comment by dhvcc** [comment]
> > > Сообщения отправляются, но при этом вылезает ошибка.
> > > https://pastebin.com/54HRUT4N
> > > ласт версия боттла
> > 
> > 
> > Попробуй сделать тот же запрос через `api.request`
> 
> через api.request ошибки нет

Отправь ещё, пожалуйста, вывод реквеста, что бы модель можно было поправить

**Comment by kforbro** [comment]
> > > > Сообщения отправляются, но при этом вылезает ошибка.
> > > > https://pastebin.com/54HRUT4N
> > > > ласт версия боттла
> > > 
> > > 
> > > Попробуй сделать тот же запрос через `api.request`
> > 
> > 
> > через api.request ошибки нет
> 
> Отправь ещё, пожалуйста, вывод реквеста, что бы модель можно было поправить

await bot.api.request('messages.send', {'peer_ids': ','.join([str(i) for i in users]), 'message': 'text', 'random_id': 0})

{'response': [{'peer_id': 182065621, 'message_id': 4757}, {'peer_id': 527796430, 'message_id': 4758}]}
