### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#258]
Код:
https://pastebin.com/PEeag1pJ
Ошибка:
https://pastebin.com/uCQqnX1S

**Comment by dhvcc** [comment]
> Код:
> https://pastebin.com/PEeag1pJ
> Ошибка:
> https://pastebin.com/uCQqnX1S

Версия ботла?

**Comment by dhvcc** [comment]
> Код:
> https://pastebin.com/PEeag1pJ
> Ошибка:
> https://pastebin.com/uCQqnX1S

Вы забыли поставить запятую в кортеже, ведь у вас 1 элемент
Обычная запись `1 == (1)`, но при том `1 != (1,)`

**Comment by Timtaran** [comment]
> > Код:
> > https://pastebin.com/PEeag1pJ
> > Ошибка:
> > https://pastebin.com/uCQqnX1S
> 
> Версия ботла?

3.0

**Comment by Timtaran** [comment]
> > Код:
> > https://pastebin.com/PEeag1pJ
> > Ошибка:
> > https://pastebin.com/uCQqnX1S
> 
> Вы забыли поставить запятую в кортеже, ведь у вас 1 элемент
> Обычная запись `1 == (1)`, но при том `1 != (1,)`

Спасибо
