### ISSUE TITLE
Баг: bot.run_polling()

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#259]
RuntimeWarning: coroutine 'start_bot' was never awaited
  start_bot()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

await asyncio.sleep(1) не будет глушить
RuntimeWarning: coroutine 'start_bot' was never awaited
  start_bot()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Делал с blueprint, сейчас все в одном файле
https://pastebin.com/D1A3tqUA
да, я знаю, много говнокода.

---
vkbottle: 3.0
vkbottle-types: 0.1.19
OS: Windows 7

---

**Comment by timoniq** [comment]
`run_polling` - асинхронная функция
если вы хотите чтобы библиотека сама создала луп и запустила в нем бота используйте `bot.run_forever()`

**Comment by dhvcc** [comment]
Наверное, стоит сначала в написать беседу или флудилку

**Comment by Timtaran** [comment]
> `run_polling` - асинхронная функция
> если вы хотите чтобы библиотека сама создала луп и запустила в нем бота используйте `bot.run_forever()`

в таком случае asyncio.sleep() глушит код, как time.time()

**Comment by timoniq** [comment]
> > `run_polling` - асинхронная функция
> > если вы хотите чтобы библиотека сама создала луп и запустила в нем бота используйте `bot.run_forever()`
> 
> в таком случае asyncio.sleep() глушит код, как time.time()

ну и бред, с чего вы это взяли?

**Comment by Timtaran** [comment]
> Наверное, стоит сначала в написать беседу или флудилку

у меня бьыла такая же ситуация, мне говорили что нужен bot.run_forever().

**Comment by timoniq** [comment]
создавайте таск тогда:
```python
bot.loop.create_task(some_task())
```

**Comment by Timtaran** [comment]
> > > `run_polling` - асинхронная функция
> > > если вы хотите чтобы библиотека сама создала луп и запустила в нем бота используйте `bot.run_forever()`
> > 
> > 
> > в таком случае asyncio.sleep() глушит код, как time.time()
> 
> ну и бред, с чего вы это взяли?

https://vk.com/timtaran_yt?z=video549204433_456239437

**Comment by Timtaran** [comment]
> создавайте таск тогда:
> 
> ```python
> bot.loop.create_task(some_task())
> ```
