### ISSUE TITLE
Баг: ServerDisconnectedError (aiohttp)

### ISSUE THREAD

**Issue by Ne0shka** [vkbottle/vkbottle#261]
**Опишите баг:** Через сутки после запуска бот упал и уже не реагировал на команды

**Ожидаемое поведение:** Продолжение работы после ServerDisconnectedError

**Фактическое поведение:**
`Task exception was never retrieved`
`future: <Task finished name='Task-1' coro=<Bot.run_polling() done, defined at /home/neoshka/.local/lib/python3.8/site-packages/vkbottle/framework/bot/bot.py:56> exception=ServerDisconnectedError()>`
`Traceback (most recent call last):`
`  File "/home/neoshka/.local/lib/python3.8/site-packages/vkbottle/framework/bot/bot.py", line 60, in run_polling`
`    async for event in polling.listen():  # type: ignore`
`  File "/home/neoshka/.local/lib/python3.8/site-packages/vkbottle/polling/bot_polling.py", line 48, in listen`
`    event = await self.get_event(server)`
`  File "/home/neoshka/.local/lib/python3.8/site-packages/vkbottle/polling/bot_polling.py", line 29, in get_event`
`    return await session.request_json(`
`  File "/home/neoshka/.local/lib/python3.8/site-packages/vkbottle/http/client/aiohttp.py", line 42, in request_json`
`    async with self.session.request(method, url, data=data, **kwargs) as response:`
`  File "/home/neoshka/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__`
`    self._resp = await self._coro`
`  File "/home/neoshka/.local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request`
`    await resp.start(conn)`
`  File "/home/neoshka/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start`
`    message, payload = await self._protocol.read()  # type: ignore  # noqa`
`  File "/home/neoshka/.local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read`
`    await self._waiter`
`aiohttp.client_exceptions.ServerDisconnectedError`

**Ваш код (опционально)**: ...

**Заполните поля технической информации:**

---
vkbottle: 3.0
vkbottle-types: 0.1.18
OS: Debian Linux

---

**Comment by timoniq** [comment]
Баг точно воспроизводится на последних версиях с мастера?
