### ISSUE TITLE
Предложение: 

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#263]
Даня Репин
    
Даня Репин  12:51
Передайте Сене, чтобы он мидлвеир закинул в папку, а не в корень экземпла
а то тегать его страшно
Передайте Сене, чтобы он мидлвеир закинул в папку, а не в корень экземпла
так напиши это в основной чат как предложение?
Даня Репин
я там не сижу
просто уже сколько времени он там лежит

**Пример псевдокода (опционально):**

````python
````

**Comment by dhvcc** [comment]
Что это? Почему нельзя нормально описать?

**Comment by Timtaran** [comment]
Как добавить лейбл "инвалиид"?

**Comment by dhvcc** [comment]
> Как добавить лейбл "инвалиид"?

Только Сеня может лейблить

Просто поправь описание и пускай висит ишью
