### ISSUE TITLE
Сломаны типы у API.wall.get

### ISSUE THREAD

**Issue by lintery** [vkbottle/vkbottle#268]
![6qHqfANiIyk](https://user-images.githubusercontent.com/60360956/100750539-3c81a480-33f7-11eb-9b5b-7f99068eaca7.jpg)

**Comment by Timtaran** [comment]
а разве не [0].items ?

**Comment by lintery** [comment]
> а разве не [0].items ?

![image](https://user-images.githubusercontent.com/60360956/100750949-c9c4f900-33f7-11eb-9c55-5250e8fd9b8f.png)

**Comment by Timtaran** [comment]
> > а разве не [0].items ?
> 
> ![image](https://user-images.githubusercontent.com/60360956/100750949-c9c4f900-33f7-11eb-9c55-5250e8fd9b8f.png)

и?
