### ISSUE TITLE
Баг: неправильная типизация VBMLRule

### ISSUE THREAD

**Issue by ghost** [vkbottle/vkbottle#270]
`VBMLRule.check` должен возвращать `bool`. Но он может вернуть результат `vbml.Patcher.check`.

(Из реализации `vbml.Patcher.check`:

`def check(
        self, pattern: Pattern, text: str, ignore_validation: bool = False
    ) -> typing.Optional[typing.Union[typing.Dict[typing.Any, typing.Any], bool]]:`

Может возвращаться не только `bool`, как видите

**Comment by timoniq** [comment]
это можно решить в pr #274 заменив неправильный `-> bool` на `-> Union[dict, bool]` во всех рулзах

**Comment by 0dminnimda** [comment]
в настоящее время используется [актуальные тайпхинтинги][1]

  [1]: https://github.com/timoniq/vkbottle/blob/634dad04e907582db89aef5faec6cffecd7d276b/vkbottle/dispatch/rules/bot.py#L69
