### ISSUE TITLE
MessageView неэффективно работает с StateDispenser

### ISSUE THREAD

**Issue by ghost** [vkbottle/vkbottle#271]
`MessageView` запрашивает `StatePeer` у `StateDispenser`, даже если обработчик не пытается достать `event.state_peer`.
Что если StateDispenser обращается к базе данных? Тогда при **КАЖДОМ** сообщении будет отправляться запрос к базе данных, даже если в этом нет необходимости.

**Возможное решение по оптимизации**
Сделать вложенный класс с методом `__getattr__`, чтобы запрос к StateDispenser отправлялся, только если обработчик пытается вытащить `state_peer` из ивента.

**Comment by dhvcc** [comment]
@van-burgerberg можешь уточнить, пожалуйста, что есть `state_peer`? Он меняется от сообщения к сообщению?

**Comment by timoniq** [comment]
> @van-burgerberg можешь уточнить, пожалуйста, что есть `state_peer`? Он меняется от сообщения к сообщению?

https://github.com/timoniq/vkbottle/blob/669e417aea0b2317088f72eda5630a25f944bc5d/vkbottle/dispatch/views/bot/message.py#L39

**Comment by dhvcc** [comment]
> > @van-burgerberg можешь уточнить, пожалуйста, что есть `state_peer`? Он меняется от сообщения к сообщению?
> 
> https://github.com/timoniq/vkbottle/blob/669e417aea0b2317088f72eda5630a25f944bc5d/vkbottle/dispatch/views/bot/message.py#L39

Это я видел, я имею в общем его предназначение. Важно то, будет ли он меняться от эвента к эвенту

**Comment by timoniq** [comment]
> > > @van-burgerberg можешь уточнить, пожалуйста, что есть `state_peer`? Он меняется от сообщения к сообщению?
> > 
> > 
> > https://github.com/timoniq/vkbottle/blob/669e417aea0b2317088f72eda5630a25f944bc5d/vkbottle/dispatch/views/bot/message.py#L39
> 
> Это я видел, я имею в общем его предназначение. Важно то, будет ли он меняться от эвента к эвенту

ну да, может, это ведь стейт

**Comment by dhvcc** [comment]
@timoniq а в пределах хенделров может меняться, нужен ридонли?

**Comment by timoniq** [comment]
> @timoniq а в пределах хенделров может меняться, нужен ридонли?

1) может
2) запись в него = запрос к бд

**Comment by dhvcc** [comment]
Сначала думал про [такой пропетри](https://stackoverflow.com/questions/36666151/asynchronous-property-setter), но, там, в стейт диспенсере не совсем такая логика, так что мои полномочия тут всё

Так же не совсем понимаю как переопределять `__getattr__`, если он должен быть асинк

**Comment by axd1x8a** [comment]
Есть ещё какие-нибудь мысли по этому вопросу? Если нет, то я закрываю ишью.

**Comment by LeeeeT** [comment]
@FeeeeK это ещё почему? Зачем закрывать ишью, если проблема не решена?

**Comment by axd1x8a** [comment]
Ну я не вижу никакого хорошего решения.

**Comment by axd1x8a** [comment]
После обсуждения в чате было решено, что проблема - вовсе не проблема.
