### ISSUE TITLE
Не срабатывается ChatActionRule()

### ISSUE THREAD

**Issue by JarKz** [vkbottle/vkbottle#281]
При использовании простого хенлера:

```
@bot.on.chat_message(rules.ChatActionRule('chat_invite_user'))
async def invite(message: Message):
    return "Hi"
```

Не возрващается ответ "Hi" в чат, где бота приглашали.

И, как проверить работает ли ChatActionRule()?

**Comment by markelovstyle** [comment]
Где ты проверяешь этот рулз? В обычном чате или в чате от сообщества?

**Comment by JarKz** [comment]
Вопрос был "как проверить, работает ли ChatActionRule()", то есть я не особо понимаю то, как правильнее проверять и что необходимо делать.

**Comment by markelovstyle** [comment]
Ты сначала на мой вопрос ответь, а потом уже я отвечу на твой.

**Comment by Ne0shka** [comment]
> И, как проверить работает ли ChatActionRule()?

Я в беседе ещё писал - включи дебаг

Какая версия vkbottle?

**Comment by JarKz** [comment]
Я включал дебаг, ни одной ошибки не обнаружилось, и к тому же в логах, при работе бота и при срабанывании ивента (приглашаю юзера в чат), пишется, что хендлер блочится (тот, который чат акшин рулз), то есть уже проинициализирован.

Версия vkbottle 3.0

**Comment by JarKz** [comment]
> Где ты проверяешь этот рулз? В обычном чате или в чате от сообщества?

В обычном чате

**Comment by JarKz** [comment]
Проблема была решена переходом на другую ОС, полагаю, что он не срабатывался из-за того, что я запускал бот на Windows.
