### ISSUE TITLE
Баг: не работает PhotoUploader + BluePrints

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#283]
**Ожидаемое поведение:** 
Отправка изображения пользователю.
**Фактическое поведение:** ...
Ошибка.
https://pastebin.com/AXC3euPx
**Ваш код (опционально)**: ...
https://pastebin.com/fN6iSd8c

**Заполните поля технической информации:**

---
vkbottle: 3.0 uploaders
vkbottle-types: 0.1.21(как я помню)
OS: Windows 7

---

**Comment by timoniq** [comment]
в ошибке написано в чем проблема. для работы аплоадеров необходим модуль aiofiles. установите его

```pip install aiofiles```

**Comment by Timtaran** [comment]
> в ошибке написано в чем проблема. для работы аплоадеров необходим модуль aiofiles. установите его
> 
> `pip install aiofiles`

В беседе уже написали. :)
