### ISSUE TITLE
Предложение: запись логов в файл и возможность выводить свои логи.

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#285]
Звучит странно :)
**Описание функциональности:** 
Возможность записи логов в файл, вывод логов:
Если использовать```from loguru import logger```, то иногда возникает ошибка.

**Comment by timoniq** [comment]
какая ошибка

**Comment by Timtaran** [comment]
> какая ошибка

не помню, пока что не возникает :)
