### ISSUE TITLE
Баг: Не работает bot.labeler.vbml_ignore_case = True.

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#286]
**Опишите баг:** ...
Описан
**Ожидаемое поведение:** ...
Бот будет игнорить регистр
**Фактическое поведение:** ...
Бот не игнорит регистр
**Ваш код (опционально)**: ...
```bot.labeler.vbml_ignore_case = True
bot.run_forever()``` и ```@bot.on.chat_message(text=['кошка', 'кот', "котик", 'котенок', 'котёнок', 'котики'])
async def cat(message: Message):
	await dev_mode(message, 'Sending Cat')
	await message.answer('Котик!', attachment=random.choice(cats))
bot.labeler.vbml_ignore_case = True``` (оба варианта не работают)

**Заполните поля технической информации:**

<!-- Узнать версии установленных библиотек можно командой pip freeze -->

---
vkbottle: 3.0 uploaders
vkbottle-types:  0.1.22
OS: Windows 7 64-bit

---

<!-- Проверьте что вы кратко описали баг в названии issue -->

**Comment by timoniq** [comment]
код оформлен ужасно, но могу предположить что флаг установлен после хендлеров когда должен до

**Comment by Timtaran** [comment]
> код оформлен ужасно, но могу предположить что флаг установлен после хендлеров когда должен до

![image](https://user-images.githubusercontent.com/60805088/102386561-034d5500-3ff1-11eb-8da1-e6e0208232d2.png)
тоже не работает

**Comment by timoniq** [comment]
ну вот как всегда нужно догадываться в чем проблема
блупринты имеют свой локальный labeler и флаги таким образом не наследуются
установите флаг в каждом из блупринтов где он нужен
