### ISSUE TITLE
Вопрос: Есть ли в vkbottle 3.0 PhotoUploader?

### ISSUE THREAD

**Issue by Nidelon** [vkbottle/vkbottle#304]
Есть ли в vkbottle 3.0 PhotoUploader? Если есть, то как использовать?

**Comment by dhvcc** [comment]
@Nikitka12XD https://github.com/timoniq/vkbottle/pull/255

**Comment by Nidelon** [comment]
Спасибо за помощь, но я уже сам портировал эту функцию со 2 версии на 3 (Видать зря)
