### ISSUE TITLE
Баг: pydantic.error_wrappers.ValidationError:1 validation error for SendUserIdsResponse. В pydantic.Model не прописан response при вызове с user_ids

### ISSUE THREAD

**Issue by barsikus007** [vkbottle/vkbottle#305]
**Опишите баг:** 
`Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\PostBot\venv\lib\site-packages\vkbottle\exception_factory\error_handler\error_handler.py", line 60, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\Admin\PycharmProjects\PostBot\blueprints\commands.py", line 27, in tst
    await message.ctx_api.messages.send(message='Выберите одну из команд', user_ids=[1, 2], random_id=0)
  File "C:\Users\Admin\PycharmProjects\PostBot\venv\lib\site-packages\vkbottle_types\methods\messages.py", line 699, in send
    return model(**response).response
  File "pydantic\main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for SendUserIdsResponse
response -> peer_id
  value is not a valid integer (type=type_error.integer)`

**Ожидаемое поведение:** No exception

**Фактическое поведение:** Exception

**Ваш код (опционально)**: 
`async def tst(message: Message):
    await message.ctx_api.messages.send(message='Выберите одну из команд', user_ids=[1, 2], random_id=0)`

**Заполните поля технической информации:**
Ошибка верификации PyDantic

---
vkbottle: 3.0
vkbottle-types: 0.1.24
OS: Windows 10

---

**Comment by barsikus007** [comment]
#vkbottle-types @vkbottle-types думаю как-то так

**Comment by Timtaran** [comment]
Ну как бы ctx_api, а не ctxapi

**Comment by Timtaran** [comment]
https://vk.com/dev/messages.send - нет user_ids, используйте peer_ids

**Comment by barsikus007** [comment]
> https://vk.com/dev/messages.send - нет user_ids, используйте peer_ids

забавно, в самой документации user_ids нет, а снизу в "Пример запроса" есть
вк...

**Comment by Timtaran** [comment]
> > https://vk.com/dev/messages.send - нет user_ids, используйте peer_ids
> 
> забавно, в самой документации user_ids нет, а снизу в "Пример запроса" есть
> вк...

Он есть там, но для старых версий API:

user_idsидентификаторы получателей сообщения (при необходимости отправить сообщение сразу нескольким пользователям). Доступно только для ключа доступа сообщества. Максимальное количество идентификаторов: 100. 

список целых чисел, разделенных запятыми, устаревший параметр, доступен только для версий меньше 5.138

**Comment by Timtaran** [comment]
> > https://vk.com/dev/messages.send - нет user_ids, используйте peer_ids
> 
> забавно, в самой документации user_ids нет, а снизу в "Пример запроса" есть
> вк...

Там есть, если нажать на показ устаревших параметров.
