### ISSUE TITLE
Баг: abc.CodeErrorFactory_1: [1] Unknown error occurred

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#314]
**Опишите баг:** ...
Не работает загрузка изображение BytesIO
**Ожидаемое поведение:** ...
Бот отправит изображение.
**Фактическое поведение:** ...
https://pastebin.com/U7kA2fMM
abc.CodeErrorFactory_1: [1] Unknown error occurred
**Ваш код (опционально)**: 
https://pastebin.com/1mSrCBji
**Заполните поля технической информации:**
---
vkbottle: v3-uploaders
vkbottle-types: 0.1.24
OS: Windows 7 

---

P.S. При использовании `generate(f"1", file, img, font).read()` выдает `abc.CodeErrorFactory_100: [100] One of the parameters specified was missing or invalid: photos_list is invalid`

**Comment by timoniq** [comment]
скорее всего были сгенерированы невалидные байты из `PIL`, попробуйте сделать `seek(0)` или посмотреть на формат/флаги файла, по умолчанию это `jpg`

если проблема не решается, постарайтесь предоставить больше данных

**Comment by Timtaran** [comment]
`abc.CodeErrorFactory_100: [100] One of the parameters specified was missing or invalid: photos_list is invalid`

**Comment by Timtaran** [comment]
`seek(0)` возвращает `None`,
`server` - `{'album_id': -64, 'upload_url': 'https://pu.vk.com/***/***/upload.php?act=do_add&mid=-***&aid=-64&gid=0&peer_id=-202897716&rhash=***&api=1&method=message&mailphoto=1&server=***&_origin=https%3A%2F%2Fapi.vk.com&_sig=***', 'user_id': 0, 'group_id': 202897716}`,
`data` - `b''`
`file` - `<_io.BytesIO object at 0x00000000053A0180>`
`uploader` - `{'server': ***, 'photo': '[]', 'hash': '***'}`
`photo` -

**Comment by timoniq** [comment]
> `data` - `b''`

что такое `data`?

**Comment by Timtaran** [comment]
> > `data` - `b''`
> 
> что такое `data`?

В классе сделал logger.info для каждой переменной, во время отправки изображения.

**Comment by timoniq** [comment]
а generate вообще возвращает валидные байты? прочитайте их, может быть они пустые вообще

**Comment by Timtaran** [comment]
Только сейчас руки дошли заного чекнуть, поменял функцию при записи в файл все ок при загрузке фото:
`photo = await PhotoMessageUploader(bot.api).upload(img.read(), peer_id=2000000001)` - `abc.CodeErrorFactory_100: [100] One of the parameters specified was missing or invalid: photos_list is invalid`
`photo = await PhotoMessageUploader(bot.api).upload(img, peer_id=2000000001)` - `abc.CodeErrorFactory_1: [1] Unknown error occurred`

**Comment by Ne0shka** [comment]
> Только сейчас руки дошли заного чекнуть, поменял функцию при записи в файл все ок при загрузке фото:
> `photo = await PhotoMessageUploader(bot.api).upload(img.read(), peer_id=2000000001)` - `abc.CodeErrorFactory_100: [100] One of the parameters specified was missing or invalid: photos_list is invalid`
> `photo = await PhotoMessageUploader(bot.api).upload(img, peer_id=2000000001)` - `abc.CodeErrorFactory_1: [1] Unknown error occurred`

А ты что в upload вообще пихаешь? Дебажь
Аплоаду надо file_path кидать (местоположение файла), а не сам файл
