### ISSUE TITLE
Предложение: Авторизация в юзере

### ISSUE THREAD

**Issue by Ne0shka** [vkbottle/vkbottle#319]
**Описание функциональности:** Добавить авторизацию по логину/паролю у юзера в PR #310

**Comment by Er1one** [comment]
Политика ВКонтакте запрещает такое и сразу банит

**Comment by Ne0shka** [comment]
> Политика ВКонтакте запрещает такое и сразу банит

Прошу не вводить в заблуждение. ВКонтакте не запрещает такое, а лишь ограничивает. Банов же (на моей памяти) за это не было.

_Источник: https://vk.com/dev/auth_direct_

**Comment by dhvcc** [comment]
Не совсем понял что именно имеется ввиду

Есть же [тулзы](https://github.com/vkbottle/vkbottle/tree/master/vkbottle/tools/dev_tools/auth), или тут требуется что-то другое?

**Comment by timoniq** [comment]
> Не совсем понял что именно имеется ввиду
> 
> Есть же [тулзы](https://github.com/vkbottle/vkbottle/tree/master/vkbottle/tools/dev_tools/auth), или тут требуется что-то другое?

видимо, нужен удобный шорткат как в 2.x. `User(login="xxx", password="xxx")`

**Comment by dhvcc** [comment]
Понял, хорошо

**Comment by Ne0shka** [comment]
> > Не совсем понял что именно имеется ввиду
> > Есть же [тулзы](https://github.com/vkbottle/vkbottle/tree/master/vkbottle/tools/dev_tools/auth), или тут требуется что-то другое?
> 
> видимо, нужен удобный шорткат как в 2.x. `User(login="xxx", password="xxx")`

Да, почти, только с указанием client_id, client_secret и т.д.
Как вариант (чтобы не набивать всем этим юзера) сделать что-то вроде:
```
User().direct_auth(
    client_id = "",
    client_secret="",
    username="",
    password="",
    **kwargs
)
```

**Comment by axd1x8a** [comment]
Лучше обернуть `direct_auth` в `@classmethod` и возвращать объект юзера с токеном.
Тогда можно будет не инитить класс:
```python
user = User.direct_auth(...)
```

**Comment by axd1x8a** [comment]
Постараюсь реализовать это в ближайшее время, но сразу хочу сказать, что не вижу смысла делать поддержку двухфакторной аутентификации, поэтому ее не будет.
