### ISSUE TITLE
Баг: AttributeError: type object 'Patcher' has no attribute 'get_current'

### ISSUE THREAD

**Issue by PyYakro** [vkbottle/vkbottle#320]
**AttributeError: type object 'Patcher' has no attribute 'get_current'**
Полный скрин ошибки: https://prnt.sc/10y63ew

Все должно работать ок

**Нифига не робит**

Код:
from vkbottle import Bot, Message
bot = Bot(token)
@bot.on.message(text="My name is <name>", lower=True)
async def wrapper(ans: Message, name):
    await ans("Hello, {}".format(name))
bot.run_polling()

--------------
vkbottle==2.7.8
vkbottle-types==0.1.23
OS: Windows 10 Pro

**Comment by timoniq** [comment]
Поставьте `vbml` версии `0.5.93`

**Comment by ghost** [comment]
И `text` исправь на `My name is <name>` 🙃
