### ISSUE TITLE
Баг: Ошибка установки библиотеки

### ISSUE THREAD

**Issue by bekhruzdilshod** [vkbottle/vkbottle#326]
**Опишите баг:** Во время скачивания и сборки библиотеки с помощью команды pip install -U https://github.com/timoniq/vkbottle/archive/master.zip

**Ожидаемое поведение:** Успешная установка библиотеки

**Фактическое поведение:** ERROR (https://pastebin.com/8CKB8wLa)

**Ваш код (опционально)**: 
pip install -U https://github.com/timoniq/vkbottle/archive/master.zip

---
vkbottle: -
Python: 3.7.7
OS: Windows 10

---

**Comment by ronmount** [comment]
Накати 3.8.5 и повтори, вроде должно быть ок.

**Comment by axd1x8a** [comment]
У вас ошибка синтаксиса в системном пакете. Исправьте или переустановите его.

**Comment by bekhruzdilshod** [comment]
> У вас ошибка синтаксиса в системном пакете. Исправьте или переустановите его.

Это как, прошу прощения?

**Comment by ghost** [comment]
> > У вас ошибка синтаксиса в системном пакете. Исправьте или переустановите его.
> 
> Это как, прошу прощения?

попробуй `pip uninstall uuid` (https://github.com/bigchaindb/bigchaindb/issues/1848)
