### ISSUE TITLE
Предложение: рефактор Middleware

### ISSUE THREAD

**Issue by dhvcc** [vkbottle/vkbottle#328]
**Описание функциональности:**

На данный момент, `middleware` возвращает значение `None/MiddlewareResponse(False)/...` и этим определяет, будет ли выполняться дальнейший хендлинг или нет. Я предлагаю сделать более стандартизированный и понятный интерфейс

Мы имеем дело с `HTTP` и веб технологиями, поэтому это предложение основывается реализациях популярных веб-фреймворков

1. `Middleware` должен всегда возвращать значение, `return event (response в вебе)` либо же `return next(event)`/`return handleNext(event)`
2. Что бы прекратить хендлинг сообщения, `middleware` должен вернуть `return error('message')`. Так же `middleware` может при ошибке модифицировать контекст (`event`) таким образом `event.error = "response message"` , что бы обработать ошибку позже, на уровне декораторов

-------

Так же хотелось бы иметь четкий нейминг и совпадение с сигнатурой в документации. [Тут](https://github.com/timoniq/vkbottle/blob/c602020865deee3204072e07fbfaf8ca0261dfa4/docs/tutorial/middlewares-return-managers.md#async-def-preself-event) и далее сигнатура обозначает правильное название `event`, что близко по смыслу к контексту, а в примерах кода это уже `message`, что путает начинающих разработчиков, которые начинают думать, что `Middleware` похож на декораторы и гварды

**Референсы**

1. [express](https://expressjs.com/en/guide/using-middleware.html) `next()`/`res.send()`
2. [django](https://docs.djangoproject.com/en/3.2/topics/http/middleware/) `return response`/`raise Exception`
3. [laravel](https://laravel.com/docs/5.0/middleware) `return $next($request)`

**Comment by ghost** [comment]
PR'ы приветствуются 😉

**Comment by dhvcc** [comment]
@timoniq

**Comment by timoniq** [comment]
спасибо, идея хорошая, вот предлагаемый мной вариант синтаксиса:

```python
class SomeMiddleware(BaseMiddleware):
    async def check(self, event: Message):
        if event.is_bad():
            return self.error("bad event")
        self.send("param", 1)
```

**Comment by dhvcc** [comment]
> спасибо, идея хорошая, вот предлагаемый мной вариант синтаксиса:
> 
> ```python
> class SomeMiddleware(BaseMiddleware):
>     async def check(self, event: Message):
>         if event.is_bad():
>             return self.error("bad event")
>         self.send("param", 1)
> ```

Окей, как будет время попробую что-то накидать
