### ISSUE TITLE
Баг: AttributeError: 'MessageView' object has no attribute 'middleware_instances'

### ISSUE THREAD

**Issue by monosans** [vkbottle/vkbottle#335]
**Опишите баг:** баг появился в c6ebefbf95672ebc39a4ca780ab20157792c4bbc, в предыдущем коммите его не было.

**Ожидаемое поведение:** вывод полученного сообщения в терминал

**Фактическое поведение:** https://pastebin.com/NpFLKFM9

**Ваш код (опционально)**: https://pastebin.com/EM4GdgKz

**Техническая информация:**

---

vkbottle: c6ebefbf95672ebc39a4ca780ab20157792c4bbc
vkbottle-types: 0.1.24
OS: GNU/Linux

---

**Comment by dhvcc** [comment]
Быстро же (:
