### ISSUE TITLE
Предложение: Autoflake

### ISSUE THREAD

**Issue by dhvcc** [vkbottle/vkbottle#338]
**Описание функциональности:** Добавить `autoflake` как дев зависимость, для обработки импортов в помощь `isort`

`isort` сам по себе не может удалять неиспользованные импорты, `autoflake` может

**Comment by dhvcc** [comment]
@timoniq 
Эти импорты ведь не нужны? Я помню, что помимо инитов есть `bot.py` из которого не нужно удалять импорты, эти файлы такие же?
![image](https://user-images.githubusercontent.com/18076967/117311491-e5dc3300-ae8c-11eb-80ec-ef5481d408ee.png)

**Comment by timoniq** [comment]
> @timoniq 
> 
> Эти импорты ведь не нужны? Я помню, что помимо инитов есть `bot.py` из которого не нужно удалять импорты, эти файлы такие же?
> 
> ![image](https://user-images.githubusercontent.com/18076967/117311491-e5dc3300-ae8c-11eb-80ec-ef5481d408ee.png)
> 
> 

Нет, это лишние импорты
