### ISSUE TITLE
Баг: Неполная модель

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#339]
Модель немного отличается от оригинальной(надо получить id поста группы)

**Ожидаемое поведение:** ...
{"ts":"353","updates":[{"type":"wall_repost","object":{"id":2058,"from_id":549204433,"owner_id":549204433,"date":1620397707,"post_type":"post","text":"","copy_history":[{"id":9,"owner_id":-,"from_id":-,"date":1620396744,"post_type":"post","text":"Скоро будет доступен бонус за репост!","post_source":{"type":"vk"}}],"can_archive":true,"is_archived":false,"comments":{"count":0},"is_favorite":false,"donut":{"is_donut":false},"short_text_rate":0.800000},"group_id":,"event_id":""}]}
**Фактическое поведение:** ...
{'access_key': None, 'attachments': None, 'copyright': None, 'date': 1620397707, 'edited': None, 'from_id': 549204433, 'geo': None, 'id': 2058, 'is_archived': False, 'is_favorite': False, 'likes': None, 'owner_id': 549204433, 'post_source': None, 'post_type': <WallPostType.POST: 'post'>, 'reposts': None, 'signer_id': None, 'text': '', 'views': None, 'postponed_id': None}
**Ваш код (опционально)**: ...
https://pastebin.com/j2bxWENR

**Заполните поля технической информации:**

---
vkbottle: 3.0
vkbottle-types: 0.1.24
OS: Windows 7 64

---

**Comment by timoniq** [comment]
будет исправлено в следующем релизе `vkbottle-types`, пока можете поставить` dataclass=dict` и не использовать проблемную модель

**Comment by Timtaran** [comment]
Спасибо.
