### ISSUE TITLE
Баг: Ошибка в аплоадере

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#342]
venv\lib\site-packages\vkbottle\tools\dev_tools\uploader\video.py, line 33, in upload
    return self.generate_attachment_string("video", video["owner_id"], video["id"])
значения video - {'video_hash': '5b3d4a3e0285362171', 'size': 21966892, 'owner_id': 549204433, 'video_id': 456239777}

---
vkbottle: 3.0
vkbottle-types: 0.1.24
OS: Windows 7

---

**Comment by Timtaran** [comment]
Контрибутить не умею нормально, да и темболее у меня версия с юзерботом)

**Comment by Ne0shka** [comment]
Не понятно, что вы ожидаете с такой ишшуей
Есть шаблон, попробуйте отредактировать по нему:

![image](https://user-images.githubusercontent.com/37632288/119267374-54482180-bbff-11eb-8f95-2712769155bc.png)
