### ISSUE TITLE
vkbottle-types Баг: Ошибка валидации messages.send(peer_ids=)

### ISSUE THREAD

**Issue by kforbro** [vkbottle/vkbottle#356]
**Опишите баг:** Ошибка валидации messages.send(peer_ids=)

**Фактическое поведение:** https://pastebin.com/E2DVs4SW

**Ваш код (опционально)**:
![image](https://user-images.githubusercontent.com/39985355/121492569-a5b62600-c9df-11eb-8bfa-95dc3f613bbc.png)

**Заполните поля технической информации:**
---
vkbottle @ https://github.com/timoniq/vkbottle/archive/master.zip
vkbottle-types @ https://github.com/timoniq/vkbottle-types/archive/master.zip
---

**Comment by axd1x8a** [comment]
Здравствуйте, можете предоставить ответ сервера?

**Comment by kforbro** [comment]
> Здравствуйте, можете предоставить ответ сервера?

Здравствуй

```
{'response': [{'conversation_message_id': 1831,
               'message_id': 3222,
               'peer_id': 182065621},
              {'conversation_message_id': 108,
               'message_id': 3223,
               'peer_id': 324926725}]}
```

**Comment by axd1x8a** [comment]
Спасибо, сейчас исправлю

**Comment by axd1x8a** [comment]
Обновите vkbottle-types с мастера
`pip install -U https://github.com/timoniq/vkbottle-types/archive/refs/heads/master.zip`
