### ISSUE TITLE
Баг: баг в hello world из README

### ISSUE THREAD

**Issue by MikhaelMIEM** [vkbottle/vkbottle#357]
**Опишите баг:** 
Запускаю код из README, выглядит так:
```
import os
from vkbottle.bot import Bot

bot = Bot(os.environ['TOKEN'])

@bot.on.message()
async def handler(_) -> str:
    return "Hello world!"

bot.run_forever()
```
Посылаю любое сообщение в личку группы, получаю:
<img width="882" alt="eerror" src="https://user-images.githubusercontent.com/45197684/121585676-864ce680-ca3b-11eb-9716-6d7c30034897.PNG">

Внутрь в код не лез

**Версии:**
---
vkbottle: 3.0.2
vkbottle-types: 5.131
OS: Windows 10

---

**Comment by axd1x8a** [comment]
Что-то очень странное, вы пробовали обновится с мастера?
Если нет, то попробуйте, заодно обновите и vkbottle-types.

**Comment by axd1x8a** [comment]
Ещё проверьте версию апи в настройках группы, она должна быть не меньше 5.103, но желательно выбрать последнюю.

**Comment by MikhaelMIEM** [comment]
И правда, по дефолту стояла старая версия апи (5.50). После изменения версии апи на последнюю всё заработало =)
Есть ли возможность сделать информативное сообщение об ошибке в случае использования старых версий апи?

**Comment by axd1x8a** [comment]
Есть вариант ставить последнюю версию при запуске, но это нужно обсудить с автором.

**Comment by dhvcc** [comment]
> Есть вариант ставить последнюю версию при запуске, но это нужно обсудить с автором.

Лучше перенеи дев ветку на 5.130 типы и АПИ. Это нужно сделать, но я не могу уже
