### ISSUE TITLE
Баг: {при запросах get_ads_layout}

### ISSUE THREAD

**Issue by Siero2017** [vkbottle/vkbottle#365]
**Опишите баг:** когда я обращаюсь к к рекламному кабинету через get_ads_layout у меня выходит ошибка 390 validation errors for GetAdsLayoutResponse. все обязательные параметры я соблюдал 

**Ожидаемое поведение:** массив с описанием рекламных обьявлений 

**Фактическое поведение:** возвращает исключение(боль и страдания)
                                                 response -> 0 -> preview_link
                                                 value is not a valid list (type=type_error.list)
                                                 ...
                                                 response -> 97 -> preview_link
                                                 value is not a valid list (type=type_error.list)

**Ваш код (опционально)**: ...

**Заполните поля технической информации:**

---
vkbottle @ https://github.com/timoniq/vkbottle/archive/master.zip
vkbottle-types==5.131
OS: Windows 10

---

**Comment by axd1x8a** [comment]
Можете предоставить ответ сервера?
