### ISSUE TITLE
Предложение: общий blueprint для пакета

### ISSUE THREAD

**Issue by BoberMod** [vkbottle/vkbottle#367]
**Описание функциональности:** есть большое количество хендлеров, часть из них доступна только для админов, часть только в ЛС, часть только в общих чатах. Можно было бы сделать 3 файла для каждого из перечисленных кейсов, но:

1. при большом кол-ве хендлеров получается нечитаемая мешанина
2. при разбитии на несколько файлов в каждом из них надо создавать блюпринт

Я решил сделать под каждый тип (ЛС, чат и админ) отдельные пакеты, в `__init.py__` которых прописал создание блюпринта. В итоге в пакете у меня несколько файлов, каждый отвечает за свою функциональность в боте и использует один и тот же блюпринт с правилами. Но из-за способа проверки наличия блюпринта в импортируемом файле, бот валится: 
```
            bp_names = re.findall(
                r"^(\w+) = (?:Bot|User|)Blueprint\(", file.read(), flags=re.MULTILINE
            )
            assert len(bp_names) == 1
```
Мой блюпринт объявлен в `__init__.py` пакета, откуда он импортируется и используется в файлах. Соответственно регулярка ничего не находит.

Структура файлов:
```
project 
│   bot.py
└── blueprints
    └─── group
    │    │     __init__.py (inits blueprint)
    │    │    some_handlers_1.py (imports blueprint from __init__.py)
    │    │    some_handlers_2.py (imports blueprint from __init__.py)
    └─── private
         │    same structure....
```

Что думаете о таком подходе?

**Comment by axd1x8a** [comment]
А зачем вам этот способ добавления блупринтов?
Просто импортируйте их в главный файл и сделайте так: `bp.load(bot)`

**Comment by axd1x8a** [comment]
Данный способ нужен, когда у вас в папке множество модулей, а в каждом из них свой блупринт.

**Comment by BoberMod** [comment]
> Просто импортируйте их в главный файл и сделайте так: `bp.load(bot)`

Проблема в том, что я хочу разделить по модулям, в каждом из которых есть свой блюпринт. Этот блюпринт мне нужен в нескольких файлах в модуле. Чтобы не создавать их каждый раз, я хочу вынести создание блюпринта в отдельный файл и заимпортить его в файлы внутри модуля. 
НО т.к. мой файл с инитом блюпринта это `__init__.py`, то он игнорируется регуляркой внутри `load_blueprints_from_package`. Как воркэраунд можно просто убрать `__` из названия файла и все, но интересно, по какой причине решили исключить зарезервированные __файлы__. Или я чего-то не понимаю, и `__init__` для этого использовать не ок.

**Comment by axd1x8a** [comment]
Да, объявлять что-либо в `__init__.py` не совсем правильно.
