### ISSUE TITLE
Вопрос: Как настроить фильтр на проверку текста внутри сообщения

### ISSUE THREAD

**Issue by ghost** [vkbottle/vkbottle#372]
**Вопрос:** ...

Мне нужно отправить ответ в том случае если "Привет" или другие строки из списка, есть внутри сообщения. Как это можно реализовать?

Пример того что мне нужно:
![image](https://user-images.githubusercontent.com/87802281/126957144-0c1740db-deff-40bb-8dc4-6f2ab7302daf.png)

**Comment by timoniq** [comment]
`@bot.on.message(`

* `func=lambda m: "привет" in m.text`
* `text="<!>привет<!>`
* `regexp=r".*привет.*"`

`)`
