### ISSUE TITLE
Не прикрепляется фото в сообщение

### ISSUE THREAD

**Issue by ksusonic** [vkbottle/vkbottle#381]
Эта фишка deprecated в текущем на данный момент апи вк?

https://github.com/vkbottle/vkbottle/blob/6811891871236017ef5855d8ae480e7810dfc89a/examples/high-level/photo_upload_example.py#L12

**Comment by axd1x8a** [comment]
Скорее всего у бота просто нет доступа к этому аттачменту. Их отправка таким способом вряд-ли будет удалена вк.

**Comment by axd1x8a** [comment]
Никаких проблем c этим аттачментом нет.
![image](https://user-images.githubusercontent.com/26704473/128650722-4c21e1a4-13e3-4e14-ab91-bc0270faeccc.png)

**Comment by Chimtek** [comment]
await m.answer(attachment="photo-41629685_457239401") - это работает и у меня в боте
await m.answer(attachment="photo-347239_457244924") - а больше ничего не работает из такого, бот тот же

**Comment by luwqz1** [comment]
@Chimtek VK API docs != vkbottle
