### ISSUE TITLE
Баг: ошибка при парсинге ответа апи после отправки сообщение нескольким пользователям сразу.

### ISSUE THREAD

**Issue by drforse** [vkbottle/vkbottle#384]
**Опишите баг:** При отправке сообщения на peer_ids, vk api версии 5.131 возвращает в response список словарей `{'response': [{'peer_id': ..., 'message_id': ..., 'conversation_message_id': ...}]}`, но библиотека пытается парсить его, как int.

**Ожидаемое поведение:** Парсинг response в соответствии с апи вк

**Фактическое поведение:** Парсинг response также, как при отправке одному пользователю, то-есть int.

**Ваш код (опционально)**: 
handler: https://hatebin.com/otevoqmzuq
vk_bottle_ext if needed: https://hatebin.com/dtmpkwjgpq
traceback: https://hatebin.com/rfovstgjvi

**Заполните поля технической информации:**

---
vkbottle: 3.0.2
vkbottle-types: 5.131
OS: Windows 10
python version: 3.9
vk api version in group settings: 5.131

---

**Comment by timoniq** [comment]
должно быть исправлено [здесь](https://github.com/vkbottle/types/commit/6ef013e216705a1a91b2999f5718ba96817a2d3c), обновите типы

**Comment by drforse** [comment]
> должно быть исправлено [здесь](https://github.com/vkbottle/types/commit/6ef013e216705a1a91b2999f5718ba96817a2d3c), обновите типы

Хорошо, обновлю. Но по дефолту встала не последняя версия, получается. Как-то не подумал обновить типы поэтому)

**Comment by drforse** [comment]
> должно быть исправлено [здесь](https://github.com/vkbottle/types/commit/6ef013e216705a1a91b2999f5718ba96817a2d3c), обновите типы

Окей, спасибо. На pypi просто нету ещё этого фикса, потому так получилось.  :)
