### ISSUE TITLE
Предложение: передача контекста руководствуясь сигнатурой хендлера

### ISSUE THREAD

**Issue by timoniq** [vkbottle/vkbottle#385]
Скорее всего лучше привязываться к from_func_handler и уже в нем изменять контекст базируясь на сигнатуре функции/по аннотациям. Таким образом в хендлер не будут стучаться лишние аргументы из контекста

**Comment by ghost** [comment]
Что делать в ситуации, когда тип аргумента, указанный в сигнатуре хендлера, не соответствует настоящему типу аргумента, хранящегося в контексте?

**Comment by timoniq** [comment]
> Что делать в ситуации, когда тип аргумента, указанный в сигнатуре хендлера, не соответствует настоящему типу аргумента, хранящегося в контексте?

думаю, можно игнорировать это
