### ISSUE TITLE
Помогите организовать ответ на сообщение.

### ISSUE THREAD

**Issue by deathpython** [vkbottle/vkbottle#395]
У моего бота появилась необходимость отвечать на полученное сообщение внутри беседы. В vk api используется is_reply или reply_to. Так и не получилось у меня заставить его работать. Простите за тупые вопросы, но нужен пример работы с reply_to или хотя бы forward

**Comment by ghost** [comment]
> Так и не получилось у меня заставить его работать.

@deathpython покажите свой код

**Comment by ghost** [comment]
[Вот тут](https://github.com/vkbottle/vkbottle/blob/dev/vkbottle/tools/dev/mini_types/bot/message.py#L63) можно глянуть пример.
Если отвечаете на сообщение с помощью `message.answer`, нужно передать `MessagesForward` в аргументе `forward`

**Comment by deathpython** [comment]
Не могу никак понять логику vkbottle. Прилагаю последний вариант, который я использовал.
Сразу извиняюсь за боль в глазах

@bot.on.chat_message(text=["Привет"])
async def forward_handler(messege: Message) -> None:
    try:
        forward_info = await bot.api.messages.get_conversation_message_ids(
            peer_id=peer_id
        )
        forward = MessagesForward(conversation_message_ids=forward_message_ids, peer_id=self.peer_id).json()
        return
    except Exception:
        print("у меня нет прав администратора")
    async def message_handler(message: Message) -> None:
        await message.answer("привет0")

**Comment by axd1x8a** [comment]
А у вас бот на странице пользователя? Если да, то достаточно этого:
```python
...
    await message.answer("text", reply_to=message.id)
...
```
А если у вас группа, то reply_to может работать только в личных сообщениях, тк `message.id` в чатах всегда будет `0`
Чтобы ответ работал и в чатах, нужно сделать так:
```python
...
    forward = MessagesForward(
        conversation_message_ids=[message.conversation_message_id],
        peer_id=message.peer_id
        is_reply=True
    ).json()
    await message.answer("text", forward=forward)
...
```

**Comment by deathpython** [comment]
Спасибо всем за помощь! Проблема была в использование `is_reply=True`. Так же необходимо импортировать `from vkbottle_types.objects import MessagesForward`
