### ISSUE TITLE
Создание опросов

### ISSUE THREAD

**Issue by deathpython** [vkbottle/vkbottle#398]
Подскажите, чего в этой схеме не хватает для создания опроса?
Опрос, должен прийти в беседу
***
@bot.on.chat_message(FromUserRule())
async def pools(message: Message) -> None:
    peer_id = message.peer_id
    api = API(bot)
 await message.answer(api.polls.create(question="да?", add_answers=["да", "да"], peer_id=message.peer_id)) ***

**Comment by axd1x8a** [comment]
Ответы на подобные вопросы стоит искать в документации вк.
https://vk.com/dev/polls.create

Там написано, что этот метод доступен только с токеном пользователя.

**Comment by deathpython** [comment]
> Ответы на подобные вопросы стоит искать в документации вк.
> https://vk.com/dev/polls.create
> 
> Там написано, что этот метод доступен только с токеном пользователя.

Вы имеете в виду, что ботам такой функционал недоступен?

**Comment by axd1x8a** [comment]
Этот метод нельзя вызвать с токеном сообщества.
![](https://i.imgur.com/vfbo41n.png)
