### ISSUE TITLE
Баг: Неэффективная работа с сообщениями

### ISSUE THREAD

**Issue by kaejuh** [vkbottle/vkbottle#406]
**Опишите баг:** В dev ветке обработчик сообщений пользователя проверяет каждое приходящее сообщение через Messages.GetById.

**Ожидаемое поведение:** При большом количестве поступающих сообщений может вызвать ошибку Too many requests per second.

**Фактическое поведение:** Вызывает ошибку Too many requests per second только при большом потококе сообщений.

**Заполните поля технической информации:**

---
vkbottle: https://github.com/vkbottle/vkbottle/tree/dev
vkbottle-types: 5.131
OS: Windows 8.1

---

**Comment by axd1x8a** [comment]
Используйте [генераторы токенов](https://vkbottle.readthedocs.io/ru/latest/low-level/api/token-generator/)

**Comment by kaejuh** [comment]
> Используйте [генераторы токенов](https://vkbottle.readthedocs.io/ru/latest/low-level/api/token-generator/)

Но, разве id сообщений относительно каждого токена не разные? В таком случае такой подход не сработает.

**Comment by axd1x8a** [comment]
>  Но, разве id сообщений относительно каждого токена не разные? В таком случае такой подход не сработает.

Нет конечно, все это сделано, чтобы получать нормальный объект сообщения из того, что присылает вк (почти ничего)

**Comment by kaejuh** [comment]
> Нет конечно, все это сделано, чтобы получать нормальный объект сообщения из того, что присылает вк (почти ничего)

Ну хорошо, будем надеяться, что вк починит событие сообщений или найдется альтернативный способ получать объект сообщения без дополнительных запросов к API.
