### ISSUE TITLE
Баг: 65 is not a valid UserEventType

### ISSUE THREAD

**Issue by kaejuh** [vkbottle/vkbottle#408]
**Опишите баг:** Неизвестное событие или возможно не учтено в обработчике.

**Ожидаемое поведение:** ValueError

**Фактическое поведение:** Возникает по неизвестной причине, вне зависимости от кода, при обработке сообщений

**Код ошибки**: 
https://dumpz.org/bKQMeZyhbNYr
Password: vkbottle

---
vkbottle: https://github.com/vkbottle/vkbottle/tree/dev
vkbottle-types: 5.131
OS: Windows 8.1

---

**Comment by axd1x8a** [comment]
Исправлено в 157e858
