### ISSUE TITLE
Вопрос: Как закрыть сессию в API? [Решено]

### ISSUE THREAD

**Issue by kaejuh** [vkbottle/vkbottle#411]
**Вопрос:**  Вот допустим, у меня есть список объектов [API(token), API(token),...]. Однако если пройтись по нему циклом for с каким либо методом, то я получаю ошибку-предупреждение, что у меня есть не закрытая сессия, как её закрыть напрямую у одного из объектов API?

**Comment by timoniq** [comment]
await api.http.session.close()

**Comment by kaejuh** [comment]
> await api.http.session.close()

Есть проблема, там нет атрибута session, в dev ветке его может забыли?
Но, есть http_client(), у него есть .close(), однако это не работает, ошибка остаётся...

**Comment by axd1x8a** [comment]
Да, в dev ветке нужно закрывать сессию так, но учтите, что это нужно сделать для каждого API.
Либо назначить им всем один http:
```python
from vkbottle.http import SingleSessionManager
from vkbottle import API
http = SingleSessionManager()
api = API(session_manager=http)
```

**Comment by kaejuh** [comment]
@FeeeeK спасибо, помогло!
Спасибо за оперативный ответ.
