### ISSUE TITLE
Баг: бот не запускается, если в одном или нескольких скриптах используются эмодзи

### ISSUE THREAD

**Issue by Inui-senpai** [vkbottle/vkbottle#412]
**Опишите баг:** если в строке для отправки искомого сообщения в методе message.send() прописан эмодзи (и здесь абсолютно не важно, как он был вставлен: через меню Windows+Ю или как Юникод-подобие), запуск бота прекращается с ошибкой "UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position (любая позиция в абсолютно любом скрипте, где встретился эмодзи): character maps to \<undefined\>". Ошибка обработки случается практически с любым эмодзи (например, с обычными "🙂", "🙃" проблем нет, но проблемы возникают уже с "😘"), но если стоит эмодзи, составленный из двух символов (например, "☝️"), то стопор произойдёт однозначно.

**Ожидаемое поведение:** бот запускается и отвечает на "привет" сообщением "Привет, [имя]. 😊"

**Фактическое поведение:** аварийное завершение работы со следующим трейсбэком:
```
Traceback (most recent call last):
  File "D:\Downloads\rpatool\Discord Bots\Mari Ohara VK\index.py", line 11, in <module>
    for cmd in load_blueprints_from_package("commands"):
  File "C:\Users\Monika\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\tools\dev_tools\utils.py", line 54, in load_blueprints_from_package
    r"^(\w+) = (?:Bot|User|)Blueprint\(", file.read(), flags=re.MULTILINE
  File "C:\Users\Monika\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 6710: character maps to <undefined>
```

**Ваш код (опционально)**: https://pastebin.com/wAnk1SHP

**Заполните поля технической информации:**

---
vkbottle: 3.0.2
vkbottle-types: 5.131.119.2
OS: Windows 11

---

**Comment by axd1x8a** [comment]
Вам нужно поставить кодировку utf-8 для питона

**Comment by axd1x8a** [comment]
Для этого напишите в консоли 
`set PYTHONIOENCODING=utf8`

**Comment by axd1x8a** [comment]
Исправлено в afa0258, установите версию с dev ветки или дождитесь релиза 3.1
