### ISSUE TITLE
Предложение:Добавить решедулер в обработчик сообщений.

### ISSUE THREAD

**Issue by kaejuh** [vkbottle/vkbottle#414]
**Описание функциональности:** Добавить решедулер в dev ветку для обработчика сообщений, чтобы он смог обработать сообщение позже в любом случае, если это возможно.

**Comment by axd1x8a** [comment]
Просто реализуете это сами через мидлвари.

**Comment by axd1x8a** [comment]
Через asyncio.sleep можно отложить обработку текущего евента. Тк на обработка производится внутри Task asyncio, это не повлияет на обработку остальных евентов.

**Comment by kaejuh** [comment]
> Через asyncio.sleep можно отложить обработку текущего евента. Тк на обработка производится внутри Task asyncio, это не повлияет на обработку остальных евентов.

Немного непонятно, как же вернуть например необработанный message_id обратно в event так, будто он новый.

То есть, ловлю ошибку Too many requests per second, и как отдать параметры снова на обработку, мидлварь срабатывает, однако хэндлер ошибок перехватывает ошибку и получается нужно вернуть из хэндлера ошибок данные в мидлварь обратно, а уже с мидлваря отправить через self.send('message': msg_id) так?
