### ISSUE TITLE
Вопрос: Как получить объект ивента сообщения

### ISSUE THREAD

**Issue by kaejuh** [vkbottle/vkbottle#415]
**Вопрос:** Как получить объект самого ивента сообщения в обход get.ById напрямую?

Инфо: Dev ветка, для юзер типов.

**Comment by axd1x8a** [comment]
Ловить сообщение через raw_event хендлер.

**Comment by kaejuh** [comment]
> Ловить сообщение через raw_event хендлер.

@bp.on.raw_event(UserTypes.MessageNew)
async def test_raw(mes: UserTypes.MessageNew):
logger.info(f'Вы поймали сырое сообщение {mes}')
Такая конструкция не работает

**Comment by axd1x8a** [comment]
Исправлено в  6695dcd

**Comment by kaejuh** [comment]
> Исправлено в [6695dcd](https://github.com/vkbottle/vkbottle/commit/6695dcde32eb7416c49c6009610d7749f671c093)

Благодарю
