### ISSUE TITLE
Баг: ContentTypeError при upload'е изображения

### ISSUE THREAD

**Issue by monosans** [vkbottle/vkbottle#418]
**Опишите баг:** ContentTypeError при upload'е изображения.

**Ожидаемое поведение:** успешный upload изображения.

**Фактическое поведение:** https://pastebin.com/96VB507w

**Ваш код**: https://pastebin.com/9K9fATdD

**Техническая информация:**

---

vkbottle: https://github.com/vkbottle/vkbottle/commit/d293d3301f39427260328c1b6d6164d9d24776de
vkbottle-types: 5.131.119.2
OS: Arch Linux

---

**Comment by axd1x8a** [comment]
Уже исправлено в d293d33

**Comment by axd1x8a** [comment]
Теперь точно работает (031e195)
