### ISSUE TITLE
Вопрос: Поддерживается ли python 3.10 и выше?

### ISSUE THREAD

**Issue by kaejuh** [vkbottle/vkbottle#419]
Вопрос по поддержке версий python 3.10 и выше

**Comment by axd1x8a** [comment]
На windows не собираются некоторые зависимости, на linux пока не проверяли.

**Comment by kaejuh** [comment]
А чем может быть вызвано такое?
  
File ".../venv/lib/python3.9/site-packages/vkbottle/dispatch/views/user/message.py", line 34, in process_event
    return event_type == UserEventType.NEW_MESSAGE
           │             └ <enum 'UserEventType'>
           └ <UserEventType.MESSAGE_NEW: 4>
  File ".../python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
                         └ 'NEW_MESSAGE'

AttributeError: NEW_MESSAGE

**Comment by axd1x8a** [comment]
Новые типы, их только dev ветка поддерживает

**Comment by axd1x8a** [comment]
f760fe1
Кстати, в чатах вам быстрее ответят на все вопросы, ссылки на них можно найти в readme.
