### ISSUE TITLE
Баг: неправильный датакласс в обработчике raw_event юзера.

### ISSUE THREAD

**Issue by kaejuh** [vkbottle/vkbottle#420]
**Вопрос:** Какая функция возращает собственно сам event, чтобы его можно было указать raw_event декоратору

**Comment by axd1x8a** [comment]
Не совсем понимаю вопрос, что именно вы хотите сделать?

И если не сложно, задавайте вопросы в чате [Telegram](https://t.me/vkbottle_ru) или [VK](https://vk.me/join/AJQ1d7fBUBM_800lhEe_AwJj), там вам помогут гораздо быстрее, чем я сделаю это здесь.

**Comment by kaejuh** [comment]
@FeeeeK Не работает в dev ветке обработка UserEvent
```
@bp.on.raw_event(event=UserEventType.MESSAGE_NEW, dataclass=UserTypes.MessageNew)
async def raw_test(event: UserTypes.MessageNew):
    logger.info(event)
```

Конструкция возращает ошибку:
`TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given`

Насчет чатов, ничего страшного, я подожду, спасибо.

**Comment by axd1x8a** [comment]
raw_event в юзере не может иметь датакласс, тк там приходит лист, а не объект
![image](https://user-images.githubusercontent.com/26704473/139163679-02853d65-24f4-483e-8b0c-4877f3192ff5.png)

**Comment by kaejuh** [comment]
> raw_event в юзере не может иметь датакласс, тк там приходит лист, а не объект ![image](https://user-images.githubusercontent.com/26704473/139163679-02853d65-24f4-483e-8b0c-4877f3192ff5.png)

Без датакласса тогда:
`TypeError: 'int' object is not iterable`

**Comment by axd1x8a** [comment]
> Насчет чатов, ничего страшного, я подожду, спасибо.

Беда не столько во времени, сколько в том, что на ишью отвечу только я, а в чате любой из 159 участников.

**Comment by axd1x8a** [comment]
886d61cbcb34f111c69b73523a2ab6cef8606a50 исправлено

**Comment by kaejuh** [comment]
> > Насчет чатов, ничего страшного, я подожду, спасибо.
> 
> Беда не столько во времени, сколько в том, что на ишью отвечу только я, а в чате любой из 159 участников.

Ну, просто когда открываю ишью на гитхабе, то я более уверен, что на него ответит тот, кто работает с кодом фреймворка напрямую, возможно даже сделает bug fix, как Вы сделали сейчас. А в чате вопрос быстро (который возможно являлся багом) затеряется в потоке других сообщений. 
Спасибо за оперативный фикс :+1:

**Comment by axd1x8a** [comment]
Потом посмотрю, спокойной ночи.

**Comment by kaejuh** [comment]
@FeeeeK 
```
File ".../venv/lib/python3.10/site-packages/vkbottle/dispatch/base.py", line 22, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
          │    │            │      │        │    └ <vkbottle.dispatch.dispenser.builtin.BuiltinStateDispenser object at 0x7fb13a543610>
          │    │            │      │        └ <vkbottle.dispatch.base.Router object at 0x7fb13a543220>
          │    │            │      └ <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
          │    │            └ [4, 2222222, 8227, 2000000014, 1635430261, 'testing', 'test']
          │    └ <function ABCRawEventView.handle_event at 0x7fb13aa11120>
          └ <RawUserEventView handlers={<UserEventType.MESSAGE_NEW: 4>: [HandlerBasement(dataclass=<class 'list'>, handler=<FromFuncHandl...
  File ".../venv/lib/python3.10/site-packages/vkbottle/dispatch/views/abc/raw.py", line 47, in handle_event
    setattr(event_model, "unprepared_ctx_api", ctx_api)
            │                                  └ <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
            └ [4, 2222222, 8227, 2000000014, 1635430261, 'testing', 'test']

AttributeError: 'list' object has no attribute 'unprepared_ctx_api'
```
Фикс не сработал или я что-то делаю не так?
Доброго времени суток.

**Comment by axd1x8a** [comment]
9f0dcf55e11f3c04b4c8a2ecf4aa4d5a233738fb готово.
