### ISSUE TITLE
Автоматическое разбиение длинного сообщения

### ISSUE THREAD

**Issue by TochnoNePercy** [vkbottle/vkbottle#427]
В ВК приложении или браузере, если сообщение длиннее 1000 символов оно автоматически разбивается на несколько сообщений, однако если попытаться отправить сообщение длиной от 1000 символов ботом, вылетает ошибка. 
   Суть сделать автоматическое разбиение длинных сообщений, делить можно по логическим частям/меткам - точкам, абзацам, пробелам(если уж вообще ничего нет)

**Comment by ghost** [comment]
Никто не запрещает вам сделать это в своём боте)

**Comment by TochnoNePercy** [comment]
В принципе да, но это было бы приятным бонусом)

**Comment by axd1x8a** [comment]
Это уже есть в dev ветке для `MessageMin.answer()`

**Comment by TochnoNePercy** [comment]
Спасибо
