### ISSUE TITLE
Баг: 'User' object has no attribute 'request'

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#431]
**Опишите баг:** ...

**Ожидаемое поведение:** 
Отправка фото/аудио человеку

**Фактическое поведение:** 
`'User' object has no attribute 'request'`

**Ваш код (опционально)**: ...
```
async def test():
    im = Image.new('RGB', (200,200), color=('#FAACAC'))
    draw_text = ImageDraw.Draw(im)
    draw_text.text(
    (100,100),
    'Test Text',
    fill=('#1C0606')
    )
    file=BytesIO()
    im.save(file, format="jpeg")
    au=await audio.upload(title="***", file_source=file, peer_id=602577387)
    print('*****')
    print(await bot.api.messages.send(attachment=au, random_id=0, peer_id=602577387))
bot.loop_wrapper.on_startup.append(test())
```

**Заполните поля технической информации:**

---
vkbottle: 3.0 dev
vkbottle-types: 0.1.18
OS: Windows 7

---

**Comment by axd1x8a** [comment]
В аплоадер вы должны передать инстанс апи, а не фреймворка
