### ISSUE TITLE
Вопрос: работа мидлварей

### ISSUE THREAD

**Issue by Ne0shka** [vkbottle/vkbottle#435]
**Вопрос:** В каком порядке происходит мидлварей?

**Пример:**
Есть зарегистрированные мидлвари: `[register_mw, check_mv]`
Будут ли они работать в том же порядке, как зарегистрированы? Если нет - то почему?

**Ветка:** dev

**Comment by dhvcc** [comment]
Пометка на будущее - проблема была в использвании сета для регистрации. Изначально это делалось как доп проверка, но по итогу поломало некоторые вещи тк сет неупорядочен
