### ISSUE TITLE
Вопрос: python 3.6

### ISSUE THREAD

**Issue by dhvcc** [vkbottle/vkbottle#437]
**Вопрос:** Почему минимальная версия 3.7? По истории видно, что 3.7 стоит с появления файла `pyproject.toml`

Python 3.6 - самая популярная версия питона на данный момент, так что лучше бы поддерживать

**Comment by axd1x8a** [comment]
Поддержка python 3.7 и так накладывает некоторые ограничения, а с 3.6 их будет ещё больше.

**Comment by dhvcc** [comment]
> Поддержка python 3.7 и так накладывает некоторые ограничения, а с 3.6 их будет ещё больше. 

Почему тогда не релизнуть беккомпат версию на отдельной ветке с хотя бы текущим функционалом. Я не предлагаю тебе писать. Не очень хорошо, что ты физически не поставишь ботл на 3.6

**Comment by Olegt0rr** [comment]
@dhvcc, начиная с января 2022 года, даже если есть критическая ошибка безопасности, она не будет исправлена командой разработчиков Python. Если проекты живые - уже давно пора перетащить их на свежие версии.

**Comment by dhvcc** [comment]
> @dhvcc, начиная с января 2022 года, даже если есть критическая ошибка безопасности, она не будет исправлена командой разработчиков Python. Если проекты живые - уже давно пора перетащить их на свежие версии.

Ага, я к этому и создавал, после изначального анонса

**Comment by axd1x8a** [comment]
Так что в итоге? Я не считаю, что поддержка 3.6 нужна, но если делать, то придется решать проблемы с зависимостями, которые тоже не поддерживают эту версию

**Comment by Olegt0rr** [comment]
Она абсолютно не нужна. Всё, поддержка 3.6 официально закончилась у самого питона. Тащить его сюда смысла никакого не имеет.

**Comment by axd1x8a** [comment]
Значит закрываю

**Comment by dhvcc** [comment]
Не совсем понимаю токса в сторону 3.6. Неважно, поддерживается или нет. Люди юзают и это главное.

Хотя с другой стороны, видимо, никому уже не хочется в ботл что-то писать

**Comment by dhvcc** [comment]
Нет смысла тогда думать о фичах, если либа не поддерживает самую популярную версию питона + ей лень заниматься. Видимо, мнение разрабов эхо-ботов на 3.8 важнее

**Comment by axd1x8a** [comment]
Как минимум с зависимостями я ничего не могу сделать. Надо решать этот вопрос с @timoniq

**Comment by Olegt0rr** [comment]
@dhvcc, с чего ты привязался к "самой популярной версии"? У тебя ломаются какие-то любимые зависимости, тогда сходи к их разработчикам или отправь туда PR. Не понимаю проблему

**Comment by dhvcc** [comment]
Ну ведь вопросы нужно обсуждать и решать, а не формировать личное мнение и отталкиваться от него.
Какие проблемы с зависимостями? Давайте тот, кто знает, отпишет.

**Comment by dhvcc** [comment]
> @dhvcc, с чего ты привязался к "самой популярной версии"? У тебя ломаются какие-то любимые зависимости, тогда сходи к их разработчикам или отправь туда PR. Не понимаю проблему

Потому что это факт и это являет собой потенциальную часть разработчиков. Если ты пишешь либу для себя или для узкого круга лиц - ок.
Не понимаю с чего ты сделал вывод, что я пишу на 3.6 и у меня ломаются зависимости

**Comment by Olegt0rr** [comment]
Потому, что когда ты начинаешь новый проект, глупо брать устаревший питон.
Единственное, что может на это сподвигнуть - зависимости, которые не докатили до нужной версии.

**Comment by dhvcc** [comment]
Почему тут именно новый проект? Что если кто-то хочет мигрировать старый?
Если тебя не интересует питон 3.6 - не пиши сюда, это логично. Я не прошу делать это ни тебя, ни фека
Этот ишью являет собой обсуждение существующих преград поддержке 3.6, а не целесообразности его использования в _новых_ проектах. По-моему это должно быть ясно

**Comment by Olegt0rr** [comment]
Если кто-то хочет мигрировать существующий проект - ему всё равно придётся переписывать часть приложения (отличный момент, чтобы заодно обновить и python). 

Целесообразность расширения поддержки для **протухшей** версии python **неочевидна** в 2022 году

**Comment by dhvcc** [comment]
Твоя неприязнь к 3.6 - твоё дело. Писать эти сообщения ровно резать воду. Ты не можешь поменять факт использования определённой версии
Тем более ты ничего не добьешься рассматривая эдж кейсы в пользу своей теории
Пожалуйста, ещё раз перечитай моё предыдущее сообщение 👎

**Comment by axd1x8a** [comment]
Кто-то из чата всё-таки умудрился поставить ботл на 3.6
https://nekobin.com/tudedugoqo

Исправить это точно не получится, поэтому закрываю вопрос.
