### ISSUE TITLE
Вопрос: Как добавить карусель?

### ISSUE THREAD

**Issue by artush6** [vkbottle/vkbottle#449]
**Вопрос:** ...

Пытаюсь добавить различными способами карусель. Вот конечный, но выдающий ошибку
`    carousel = template_gen(
      TemplateElement(
        ["Title", "Description", "-109837093_457242809"],
        [Keyboard().add(Text("Example")).get_json()]
      )
    )`

Вот ошибка:   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vkbottle/tools/dev/template/element.py", line 17, in __init__
    assert buttons, "Buttons are required"
AssertionError: Buttons are required

как быть?

**Comment by axd1x8a** [comment]
Зачем вы передаёте лист?

**Comment by artush6** [comment]
Когда я передаю не лист, мне выдают ошибку, мол, list is requirement

**Comment by axd1x8a** [comment]
Покажите, что за ошибка

**Comment by artush6** [comment]
`vkbottle.exception_factory.code_exception.VKAPIError_911: Keyboard format is invalid: template['elements'][0]['buttons'][0] should be array`

**Comment by artush6** [comment]
@bot.on.private_message(text = "example")
  @bot.on.private_message(payload = {"cmd": "example"})
  async def top_songs_handler(message: Message):

    keyboard_1 = Keyboard().add(Text("button 1", {})).get_json()
    keyboard_2 = Keyboard().add(Text("button 2", {})).get_json()

    # More about combining fields can be read in vk documentation
    # for templates: https://vk.com/dev/bot_docs_templates
    template = template_gen(
        TemplateElement(
            photo_id="-109837093_457242809", buttons=keyboard_1, action={"type": "open_photo"}
        ),
        TemplateElement(
            photo_id="-109837093_457242809", buttons=keyboard_2, action={"type": "open_photo"}
        ),
    )

    await message.answer("Carousel", template=template)`

Вот весь код функции (клавиатуру и карусель пробовал вставлять вне функции, ошибка была та же). Модулей, не связанных с vkbottle не импортировал.
P.S. Код из документации даже ошибку выдает

**Comment by axd1x8a** [comment]
Обновитесь до 4.0.4, там должно работать

**Comment by artush6** [comment]
Да, заработало. Спасибо большое, очень выручили ;)
