### ISSUE TITLE
ImportError: cannot import name 'StatePeer' from 'vkbottle_types'

### ISSUE THREAD

**Issue by beliboba** [vkbottle/vkbottle#454]
ImportError: cannot import name 'StatePeer' from 'vkbottle_types' (C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle_types\__init__.py
)

**Comment by axd1x8a** [comment]
если у вас версия 4.x, то стейты импортируются из vkbottle, а если 3.х, то вам нужно обновиться до 3.0.3
