### ISSUE TITLE
Трудно читать документацию

### ISSUE THREAD

**Issue by Masynchin** [vkbottle/vkbottle#458]
**UPD: отправляйте свои изменения, улучшающие документацию, в #471 **

Очень трудно читать документацию из-за обилия непереведённых терминов.

**Пример из документации (раздел LoopWrapper):**
## interval
Легкий темплейт для создания тасков с бесконечно повторяющимися действиями в интервале. Пример:

...

**Пример перевода на русский:**
## interval (Повторяющиеся задачи)
Пример создания повторяющейся задачи с заданным интервалом:

---

По всей документации встречаются слова "темплейт", "экзамплы". Самый явный пример плохого использования англицизмов.

А вот пример перегрузки. Не ко всем можно подобрать русское слово, но бОльшую часть перевести можно.
![image](https://user-images.githubusercontent.com/47028153/148082813-61ad0ba3-99a7-4fcb-88f4-3a778d3b361c.png)

**Comment by axd1x8a** [comment]
Вы правы, это один из вопросов, который можно было бы сделать лучше. К сожалению, ресурсов мейнтейнеров и контрибьюторов не хватает, в том числе на решение проблемы, которую вы обозначили.
Если вы сами сможете исправить это - с нетерпением ждём вашего пулл реквеста.

**Comment by Masynchin** [comment]
@FeeeeK может снова открыть этот ишьюс? Хочу, чтобы она вела на мой ПР, в который будут добавляться улучшения документации
