### ISSUE TITLE
Не работает код из примера User LP

### ISSUE THREAD

**Issue by json1c** [vkbottle/vkbottle#46]
https://github.com/timoniq/vkbottle/blob/master/vkbottle/user.py

`Traceback (most recent call last):
  File "c:\Users\User\game_bot\test.py", line 1, in <module>
    from vkbottle.user import User
ModuleNotFoundError: No module named 'vkbottle.user'`

**Comment by timoniq** [comment]
Как устанавливали библиотеку?

**Comment by json1c** [comment]
> Как устанавливали библиотеку?

pip install vkbottle==1.35

**Comment by timoniq** [comment]
> pip install vkbottle==1.35

На версии 1.35 еще не доступен user longpoll, обновите библиотеку с помощью команды:
```sh
pip install vkbottle --upgrade
```
