### ISSUE TITLE
Вопрос: как получить id сообщения на которое ответил пользователь?

### ISSUE THREAD

**Issue by beliboba** [vkbottle/vkbottle#460]
как получить id сообщения на которое ответил пользователь?

**Comment by axd1x8a** [comment]
Вконтакте предоставляют [документацию](https://dev.vk.com/) ко всему апи, включая объект [сообщения](https://dev.vk.com/reference/objects/message).
Еще советую посмотреть список [рекомендованных IDE](https://vkbottle.readthedocs.io/ru/latest/tutorial/recommended_ide/), в которых есть подсказки для всего, что есть в vkbottle.
