### ISSUE TITLE
Поддерживаемая версия VK API

### ISSUE THREAD

**Issue by Olegt0rr** [vkbottle/vkbottle#462]
Добавьте в README поддерживаемую версию VK API, будет нагляднее для новичков

**Comment by axd1x8a** [comment]
Не вижу в этом никакого смысла

**Comment by Olegt0rr** [comment]
@FeeeeK,
А как понять какая версия VK API сейчас поддерживается?

**Comment by axd1x8a** [comment]
Последняя
