### ISSUE TITLE
Предложение: сделать объекты пользователей хешируемыми

### ISSUE THREAD

**Issue by Olegt0rr** [vkbottle/vkbottle#465]
## Описание функциональности
Было бы круто сделать объекты пользователей хешируемыми. 
Это поможет сравнивать их друг с другом и добавлять в сеты.

## Пример псевдокода

```python
class UsersUserMin(BaseModel):
    ...
    def __hash__(self):
        return hash(self.id)
```

```python
class Party:
    def __init__(self):
        self._users = set()

    def register(self, user: UsersUserMin):
        self._users.add(user)
        

party = Party()
party.register(UsersUserMin(id=1))
party.register(UsersUserMin(id=2))
```

**Comment by axd1x8a** [comment]
Так как объекты в vkbottle-types генерируются автоматически, к ним нельзя ничего добавлять.

**Comment by Olegt0rr** [comment]
Почему нельзя? Делаем изменённый в нужную сторону `pydantic.BaseModel` и наследуемся от него

**Comment by axd1x8a** [comment]
Не во всех объектах есть .id

**Comment by Olegt0rr** [comment]
Да, но можно проверять наличие id :)

**Comment by Olegt0rr** [comment]
А где можно посмотреть генератор?

**Comment by dhvcc** [comment]
> Да, но можно проверять наличие id :)

Если я правильно понимаю, то тогда что-то будет хешируемым, что-то нет. Почему это тогда на разработчика не оставить?
Идея здравая, но если это будет работать частично, то может только добавить проблем

**Comment by Olegt0rr** [comment]
@dhvcc ты не можешь оставить на разработчика то, что прилетает тебе из бутылки :) 
Патчинг моделей на лету я не рассматриваю, это дно)

Объекты без id тоже можно сделать хэшируемыми: либо через станадартные средства pydantic (frozen=True), либо через сумму полей

**Comment by dhvcc** [comment]
Тогда я думаю это больше ишью для репы тайпов. Можешь сделать минимальный ПР, что бы изначально посмотреть как это будет работать, а потом можно попробовать в кодген добавить

**Comment by axd1x8a** [comment]
Все ишью к типам нужно заводить здесь. А насчёт этой идеи, я не вижу необходимости в этом, если у него проблема с повторяющимися юзерами, то это нужно решать перед запросом, а не после.

**Comment by Olegt0rr** [comment]
Вопрос не в одном повторении, а в использовании всех возможностей и преимуществ `set()`, которые сейчас заблокированы по непонятной причине ("нет необходимости" за причину не считается)

**Comment by axd1x8a** [comment]
Считается

**Comment by timoniq** [comment]
это будет полезно. такое уже делали когда-то (#145), можно это легко кодгенить: использовать поля `r"\bid\b"` для хеширования

**Comment by axd1x8a** [comment]
:sob:

**Comment by axd1x8a** [comment]
Ладно

**Comment by dhvcc** [comment]
@FeeeeK тебе не обязательно что-то делать. ПР поднимет он, а нюансы обсудим тут. А тебе или Арсению на мердж нажать

**Comment by axd1x8a** [comment]
Есть вариант указать `frozen = True` для всех моделей, но тогда это сделает их неизменяемыми. @Olegt0rr, этот вариант вас устраивает?

**Comment by Olegt0rr** [comment]
Да. А зачем прилетающая извне модель должна быть изменяемой?

**Comment by axd1x8a** [comment]
Все датаклассы эвентов останутся изменяемыми, чтобы с ними можно было работать в мидлварях.

**Comment by Olegt0rr** [comment]
Тогда проблема решается так: https://github.com/vkbottle/vkbottle/issues/465#issuecomment-1010715527

**Comment by Olegt0rr** [comment]
Не очень понял как указанный коммит решает проблему :(

**Comment by axd1x8a** [comment]
Там используется новая версия типов
