### ISSUE TITLE
Баг: у метода `message.answer` параметр `peer_ids` не работает ни при каких условиях

### ISSUE THREAD

**Issue by Olegt0rr** [vkbottle/vkbottle#468]
**Опишите баг:**
У метода `message.answer()` есть параметр `peer_ids`, который не работает.
При этом рядом лежит параметр `user_ids`, который работает корректно.

**Ожидаемое поведение:** 
1. Передаю в message.answer() параметр `peer_ids`
2. Сообщение доставлено каждому peer.

**Фактическое поведение:**
1. Сообщение доставлено только в чат, в который было отправлено.

**Заполните поля технической информации:**
vkbottle==4.1.11

**Comment by Bundaev** [comment]
bot.api.messages.send(peer_ids=peer_ids ,message='message', random_id=0)

**Comment by Olegt0rr** [comment]
Спасибо, этот workaround понятен :)
