### ISSUE TITLE
Проблема при установке vkbottle - Build Tools for Visual Studio

### ISSUE THREAD

**Issue by json1c** [vkbottle/vkbottle#47]
.

**Comment by timoniq** [comment]
### Для работы vkbottle рекомендуется python версии 3.7
### Build tools можно скачать по этой ссылке: 
https://go.microsoft.com/fwlink/?LinkId=691126

**Comment by sergeyfilippov1** [comment]
1. 3.8.1
2.  ошибка
3. Windows 7 Ultimate

Loguru я устанавливал до установки фреймворка, он нормально установился

**Comment by timoniq** [comment]
Загрузите полный лог установки на https://pastebin.com и пришлите сюда ссылку. Одной лишь ошибкой невозможно руководствоваться, нужно понять при установке чего конкретно появляется ошибка

**Comment by sergeyfilippov1** [comment]
https://pastebin.com/9LzE12U8

**Comment by timoniq** [comment]
Решения вашей проблемы:

Обновите установщик pip и `setuptools`:  
```sh
python -m pip install --upgrade pip
pip install --upgrade setuptools
```
Установка `Build tools`: [установить здесь](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16)
Использовать `--only-binary :all:` при установке пакета

https://stackoverflow.com/questions/47253638/error-microsoft-visual-c-14-0-is-required-when-installing-python-package

**Comment by sergeyfilippov1** [comment]
$ pip install -U --only-binary :all: vkbottle
Requirement already up-to-date: vkbottle in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (1.35)

Не обновляется до новой версии

**Comment by timoniq** [comment]
А для кого есть pip uninstall?

**Comment by sergeyfilippov1** [comment]
```$ pip install -U --only-binary :all: vkbottle
ERROR: Could not find a version that satisfies the requirement vkbottle (from versions: none)
ERROR: No matching distribution found for vkbottle```

**Comment by timoniq** [comment]
> https://stackoverflow.com/questions/47253638/error-microsoft-visual-c-14-0-is-required-when-installing-python-package

Я добавил ссылку, если следовать инструкции, то все установится
