### ISSUE TITLE
Вопрос: OnMessage ивент на сообщения сообщества

### ISSUE THREAD

**Issue by capsey** [vkbottle/vkbottle#477]
**Вопрос:** Есть ли возможностью иметь ивент на подобии `@bot.on.message`, который вызывается при новом сообщении от сообщества в личном чате?

`@bot.on.message` вызывается только при новом сообщения от всех, кроме самого сообщества (что имеет смысл), однако мне нужно также обрабатывать и сообщения от сообщества тоже, чтобы администраторы, пишущие от лица сообщества в личном чате также могли использовать команды бота. Каким образом это можно сделать?

**Comment by deknowny** [comment]
На моей памяти, событие сообщения от самого сообщества называется `message_reply`. Можно обработать событие в сыром виде.

Однако добавить флаг на поддержку этого события под интерфейс `on.message` имеет смысл.

**Comment by axd1x8a** [comment]
Так и есть, приходит отдельный евент `message_reply`, но его поддержки в `.message()` не будет, тк это для этого используется другое view. Если он вам нужен, то используйте `raw_event()`
