### ISSUE TITLE
Бот виснет после ошибки ServerDisconnectedError

### ISSUE THREAD

**Issue by alekssamos** [vkbottle/vkbottle#486]
Отправляю или редактирую сообщение, иногда получаю такую ошибку:
`<class 'vkbottle.exception_factory.code_exception.VKAPIError_9'> Flood control: too much messages sent to user.`
try catch не помогают. Обновил до последней версии, проблема осталась.

**Comment by axd1x8a** [comment]
Покажите код

**Comment by alekssamos** [comment]
```python3
async def messages_edit(api, *args, **kwargs):
    async def _():
        return await api.messages.edit(*args, **kwargs)
    try:
        result = await _()
    except VKAPIError[9] as e:
        logger.info("flood control, waiting...")
        await asyncio.sleep(30)
        logger.info("repeat...")
        await _()
    return result


```
Ну например так.
Или просто обычный:
```
try: await api.messages.edit(...)
catch: # ...
```
И всё равно программа останавливается.

**Comment by mironovmeow** [comment]
В vkbottle есть ErrorHandler, которые позволяет отлавливать ошибки.

https://github.com/vkbottle/vkbottle/blob/master/docs/low-level/exception_handling/error-handler.md

Так же его можно передать при инициализации бота.

bot = Bot(error_handler=...)

**Comment by alekssamos** [comment]
Я пробовал, тогда он поработает две минуты и отключается от LP сервера, точнее если ошибка соединения, он не восстанавливается, а вылетает.

**Comment by mironovmeow** [comment]
Ошибка с longpool? А можно показать какая конкретно ошибка?

**Comment by alekssamos** [comment]
`aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected`
После этого зависает и больше ничего не делает.

**Comment by mironovmeow** [comment]
Вспомнил. Иногда longpool может барахлить и бросает ошибку. Я её просто [игнорирую](https://github.com/mironovmeow/MeowSchool/blob/8c7ab0632f9e3856caad6f3c5ba1a3ca9c9b5805/vk_bot/error_handler.py#L157) (ClientError из aiohttp). Сам не понимаю почему, но работает.

**Comment by alekssamos** [comment]
Ну я так и не понял почему появляется проблема которую я описал в первом сообщении. Сделайте чтобы она перехватывалась нормально и всё. И как правильно тогда написать обработчик ошибок чтобы он подобную ошибку не выдавал и соединение восстанавливал при разрыве?

**Comment by mironovmeow** [comment]
> Ну я так и не понял почему появляется проблема которую я описал в первом сообщении.

Это vk возвращает ошибку от какого-то метода, который вызывается часто.

> И как правильно тогда написать обработчик ошибок чтобы он подобную ошибку не выдавал и соединение восстанавливал при разрыве?

В ссылке выше я реализовал разные обработчики для разных хендлеров, обернув их `@error_handler.catch`. Почему соединение обрывает я не знаю. Сталкивался пару раз и моё решение выше мне помогло.

P.s. Через [vk](https://vk.com/mironovmeow) я могу помочь быстрее.

**Comment by axd1x8a** [comment]
Соединение разрывается из-за проблем у вк, позже реализую переподключение. Первый пример кода у меня работает, но вам лучше использовать респонс валидатор для этого.

**Comment by alekssamos** [comment]
> Соединение разрывается из-за проблем у вк

Но когда `ErrorHandler` в **моей** функции нет, ошибки переподключения тоже **нет**, хотя и допускаю, что это чисто совпадение.
