### ISSUE TITLE
Вопрос: Поддержка FSM

### ISSUE THREAD

**Issue by iQiexie** [vkbottle/vkbottle#489]
Существует ли в vkbottle поддержка FSM, как в [vk_wave](https://fscdev.github.io/vkwave/ru/bots/fsm/)?

Я видел [этот же самый вопрос](https://github.com/vkbottle/vkbottle/issues/113), но ответ на него уже неактуален, т.к бранчи выпилили, как я понял

**Comment by axd1x8a** [comment]
Да, есть. Вместо бранчей теперь стейты, подробнее о них вы можете узнать в [документации](https://vkbottle.readthedocs.io/)
