### ISSUE TITLE
Баг: ошибка при нажатии на не-инлайн callback кнопку

### ISSUE THREAD

**Issue by arseny2606** [vkbottle/vkbottle#498]
**Опишите баг:** при нажатии на не-инлайн callback кнопку ВКонтакте не присылает conversation_message_id, хотя в модуле types в объекте события параметр не отмечен как Optional. В репозитории vkbottle-types создан [пулл-реквест с исправлением](https://github.com/vkbottle/types/pull/37).

**Ожидаемое поведение:** событие message_event правильно обрабатывается, ошибки валидации pydantic не возникает

**Фактическое поведение:** возникает ошибка валидации pydantic из-за отсутствия параметра conversation_message_id

**Заполните поля технической информации:**

---
vkbottle: 4.2.2
vkbottle-types: 5.131.146.1
OS: Windows 10

---

**Comment by markelovstyle** [comment]
Можно пример такого события, где отсутствует `conversation_message_id`?

**Comment by arseny2606** [comment]
```{'group_id': ..., 'type': 'message_event', 'event_id': '5fff6d1f8a832a19ea8e4b717a139f32dd80ac99', 'v': '5.131', 'object': {'user_id': ..., 'peer_id': ..., 'event_id': 'a63ab5923e8c', 'payload': {'command': 'show_product', 'product_id': 2}}}```


Подобное событие приходит при нажатии на Callback кнопку в клавиатуре, у которой `inline=False`.

**Comment by axd1x8a** [comment]
От пр в типах нет никакого смысла, изменения удалит кодген, откройте ишью в схеме вк.

**Comment by axd1x8a** [comment]
https://github.com/VKCOM/vk-api-schema

**Comment by arseny2606** [comment]
Или я и мои коллеги слепые, или в схеме нет описания объектов longpoll api...

**Comment by arseny2606** [comment]
Или мы слепые (что возможно), или в схеме нет описания объекта события message_event...

**Comment by axd1x8a** [comment]
Да, моя ошибка. Обновите типы с мастер ветки или дождитесь релиза на pypi.
