### ISSUE TITLE
Вопрос: как сделать хендлеры по тексту регистронезависимыми?

### ISSUE THREAD

**Issue by Futyn-Maker** [vkbottle/vkbottle#500]
Здравствуйте! Большое спасибо за удобную библиотеку! Я новичок во всём, что касается асинхронного программирования и хендлеров, поэтому заранее прошу прощение, если вопрос покажется элементарным.

**Вопрос:** как сделать так, чтобы сообщения обрабатывались независимо от регистра?
```Python3
@bot.on.message(text="привет")
...
```
Это будет работать для "привет", но не будет --- для "Привет". Можно, конечно, написать `text=['привет', 'Привет']`, но это кажется не очень Pythonic.

Есть ли простой способ справиться с этим, не заставляя движок обрабатывать каждое сообщение и приводить текст к нижнему регистру?

**Comment by timoniq** [comment]
https://github.com/vkbottle/vkbottle/blob/9c029f449f0ffa41da1ec6e72b7a42fedea3813d/examples/high-level/labeler_setup.py#L31

**Comment by Futyn-Maker** [comment]
Спасибо! Кажется, то, что нужно. :-)
