### ISSUE TITLE
Баг: на сайте документации сломанная ссылка

### ISSUE THREAD

**Issue by beliboba** [vkbottle/vkbottle#503]
https://vkbottle.readthedocs.io/ru/latest/tutorial/first-bot/#_1
Если кликнуть по ссылке token-generator, попадаем на неисправную страницу https://vkbottle.readthedocs.io/docs/low-level/api/token-generator.md
![image](https://user-images.githubusercontent.com/73661136/166435695-7aec7cd5-29b1-41d7-aa42-5e9fd2262bcd.png)

**Comment by axd1x8a** [comment]
Исправлено.
