### ISSUE TITLE
Баг: Циклически вызывается ErrorHandler при использовании функции task.cancel()

### ISSUE THREAD

**Issue by Zensonaton** [vkbottle/vkbottle#504]
**Опишите баг:** При создании User-polling'а в функции `asyncio.create_task(...)`, и далее при дальнейшем использовании `task.cancel()` внутри Error Handler'а вызывает цикличный вызов Error Handler'а.

**Контекст**: Я пытаюсь объеденить vkbottle и другую библиотеку, в которых тоже используется Polling, (aiogram) и именно поэтому мне необходимо запускать `User.run_polling()` как отдельный asyncio'шный Task. Я хочу, что бы при отзыве сессии (токена) со стороны ВК пользователем мой код писал специальную ошибку в консоль, а после останавливал Polling-task.

**Ожидаемое поведение:** Бот **не** должен циклично вызывать Error Handler.

**Фактическое поведение:** Бот циклично **вызывает** Error Handler.

**Ваш код**:
[Pastebin](https://pastebin.com/ztcMyfHq), 
<details>
  <summary>Код в спойлере:</summary>
  
  ```python
# coding: utf-8

import vkbottle
from vkbottle import VKAPIError
import asyncio

# Токен пользователя, его можно получить, например, тут: 
# https://oauth.vk.com/oauth/authorize?client_id=6463690&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token&revoke=1
TOKEN = "USERTOKEN"

async def main():
    vkUser = vkbottle.User(TOKEN)
    LPTask: asyncio.Task


    # Для теста создаю Handler для получения всех сообщений:
    @vkUser.on.private_message()
    async def pmHandler(msg):
        print("Новое сообщение!")

    # А теперь то, где, вероятнее всего, и затаился
    # баг vkbottle: Эта функция вызывается циклически
    # из за ошибки `asyncio.exceptions.CancelledError`.
    #
    # Всё, что я хочу, так это остановить задачу (Task)
    # с помощью метода task.cancel(), в случае, если
    # пользователь завершает сессию в настройках
    # безопасности ВК.
    @vkUser.error_handler.register_error_handler(VKAPIError[5])
    async def errorHandler(e: VKAPIError):
        LPTask.cancel()

    # Создаём Task с Polling'ом:
    LPTask = asyncio.create_task(
        vkUser.run_polling()
    )


if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    
    loop.create_task(main())
    loop.run_forever()
  ```
  
</details>

<br>

**Техническая информация:**

---

**vkbottle**: `4.2.2`,
**vkbottle-types**: `5.131.146.1`,
**OS**: `Manjaro Linux`,
**Python**: `3.10.4`

---

**Comment by axd1x8a** [comment]
Просто игнорируйте эту ошибку. Для этого сделайте для нее хендлер, который ничего не делает.

**Comment by Zensonaton** [comment]
> Просто игнорируйте эту ошибку. Для этого сделайте для нее хендлер, который ничего не делает.

Создал ещё один Error Handler, 
```python
@vkUser.error_handler.register_error_handler(asyncio.CancelledError)
async def _errorHandler(e: asyncio.CancelledError):
	pass
```
теперь ошибок в консоли не появляется, однако, Error Handler всё равно продолжает циклически перезапускаться.

**Comment by Zensonaton** [comment]
Как бы я не старался, вызов `task.cancel()`, по какой то причине, повторно вызывает ту же ошибку, которую 'ждёт' Error Handler, из за чего бот бесконечно вызывает Handler, внутри `task.cancel()`, а оно снова Handler, ...

Сейчас даже пытался переменные добавлять:
```python
if isCancelled:
    return

isCancelled = True
task.cancel()
```
пытался делать ещё один Wrapper:
```python
async def pollingTask(vkUser):
    try:
        await vkUser.run_polling()
    except Exception as error:
        print(error)
```
и результаты такие же; vkbottle всё ещё циклится в Error Handler'е.

**Comment by axd1x8a** [comment]
Попробуйте сделать свой обработчик ошибок и поставить его в качестве основного в ините бота.

**Comment by Zensonaton** [comment]
> Попробуйте сделать свой обработчик ошибок и поставить его в качестве основного в ините бота.

Прошу прощения, не могли бы Вы показать как это сделать? 👀

**Comment by Zensonaton** [comment]
Решил изучить сущность бага, изучая [error_handler.py](https://github.com/vkbottle/vkbottle/blob/master/vkbottle/exception_factory/error_handler/error_handler.py#L37-L48), и я заметил что вместо ошибки `asyncio.CancelledError` вызывается другая ошибка, `Authorization failed`, которая вызывается снова и снова при отзыве сессии, поэтому вариант с `if (error == CancelledError) => return` не прокатит. Именно по этой же причине, код, который я [отправлял выше](https://github.com/vkbottle/vkbottle/issues/504#issuecomment-1116345073) с "пустым" ErrorHandler'ом бесполезен, так как он **не** ловит `CancelledError` ошибку.

**Comment by axd1x8a** [comment]
те, это не проблема ботла?

**Comment by Zensonaton** [comment]
> те, это не проблема ботла?

Нет, это именно баг vkbottle, так как такой же баг происходит и при коде [в самом первом посту](https://github.com/vkbottle/vkbottle/issues/504#issue-1224308486).

**Comment by axd1x8a** [comment]
А, я понимаю что происходит. Этот запрос не обернут в хендлер ошибок и поэтому ничего не работает.
![image](https://user-images.githubusercontent.com/26704473/166957706-0d14643a-e458-4db5-bd17-50d94c580fc5.png)

**Comment by Zensonaton** [comment]
> А, я понимаю что происходит. Этот запрос не обернут в хендлер ошибок и поэтому ничего не работает. ![image](https://user-images.githubusercontent.com/26704473/166957706-0d14643a-e458-4db5-bd17-50d94c580fc5.png)

Хорошо, как можно самому сделать патч? Сам попытался через `try-catch`, не вышло :D

**Comment by axd1x8a** [comment]
Да я что-то тоже не понимаю, у меня просто не отменяется таск...

**Comment by axd1x8a** [comment]
И так, из моих наблюдений: 

1. Отменить таск лп нельзя, пока не знаю почему
2. ЛП продолжает работать после прерывания сессии, поэтому можно спокойно обрабатывать сообщения с помощью raw_event

**Comment by Zensonaton** [comment]
> 1. Отменить таск лп нельзя, пока не знаю почему

Единственное, что я сам мог выяснить так это то что вызывается ошибка о невалидной сессии, и вызывается она снова и снова. Чувство такое, что где-то сидит `try-catch` блок, который ловит ошибку `asyncio.CancelledError`, (которая вызывается, судя по всему, при `task.cancel()`) и вместо того, что бы ошибку о отмене Task'а обработать, оно вызывает ошибку о невалидной сессии. То есть, псевдокод такой:
```python
...
try:
    with longpoll.listen():
        ...
catch Exception as error:
    raise VKApiError[...]
```

> 2. ЛП продолжает работать после прерывания сессии, поэтому можно спокойно обрабатывать сообщения с помощью raw_event

Тоже заметил. Это ли не баг самого ВК случаем? :eyes:

**Comment by axd1x8a** [comment]
```python
  import vkbottle
  from vkbottle import VKAPIError
  import asyncio
  
  # Токен пользователя, его можно получить, например, тут:
  # https://oauth.vk.com/oauth/authorize?client_id=6463690&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token&revoke=1
  TOKEN = ""
  
  
  bot = vkbottle.User(TOKEN)
  
  
  # Для теста создаю Handler для получения всех сообщений:
  @bot.on.private_message()
  async def pm_handler(msg):
      print("Новое сообщение!")
  
  
  # А теперь то, где, вероятнее всего, и затаился
  # баг vkbottle: Эта функция вызывается циклически
  # из за ошибки `asyncio.exceptions.CancelledError`.
  #
  # Всё, что я хочу, так это остановить задачу (Task)
  # с помощью метода task.cancel(), в случае, если
  # пользователь завершает сессию в настройках
  # безопасности ВК.
  @bot.error_handler.register_error_handler(VKAPIError[5])
  async def errorHandler(e: VKAPIError):
      lp_task.cancel()
  
  
  # Создаём Task с Polling'ом:
  loop = asyncio.get_event_loop()
  lp_task = loop.create_task(bot.run_polling())
  loop.run_forever()
  ```
  У меня ваш код работал не совсем правильно, поэтому пришлось чуть-чуть его изменить.
  Как мне кажется, ошибка связанна с asyncio и мы оба что-то делаем не так.

**Comment by Zensonaton** [comment]
> У меня ваш код работал не совсем правильно, поэтому пришлось чуть-чуть его изменить. Как мне кажется, ошибка связанна с asyncio и мы оба что-то делаем не так.

Такой вариант кода работает? `task.cancel()` работает нормально?
Интересно будет разобраться в чём беда, и можно ли это пофиксить на стороне vkbottle :eyes:

**Comment by axd1x8a** [comment]
В ботле есть кое-что на этот случай, вместо отмены таска можно просто сделать `user.polling.stop = True`

**Comment by axd1x8a** [comment]
> > У меня ваш код работал не совсем правильно, поэтому пришлось чуть-чуть его изменить. Как мне кажется, ошибка связанна с asyncio и мы оба что-то делаем не так.
> 
> Такой вариант кода работает? `task.cancel()` работает нормально? Интересно будет разобраться в чём беда, и можно ли это пофиксить на стороне vkbottle 👀

Скорее всего проблема в хендлере ошибок и в том, что он ловит `BaseException`, а не `Exception`

**Comment by axd1x8a** [comment]
Да, так и есть.

**Comment by Zensonaton** [comment]
> В ботле есть кое-что на этот случай, вместо отмены таска можно просто сделать `user.polling.stop = True`

Этот вариант подошёл, он не такой, к сожалению, элегантный как `task.cancel()`, но он работает!

> Да, так и есть, Скорее всего проблема в хендлере ошибок и в том, что он ловит `BaseException`, а не `Exception`

Замечательно, значит, скоро будет фикс со стороны vkbottle? :+1:

**Comment by axd1x8a** [comment]
Исправлено в cddd772
