### ISSUE TITLE
Как изменить сообщение, на котором была нажата кнопка?

### ISSUE THREAD

**Issue by neJok** [vkbottle/vkbottle#508]
![image](https://user-images.githubusercontent.com/84874782/167940841-392daa1e-8824-4476-b043-5f77b6ba87b9.png)

Я написал такой код. Не знаю как через vkbottle получить текст сообщения, по этому сделал  get запрос, но он возвращает не то сообщение, на котором нажата кнопка, а другое. При попытке изменения сообщения мне выдает ошибку о том, что у бота нету доступа.

Как можно переписать код, чтобы он работал?

**Comment by axd1x8a** [comment]
Можете скинуть ссылку на вашего бота?

**Comment by neJok** [comment]
> Можете скинуть ссылку на вашего бота?

Бот реагирует на кнопки в беседе, так что нету смысла

**Comment by axd1x8a** [comment]
Советую сейчас же убрать из кода eval и requests.
И ознакомиться с [документацией](https://vkbottle.readthedocs.io/)

**Comment by neJok** [comment]
> Советую сейчас же убрать из кода eval и requests. И ознакомиться с [документацией](https://vkbottle.readthedocs.io/)

Её очень сложно читать, не могли бы Вы объяснить на что нужно изменить?

**Comment by axd1x8a** [comment]
Вам придется переписывать весь код, поэтому лучше прочтите и постарайтесь понять документацию.

**Comment by KurimuzonAkuma** [comment]
> > Советую сейчас же убрать из кода eval и requests. И ознакомиться с [документацией](https://vkbottle.readthedocs.io/)
> 
> Её очень сложно читать, не могли бы Вы объяснить на что нужно изменить?

Не сказал бы, что сложно... Хотя бы на json.loads

**Comment by neJok** [comment]
> > > Советую сейчас же убрать из кода eval и requests. И ознакомиться с [документацией](https://vkbottle.readthedocs.io/)
> > 
> > 
> > Её очень сложно читать, не могли бы Вы объяснить на что нужно изменить?
> 
> Не сказал бы, что сложно... Хотя бы на json.loads

Хорошо, как я понял запросы можно делать через https://vkbottle.readthedocs.io/ru/latest/low-level/http/http-client ? Но это не решает мою проблему. В документации нету никаких функций api, какие аргументы они принимают и тд. Или я что-то не понимаю...

**Comment by axd1x8a** [comment]
https://dev.vk.com/method

**Comment by neJok** [comment]
> https://dev.vk.com/method

Да, но метод который мне нужен не работает в vkbottle. Я уже описал проблему в самом первом сообщении. У меня есть код на vk_api, который прекрасно работает, но на vk_bottle выдаются ошибки или некоторых методов вообще нету...

**Comment by KurimuzonAkuma** [comment]
> > https://dev.vk.com/method
> 
> Да, но метод который мне нужен не работает в vkbottle. Я уже описал проблему в самом первом сообщении. У меня есть код на vk_api, который прекрасно работает, но на vk_bottle выдаются ошибки или некоторых методов вообще нету...

Все открытые методы есть в vkbottle, скрытые ты можешь выполнить через апи реквест, который также есть в боттле

**Comment by neJok** [comment]
> > > https://dev.vk.com/method
> > 
> > 
> > Да, но метод который мне нужен не работает в vkbottle. Я уже описал проблему в самом первом сообщении. У меня есть код на vk_api, который прекрасно работает, но на vk_bottle выдаются ошибки или некоторых методов вообще нету...
> 
> Все открытые методы есть в vkbottle, скрытые ты можешь выполнить через апи реквест, который также есть в боттле

То есть bot.api?
Или из vkbottle.api?

**Comment by neJok** [comment]
> > > > https://dev.vk.com/method
> > > 
> > > 
> > > Да, но метод который мне нужен не работает в vkbottle. Я уже описал проблему в самом первом сообщении. У меня есть код на vk_api, который прекрасно работает, но на vk_bottle выдаются ошибки или некоторых методов вообще нету...
> > 
> > 
> > Все открытые методы есть в vkbottle, скрытые ты можешь выполнить через апи реквест, который также есть в боттле
> 
> То есть bot.api? Или из vkbottle.api?

**Comment by axd1x8a** [comment]
https://vkbottle.readthedocs.io/ru/latest/ ещё раз попрошу ознакомиться с документацией. Там есть ответы на все ваши вопросы

**Comment by neJok** [comment]
> https://vkbottle.readthedocs.io/ru/latest/ ещё раз попрошу ознакомиться с документацией. Там есть ответы на все ваши вопросы

По вашей логике, вместо вопросов, можно просто оставить ссылку на документацию, раз мне уже 3 раз присылают ссылку на неё...

**Comment by axd1x8a** [comment]
Третий раз присылают, а вы все не можете ее прочесть.

**Comment by neJok** [comment]
> Третий раз присылают, а вы все не можете ее прочесть.

Хорошо, видимо я не умею читать, писать код. Больше не буду вас беспокоить.

**Comment by ghost** [comment]
> > Третий раз присылают, а вы все не можете ее прочесть.
> 
> 
> 
> Хорошо, видимо я не умею читать, писать код. Больше не буду вас беспокоить.

До вас дошло, это хорошо
