### ISSUE TITLE
Не работает импорт из документации

### ISSUE THREAD

**Issue by m1naj** [vkbottle/vkbottle#509]
![cmd_cURdsoc1Wk](https://user-images.githubusercontent.com/78999294/168117859-9237499d-862b-4c2c-80da-5d038d831caf.png)
![opera_nw8V3mtVcF](https://user-images.githubusercontent.com/78999294/168117986-d5773bef-1095-4c6f-849e-0a3b16f6f117.png)

**Comment by mironovmeow** [comment]
Откуда скачивали vkbottle (git / pip) и какой версии?

**Comment by m1naj** [comment]
pip, 3.1

**Comment by mironovmeow** [comment]
В 3.1 этого функционала нет. Он появился в 4.0.

upd: Можно воспользоваться обычными сырыми событиями. Они, насколько мне известно, не изменились с 3 версии.
