### ISSUE TITLE
bot.on.chat_message.regex отсутствует

### ISSUE THREAD

**Issue by DarklyZ** [vkbottle/vkbottle#51]
Почему `bot.on.chat_message.regex` удалён из хэндлеров?

**Comment by markelovstyle** [comment]
Вместо `regex` есть Rules и VBML. Поэтому он тут лишний

**Comment by axd1x8a** [comment]
рулзы

**Comment by DarklyZ** [comment]
Так как я правила для `regex`'ов не наблюдаю, придётся писать либо своё правило, либо в `VBMLRule` посылать `Pattern`'ы, настроенные как `regex`'ы, а это, я считаю, куда неудобнее, чем было до этого

**Comment by DarklyZ** [comment]
Решил проблему локально, закрываю вопрос.
