### ISSUE TITLE
Вопрос: Как отловить событие при редактировании сообщения?

### ISSUE THREAD

**Issue by Zensonaton** [vkbottle/vkbottle#514]
**Вопрос**: Как именно можно отловить событие при редактировании сообщения? Событие нужно отловить именно у пользователя, а не бота. В примерах кода нашёл примерно следующее:
https://github.com/vkbottle/vkbottle/blob/16f4cbd9b6603e58e9d82083fa452ffe2e7fbd93/examples/high-level/message_event.py#L37-L41
Решил применить это у себя:
```python
@vkUser.on.raw_event(str(vkbottle.UserEventType.MESSAGE_EDIT), dict)
async def edit(a):
    print("Edited!")
```
и код не работает. IDE ругался на то что `...UserEventType.MESSAGE_EDIT` это `int` а не `str`, а так же я не нашёл в vkbottle подходящий dataclass, поэтому я использовал dict. В чём беда? :thinking:

**Comment by axd1x8a** [comment]
Беда в том, что .on это проперти, у которого в типе указан ABCLabeler, а он писался для бота.
![image](https://user-images.githubusercontent.com/26704473/170828350-6bc030a6-dcec-4ddd-9990-d188bde13747.png)
Вы все сделали правильно, но датакласс можно не указывать, тогда в event.object будет сырой лист

**Comment by Zensonaton** [comment]
Попробовал, и следующий код тоже не работает, ничего не появляется в консоли при редактировании сообщения:
```python
@vkUser.on.raw_event(str(vkbottle.UserEventType.MESSAGE_EDIT)) # type: ignore
async def edit(a):
    print("Edited!")
```

**Comment by axd1x8a** [comment]
зачем str

**Comment by Zensonaton** [comment]
Потому что IDE говорит о том, что "тип int не может быть присвоен типу str"

**Comment by axd1x8a** [comment]
Просто игнорируйте это.
https://github.com/vkbottle/vkbottle/issues/514#issuecomment-1140268809
