### ISSUE TITLE
Баг: Если на стене есть запись с видео, то при запросе api.wall.get возникает exception=ValidationError

### ISSUE THREAD

**Issue by TheRealMaN** [vkbottle/vkbottle#519]
**Опишите баг:**
exception=ValidationError(model='GetResponse', errors=[{'loc': ('response', 'items', 2, 'attachments', 0, 'video', 'type'), 'msg': "value is not a valid enumeration member; permitted: 'video', 'music_video', 'movie'", 'type': 'type_error.enum', 'ctx': {'enum_values': [<VideoVideoType.VIDEO: 'video'>, <VideoVideoType.MUSIC_VIDEO: 'music_video'>, <VideoVideoType.MOVIE: 'movie'>]}}])>

posts = await api.wall.get(domain=site.vkGroupName, count=site.vkCount)
  File "/.venv/lib/python3.10/site-packages/vkbottle_types/codegen/methods/wall.py", line 296, in get
    return model(**response).response
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GetResponse
response -> items -> 2 -> attachments -> 0 -> video -> type
  value is not a valid enumeration member; permitted: 'video', 'music_video', 'movie' (type=type_error.enum; enum_values=[<VideoVideoType.VIDEO: 'video'>, <VideoVideoType.MUSIC_VIDEO: 'music_video'>, <VideoVideoType.MOVIE: 'movie'>])

**Comment by axd1x8a** [comment]
Что пришло в ответе сервера?

**Comment by TheRealMaN** [comment]
{
    "response": {
        "count": 21590,
        "items": [
            {
                "id": 937955,
                "from_id": -23509252,
                "owner_id": -23509252,
                "date": 1654096098,
                "type": "post",
                "marked_as_ads": 0,
                "is_favorite": false,
                "post_type": "post",
                "text": "",
                "attachments": [
                    {
                        "type": "video",
                        "video": {
                            "can_comment": 1,
                            "can_like": 1,
                            "can_repost": 1,
                            "can_subscribe": 1,
                            "can_add_to_faves": 1,
                            "can_add": 0,
                            "comments": 16,
                            "date": 1654096098,
                            "description": "Jgbcfybt",
                            "duration": 24,
                            "image": [
                                {
                                    "url": "https://sun4.userapi.com/sun4-15/s/v1/if2/V7lgDhvDIV38vXz-bddjmCL2z9um5-Z_FDUXwuJoKdNe2Z6VZ6fl_wQJnjPEML7p0E1AGC-ciM_BufpLXhpn7k44.jpg?size=130x96&quality=96&keep_aspect_ratio=1&background=000000&type=video_thumb",
                                    "width": 130,
                                    "height": 96,
                                    "with_padding": 1
                                },
                                {
                                    "url": "https://sun4.userapi.com/sun4-15/s/v1/if2/Do_83dEo9GfjUPQAI8TbugNp6S0ynseQ8jI47VRwq_5WZQ78nvLJ-pPprGT7F6CdEiLUzSxD48LWFJbI6c5PAjfr.jpg?size=160x120&quality=96&keep_aspect_ratio=1&background=000000&type=video_thumb",
                                    "width": 160,
                                    "height": 120,
                                    "with_padding": 1
                                },
                                {
                                    "url": "https://sun4.userapi.com/sun4-15/s/v1/if2/aJGb0RwnklILgP0MrGvcVCHRenPPTosmxu_HsPlW8RKHj3rikpNQ6VS_PhRWc-ajbTfQSPwtX5dS2KGCC_uBLTcB.jpg?size=320x240&quality=96&keep_aspect_ratio=1&background=000000&type=video_thumb",
                                    "width": 320,
                                    "height": 240,
                                    "with_padding": 1
                                },
                                {
                                    "url": "https://sun4.userapi.com/sun4-15/s/v1/if2/NPpogBQofkcRGPoEjkaAW3sm9tQuPI00iZWWHjDKMjXdsBLS_M1QUTT6RnxLXLSlzi03f1uZRj-jNohBULG-2T0p.jpg?size=800x450&quality=96&keep_aspect_ratio=1&background=000000&type=video_thumb",
                                    "width": 800,
                                    "height": 450,
                                    "with_padding": 1
                                },
                                {
                                    "url": "https://sun4.userapi.com/sun4-15/s/v1/if2/TMVcm-ATGXbFh03_TAIgQsJ7YN7w9pej2FWapjAZh8FUFSsQ5-IEKNyRykvJCRlXHDdDhWrnZWYQ4n1YdqBSyBjI.jpg?size=405x720&quality=96&type=video_thumb",
                                    "width": 405,
                                    "height": 720
                                },
                                {
                                    "url": "https://sun4.userapi.com/sun4-15/s/v1/if2/cXO4aIudacvZ6MrXX-m90fQaQHEYqWcTQOhI5O-QVkLlh8OWhIIjm1FlJ9A_cA_APe4LIzf7daR5775bsM5N4CbM.jpg?size=360x640&quality=96&type=video_thumb",
                                    "width": 320,
                                    "height": 569
                                },
                                {
                                    "url": "https://sun4.userapi.com/sun4-15/s/v1/if2/CHu4e2gSNSEoewm1kEi6TpujeLx7XrJH7KUOhGlRDK0lVZRLdK959pS_IiMf4ppHMdqVu-3axi-CklJszJ3MeGp8.jpg?size=810x1440&quality=96&type=video_thumb",
                                    "width": 720,
                                    "height": 1280
                                },
                                {
                                    "url": "https://sun4.userapi.com/sun4-15/s/v1/if2/ypuEdXGxV0RC9hAbEY5a08dajvqf1Bx3Rgi33fS881oVBWxCVIGvqa24NbN3aLBozDYpQNPcguc6eGGKpYWtDH9j.jpg?size=1152x2048&quality=96&type=video_thumb",
                                    "width": 1024,
                                    "height": 1820
                                },
                                {
                                    "url": "https://sun4.userapi.com/sun4-15/s/v1/if2/3kVTB9uU00YDlsHSmR_WratwE6LXakJmRW6BHInr_Ns-ScWiwyIdCTdJl55GPwGdg8nXb1XxHBunbuVxtY81fAnz.jpg?size=0x0&quality=90&proxy=1&type=video_thumb",
                                    "width": 2304,
                                    "height": 4096
                                }
                            ],
                            "first_frame": [
                                {
                                    "url": "https://i.mycdn.me/getVideoPreview?id=2549431405194&idx=0&type=39&tkn=JFI0PPw63SL0SWmOYQYfHUFX9QU&fn=vid_f",
                                    "width": 405,
                                    "height": 720
                                },
                                {
                                    "url": "https://i.mycdn.me/getVideoPreview?id=2549431405194&idx=0&type=39&tkn=JFI0PPw63SL0SWmOYQYfHUFX9QU&fn=vid_md",
                                    "width": 270,
                                    "height": 480
                                },
                                {
                                    "url": "https://i.mycdn.me/getVideoPreview?id=2549431405194&idx=0&type=39&tkn=JFI0PPw63SL0SWmOYQYfHUFX9QU&fn=vid_d",
                                    "width": 135,
                                    "height": 240
                                },
                                {
                                    "url": "https://i.mycdn.me/getVideoPreview?id=2549431405194&idx=0&type=39&tkn=JFI0PPw63SL0SWmOYQYfHUFX9QU&fn=vid_sm",
                                    "width": 72,
                                    "height": 128
                                },
                                {
                                    "url": "https://i.mycdn.me/getVideoPreview?id=2549431405194&idx=0&type=39&tkn=JFI0PPw63SL0SWmOYQYfHUFX9QU&fn=vid_h",
                                    "width": 540,
                                    "height": 960
                                },
                                {
                                    "url": "https://i.mycdn.me/getVideoPreview?id=2549431405194&idx=0&type=39&tkn=JFI0PPw63SL0SWmOYQYfHUFX9QU",
                                    "width": 720,
                                    "height": 1280
                                }
                            ],
                            "width": 1080,
                            "height": 1920,
                            "id": 456245955,
                            "owner_id": -23509252,
                            "title": "Клип",
                            "is_favorite": false,
                            "track_code": "video_0c3f1fe70TzthQ_mbqPtunKt54bhxGW0lCXeMaA-vv6hW1136rPjFvKCDoxnqei2dcfTs9f2UYGtEOs111_Skg",
                            "repeat": 1,
                            "type": "short_video",
                            "views": 13445
                        }
                    }
                ],
                "post_source": {
                    "type": "vk"
                },
                "comments": {
                    "can_post": 1,
                    "count": 16
                },
                "likes": {
                    "can_like": 1,
                    "count": 84,
                    "user_likes": 0,
                    "can_publish": 1
                },
                "reposts": {
                    "count": 12,
                    "user_reposted": 0
                },
                "views": {
                    "count": 13575
                },
                "donut": {
                    "is_donut": false
                },
                "ads_easy_promote": {
                    "type": 2,
                    "text": "Что-то пошло не так.",
                    "label_text": "",
                    "button_text": "",
                    "is_ad_not_easy": false
                },
                "short_text_rate": 0.8,
                "hash": "y1UoHb_HyWZoahfYU1hHJqrAlQ"
            }
        ],
        "next_from": "4"
    }
}

**Comment by TheRealMaN** [comment]
А такой тип видео поддерживается?
"type":"short_video"?

**Comment by axd1x8a** [comment]
https://github.com/VKCOM/vk-api-schema/issues/212

**Comment by axd1x8a** [comment]
Fixed
