### ISSUE TITLE
Баг: Exception "file is undefined" у vkbottle.GraffitiUploader(...).upload() при использовании типа bytes

### ISSUE THREAD

**Issue by Zensonaton** [vkbottle/vkbottle#520]
**Опишите баг:** Происходит Exception при использовании типа `bytes`:
`vkbottle.exception_factory.code_exception.VKAPIError_100: One of the parameters specified was missing or invalid: file is undefined`

**Ваш код (опционально)**: https://pastebin.com/iEXXVrNh
Необходимо положить любое изображение в формате `png` и запустить код.

**Заполните поля технической информации:**

**vkbottle**: `4.3.2`
**vkbottle-types**: `5.131.146.2.post1`
**OS**: `Manjaro (Arch) Linux`

**Comment by axd1x8a** [comment]
Проблема на строне вк

**Comment by Zensonaton** [comment]
Как оказалось, и вправду, майл ру очень бедная компания, и поэтому им пришлось ограничить доступ к [отправке графити](https://vk.com/wall-1_395554), ибо люди использовали их для создания стикеров.
Спасибо за наводку.
