### ISSUE TITLE
Баг: {Выдаёт огромный Error}

### ISSUE THREAD

**Issue by selfiction** [vkbottle/vkbottle#524]
**Бот использует картинку, который отправляет пользователь, затем преобразует его в демотиватор:** ...

**Ожидаемое поведение:** должен отправиться демотиватор

**Фактическое поведение:** картинка сохраняется на устройство(пол пути до конечного результата), но уже выдает ошибку и картинка не отправляется от бота. на локальной машине работает без нареканий, но заливая на хероку, заметил эту ошибку

**Ваш код (опционально)**: ...

https://pastebin.com/vjfxsrVr
**Заполните поля технической информации:https://pastebin.com/ZEQvHLFa(тут сам лог ошибки)
**

---
vkbottle==4.3.4
vkbottle-types==5.131.146.5
OS: Windows 10

---

**Comment by hilorioze** [comment]
Скорее всего у вас не установлен шрифт на сервере.

**Comment by selfiction** [comment]
спасибо, помогло
