### ISSUE TITLE
Баг: unclosed connector в vkbottle/tools/dev/auth.py

### ISSUE THREAD

**Issue by Friendosie** [vkbottle/vkbottle#529]
Ошибка:
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x769411bfa0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x768ffd4ca0>, 53486.361666725)]']
connector: <aiohttp.connector.TCPConnector object at 0x78ee49150>
Решение бага:
https://pastebin.com/W48mDcNJ

**Comment by axd1x8a** [comment]
Какая версия вкботла?

**Comment by Friendosie** [comment]
4.3.8

**Comment by axd1x8a** [comment]
Покажите код

**Comment by Friendosie** [comment]
https://pastebin.com/2Uk2g20P
В файле accs находится аккаунты в формате login:password

**Comment by axd1x8a** [comment]
У меня баг не воспроизводится
