### ISSUE TITLE
Баг: types at GetAlbumsResponse

### ISSUE THREAD

**Issue by Pavel-qr** [vkbottle/vkbottle#535]
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for GetAlbumsResponse
response -> items -> 0 -> created
  field required (type=value_error.missing)
response -> items -> 0 -> updated
  field required (type=value_error.missing)
response -> items -> 1 -> created
  field required (type=value_error.missing)
response -> items -> 1 -> updated
  field required (type=value_error.missing)

created — дата создания альбома в формате unixtime (не приходит для системных альбомов);

updated — дата последнего обновления альбома в формате unixtime (не приходит для системных альбомов);

---
vkbottle: 4.3
vkbottle-types: 5.131.146

**Comment by axd1x8a** [comment]
Откройте ишью в [VKCOM/vk-api-schema](https://github.com/VKCOM/vk-api-schema)
