### ISSUE TITLE
Баг: декоратор raw_event() работает только в одном Blueprint/Labeler

### ISSUE THREAD

**Issue by HamerLolKekChegoo** [vkbottle/vkbottle#539]
При подключении первого Blueprint/Labeler с декоратором raw_event(), работает только первый подключенный, игнорируя остальные. Подключаю стандартным способом, который описан в документации

---

vkbottle==4.1.13
vkbottle-types==5.131.146.2.post1
OS: Windows 10

---

**Comment by axd1x8a** [comment]
Не помню в какой точно, но это точно исправлено в последних версиях.
