### ISSUE TITLE
Создание Lock контроллера для вызова методов в User LP

### ISSUE THREAD

**Issue by markelovstyle** [vkbottle/vkbottle#54]
Часто сталкиваюсь с такой ситуацией, когда ВК пробрасывает исключение **Too many requests per second**, поэтому неплохо было бы сделать какой-нибудь контроллер, который будет управлять запросами API.

**Comment by kesha1225** [comment]
Сделай много токенов и все

**Comment by markelovstyle** [comment]
Проблема решена. Много токенов все таки помогли ._.
