### ISSUE TITLE
Множественное нажатие на кнопку клавиатуры.

### ISSUE THREAD

**Issue by belkinark** [vkbottle/vkbottle#543]
Приветсвую, пытаюсь реализовать функцию кнопок. Есть проблема, когда нажимаешь на кнопку сообщение и новая клавиатура отправляется с задержкой, из-за этого успеваешь нажать на кнопку ещё 10 раз и соответсвенно сообщение с клавиатурой и сама функция выполняются тоже 10 раз. Есть ли решение это проблемы без использования one_time?

Примерно так это выглядит:
![unknown 1](https://user-images.githubusercontent.com/67878832/185790700-3db9c126-2123-4367-8ef4-4e0e96de6f8f.png)

Хотелось бы получить такой результат.
![image](https://user-images.githubusercontent.com/67878832/185790601-36b7a59d-019a-445c-aa50-9a9637a13187.png)

В документации по этому поводу ничего не нашёл.

```
keyboard_start = Keyboard()
keyboard_start.add(Text("hi", {"cmd": "test"}))

keyboard_t = Keyboard()
keyboard_t.add(Text("start"))

@bot.on.private_message(lev = "start")
async def handler(message: Message):
    await message.answer("Это первое сообщение. После него появляется клавиатура с кнопкой <hi>", keyboard = keyboard_start)


@bot.on.private_message(payload={"cmd": "test"})
async def handler(message: Message):
    await message.answer("Это второе сообщение. После него появляется клавиатура с кнопкой <start>", keyboard = keyboard_t)
```

**Comment by axd1x8a** [comment]
Используйте стейты.
https://vkbottle.readthedocs.io/ru/latest/high-level/handling/state-dispenser/

**Comment by belkinark** [comment]
Всё ровно не то.
Я так же успеваю нажать на кнопку 3 раза и он выполняет эту функцию 3 раза.

![image](https://user-images.githubusercontent.com/67878832/185795417-fab76f81-1c01-4cf1-9421-1ed672ee93f9.png)

**Comment by axd1x8a** [comment]
Значит вы делаете что-то не так.

**Comment by belkinark** [comment]
Забыл код прикрепить

```
keyboard_start = Keyboard()
keyboard_start.add(Text("hi", {"cmd": "test"}))

keyboard_t = Keyboard()
keyboard_t.add(Text("start"))

class SuperStates(BaseStateGroup):
    TEST_STATE = 0

@bot.on.private_message(lev = "start")
async def handler(message: Message):
    await message.answer("Это первое сообщение. После него появляется клавиатура с кнопкой <hi>", keyboard = keyboard_start)
    await bot.state_dispenser.set(message.peer_id, SuperStates.TEST_STATE)


@bot.on.private_message(state = SuperStates.TEST_STATE)
async def handler(message: Message):
    await message.answer("Это второе сообщение. После него появляется клавиатура с кнопкой <start>", keyboard = keyboard_t)
```

**Comment by axd1x8a** [comment]
Сделайте чтобы первое сообщение обрабатывалось только если нет стейта.

**Comment by axd1x8a** [comment]
А сам стейт устанавливаете раньше отправки.

**Comment by belkinark** [comment]
Всё отлично, спасибо.
