### ISSUE TITLE
Вопрос: Как сделать так чтоб return возвращал значения chat_id и user_id, а не отправлял их в виде сообщений в вк?

### ISSUE THREAD

**Issue by KOMPuteRSH4IK** [vkbottle/vkbottle#547]
Как сделать так чтоб return возвращал значения chat_id и user_id, а не отправлял их в виде сообщений в вк
код: https://pastebin.com/rWEAgLj9

**Comment by axd1x8a** [comment]
https://vkbottle.readthedocs.io/ru/latest/high-level/handling/return-manager/
