### ISSUE TITLE
Вопрос: Как устроить проверку на пустой аргумент

### ISSUE THREAD

**Issue by rirxr** [vkbottle/vkbottle#548]
К примеру

 ```
 @client.on.message(text="/text <arg>")
 await def text(message: Message, arg):
    if arg is None:
       await message.reply("text")
    else:
       await message.reply("text2")
 ```

Установка arg в значение None тоже не помогает

**Comment by axd1x8a** [comment]
Этот рул может принимать как строку, так и список строк. Просто в декоратор передайте еще и строку без аргумента, а в самой функции сделайте его опциональным.
