### ISSUE TITLE
Использование vk_api в vkbottle

### ISSUE THREAD

**Issue by bimgeer** [vkbottle/vkbottle#561]
Недавно видел, как пользователь github использовал библиотеку vk_api в vkbottle.
К сожалению, ссылку забыл сохранить.

Подскажите, пожалуйста, в каком пункте документации можно найти эту функцию.

**Comment by axd1x8a** [comment]
Для чего вам vk_api? В vkbottle уже есть все, что предоставляет эта библиотека.

**Comment by bimgeer** [comment]
Затем, что для моей задачи не хватает навыка владения vkbottle и некоторые вещи было бы проще и быстрее написать при помощи vk_api, нежели тратить время, которого и так нет, на изучение криво написанной документации.

**Comment by bimgeer** [comment]
> Для чего вам vk_api? В vkbottle уже есть все, что предоставляет эта библиотека.

Не понимаю вашей логики. Вы создаёте метод, при помощи которого можно связать 2 разные библиотеки, люди этот метод находят, используют, но при этом на мой вопрос поступает ответ, что в vkbottle уже всё есть и не нужон этот ваш vk_api. И это вместо того, чтобы ответить на поставленный вопрос, который был не об этом.

Может проще этот метод удалить? Или всё таки отвечать на поставленные вопросы, а не вкидывать своё личное мнение где его не просят? Или же документацию отредактировать так, чтобы её не приходилось круглыми сутками листать, чтобы новички в написании ботов не шарахались по углам от нервоза?

**Comment by axd1x8a** [comment]
Сожалею, что вам тяжело читать документацию, написанную максимально простым языком. Советую ознакомиться с простейшими концепциями программирования и основами python. Тогда вы все сможете понять.

**Comment by axd1x8a** [comment]
Связать можно что угодно (ссылаюсь на свой предыдущий комментарий). Никаких специальных методов не существует. 
Для новичков существует туториал, подробно разжевывающий базовый функционал vkbottle.

**Comment by axd1x8a** [comment]
Вы можете сразу спросить о том, что у вас не получается, а не изобретать велосипед.

**Comment by axd1x8a** [comment]
Ладно, надеюсь, что вы уже решили свою проблему.
