### ISSUE TITLE
Вопрос: Как получить аргументом строку состоящую из нескольких слов?

### ISSUE THREAD

**Issue by NotWorkingCode** [vkbottle/vkbottle#567]
Имеется хэндлер вида:
```python
@blueprint.on.message(text=["+written <mention> <reason>", "+письменный <mention> <reason>"])
async def give_written_warn_full(message: Message, mention, reason):
```
В аргумент "Причина" может приходить строка состоящая из нескольких слов.

Как для такой команды изменить хэндлер, чтобы в функцию передавалась вся строка?

**Comment by axd1x8a** [comment]
Она и так будет приходить.

**Comment by KurimuzonAkuma** [comment]
алиса ку

**Comment by shjwkdixkskwldi** [comment]
Мне говорили, что оставшаяся строка и будет.

**Comment by HamerLolKekChegoo** [comment]
Дополни ишью, тем что выдаёт

**Comment by NotWorkingCode** [comment]
Проблема была не в библиотеке, а в моем коде,
Всем спасибо.

**Comment by AikoSora** [comment]
@NotWorkingCode Ок

**Comment by ZeN220** [comment]
@AikoSora ок
