### ISSUE TITLE
Make TokenManager

### ISSUE THREAD

**Issue by markelovstyle** [vkbottle/vkbottle#57]
Make TokenManager for multiple token storage and then switch them in case of too many requests per second error

**#TODO**

**Comment by kesha1225** [comment]
Use [vkwave](https://github.com/fscdev/vkwave)!

Берешь импортишь токен, далее создаешь сколько тебе их надо:
```python
from vkwave.api.token.token import UserSyncSingleToken, BotSyncSingleToken, Token

bot_plain_token1 = Token("...")
bot_plain_token2 = Token("...")

bot_token1 = BotSyncSingleToken(bot_plain_token1)
bot_token2 = BotSyncSingleToken(bot_plain_token2 )
```
Потом просто создаешь инстанс апи со всеми этими токенами:
```python
from vkwave.api.methods import API

api = API(tokens=[bot_token1, bot_token2], cliens=AIOHTTPClient())
```
В процессе использования бота он сам будет брать токены и делать запросы через них.

Дока поподробнее - https://github.com/fscdev/vkwave/blob/master/docs/api/index.md
