### ISSUE TITLE
Предложение: Использование msgspec вместо msgpack & orjson/ujson

### ISSUE THREAD

**Issue by wildrun0** [vkbottle/vkbottle#572]
При запуске замечаю что 
`msgpack not installed, MsgPackSerializer unavailable (serializers.py:15)`
и как мне кажется, более лучшей (и более быстрой) альтернативой для msgpack будет [msgspec](https://github.com/jcrist/msgspec). 
Оно так же может заменить `ujson`

**Comment by wildrun0** [comment]
Я дико извиняюсь, не вник до конца в логи, это **не от vkbottle** сообщения про msgpack
Но насчет json -  msgpec быстрее конкурентов в лице orjson/ujson и пр. в 2-40 раз

**Comment by axd1x8a** [comment]
Его API совместим с библиотекой json?

**Comment by dhvcc** [comment]
@FeeeeK ujson да, orjson же dumps делает в байты (losds из строки работает как обычно). Можно самому обернуть, но может проще юзать ujson. Для этого разве что нужно провести бенчмарки и понять, если ли реальный перфоманс буст в ботк или это просто будет +1 зависимость

**Comment by wildrun0** [comment]
msgspec использует msgspec.json.encode чтобы приводить типы (msgspec.Struct)  в байты и msgspec.json.decode чтобы декодировать байты сразу в тип msgspec.Struct

**Comment by ZeN220** [comment]
@dhvcc опять пытаются какие то наносекунды сэкономить

**Comment by axd1x8a** [comment]
> msgspec использует msgspec.json.encode чтобы приводить типы (msgspec.Struct) в байты и msgspec.json.decode чтобы декодировать байты сразу в тип msgspec.Struct

Тогда нужно будет избавляться от pydantic, а этого в планах нет.
