### ISSUE TITLE
Migrate from `pydantic` to `msgspec`

### ISSUE THREAD

**Issue by axd1x8a** [vkbottle/vkbottle#573]
В #572 было предложено использовать `msgspec` вместо `json`, но можно пойти дальше и использовать его вместо `pydantic`.
Пока не совсем ясно, какой будет прирост в производительности, но, в теории, это должно сильно ускорить обработку и валидацию ответов от вк.
Проблема лишь в том, что потребуется полностью переписать [vkbottle/types](https://github.com/vkbottle/types), на что пока нет времени.

**Comment by axd1x8a** [comment]
Как оказалось, `msgspec` не поддерживает python 3.7, что тоже может стать проблемой, тк у vkbottle нет никаких проблем с его поддержкой и отказываться от нее нет смысла.

**Comment by dhvcc** [comment]
@FeeeeK через 8 месяцев дропается поддержка вроде как. По такой же логике 3.6 не поддерживали.

Лучше сначала провести бенчмарки, а потом уже думать стоит ли вообще трогать это всё дело. Нужно ли будет кодген переписывать под `msgspec`? Есть ли у `msgspec` все фичи что тут уже юзаются?

**Comment by axd1x8a** [comment]
Как оказалось, вконтакте поддерживает msgpack, а это значит, что от msgspec теперь еще больше смысла

**Comment by mironovmeow** [comment]
В другой библиотеке для golang уже добавили экспериментально поддержку: https://github.com/SevereCloud/vksdk/discussions/181. Как там пишут, там есть некоторые проблемы с кодировкой. Прошёл уже год, возможно проблема решена, но, возможно, не стоит завязывать логику на недокументированный msgpack от vk api.

Вопрос о миграции на msgspec остаётся открытым.

**Comment by axd1x8a** [comment]
@mironovmeow Приложение вк уже минимум полгода использует msgpack для запросов к апи и никаких проблем, вроде бы, нет

**Comment by mironovmeow** [comment]
Попробовал рассмотреть возможность перехода и столкнулся вот с какой проблемой:

В pydantic можно наследоваться от нескольких моделей. Это уже используется в vkbottle-types.
```py
from pydantic import BaseModel

class A(BaseModel):
    a: int

class B(BaseModel):
    b: int

#  Это работает
class C(A, B):
    c: int
```

В msgspec на такое ругается:
```py
from msgspec import Struct as BaseModel

class A(BaseModel):
    a: int

class B(BaseModel):
    b: int

# TypeError: multiple bases have instance lay-out conflict
class C(A, B):
    c: int
```

**Comment by luwqz1** [comment]
@mironovmeow а почему они конфликтуют?
