### ISSUE TITLE
How i can handle kick event&

### ISSUE THREAD

**Issue by IgnatInyutsin** [vkbottle/vkbottle#581]

**Comment by relativemodder** [comment]
@IgnatInyutsin ??

**Comment by IgnatInyutsin** [comment]
> @IgnatInyutsin ??

I want handle kick event in chats like @bot.on.message

**Comment by ronmount** [comment]
@IgnatInyutsin ну если сильно хочется то делай чё кайф брат

**Comment by TheBakerCat** [comment]
@IgnatInyutsin Делай че по кайфу бро

**Comment by IgnatInyutsin** [comment]
> @IgnatInyutsin ну если сильно хочется то делай чё кайф брат

Я хочу понять, как

**Comment by VodoGamer** [comment]
кайфуй от кайфа брат

**Comment by TheBakerCat** [comment]
@VodoGamer Кайфы кайфы кайфуле

**Comment by suconakh** [comment]
https://github.com/vkbottle/vkbottle/blob/33394142644615fef75a90f6263cb8ed6686a5d9/examples/high-level/easy_bot.py#L49-L63

**Comment by IgnatInyutsin** [comment]
Спасибо!

**Comment by IgnatInyutsin** [comment]
> https://github.com/vkbottle/vkbottle/blob/33394142644615fef75a90f6263cb8ed6686a5d9/examples/high-level/easy_bot.py#L49-L63

извиняюсь, а можете подсказать хандлер для кика в беседе именно, никак не могу найти
