### ISSUE TITLE
Что не так со стейтом

### ISSUE THREAD

**Issue by ghost** [vkbottle/vkbottle#593]
**Вопрос:** ...
Код:
```
class banname(BaseStateGroup):
	BAN_NAME="jjjj"
@bot.on.private_message(lev='/ban')
async def pla1y(message: Message):
	u=await bot.api.users.get(message.from_id, {"screen_name"})
	user_id=u[0].screen_name
	op,balance,start,prefix=get_db(user_id) //это уже просто в каждом методе есть дабы работать с данными юзера
	await bot.state_dispenser.set(message.peer_id, banname.BAN_NAME)
	return "Введите имя пользователя для блокировки"

@bot.on.message(state=banname.BAN_NAME)  
async def ban_handler(message: Message):
    user_for_ban=message.text
    await message.answer("Вызван метод блокировки")
    upd_db('users',user_for_ban,'op','0')
```
Да все работает, но при этом ban_handler вызывается при любой команде
Пример:
/ban
Результат: Введите имя пользователя для блокировки
 Der_439
Результат: Вызван метод блокировки
gjghgewkgewkkgewgew
Результат: Вызван метод блокировки

**Comment by ghost** [comment]
После 1 вызова команды он любую команду считает как этот стейт

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/86500766/203739646-cb454e29-690c-4bd0-8404-a58abaaeabad.png)

**Comment by axd1x8a** [comment]
Стейты нужно удалять, посмотрите примеры и почитайте документацию внимательнее.

**Comment by FeeeeK** [comment]
Стейты нужно удалять, посмотрите примеры и почитайте документацию внимательнее.
