### ISSUE TITLE
Баг: Ошибка парсинга заказа

### ISSUE THREAD

**Issue by adlemx** [vkbottle/vkbottle#598]
**Опишите баг:** 
Ошибка парсинга заказа

**Ожидаемое поведение:** 
Чтобы исправить нужно просто добавить  `= False` в конце 6468 строки в файле vkbottle_types\codegen
**Фактическое поведение:** 

pydantic.error_wrappers.ValidationError: 1 validation error for MarketOrderNew
object -> preview_order_items -> 0 -> photo -> has_tags
  field required (type=value_error.missing)

**Ваш код (опционально)**: ...
```
@bot.on.raw_event(GroupEventType.MARKET_ORDER_NEW, dataclass=MarketOrderNew)
async def handle(order: MarketOrderNew):
```

**Заполните поля технической информации:**

---
vkbottle: 4.3.10
vkbottle-types: 5.131.146.10
OS: Windows 10

---

**Comment by axd1x8a** [comment]
Установите последнюю версию vkbottle-types
