### ISSUE TITLE
Вопрос: обрабатывает ли event.edit_message(...) ошибку VK API 909?

### ISSUE THREAD

**Issue by snowlue** [vkbottle/vkbottle#600]
Столкнулся с необходимостью редактировать сообщение после пришедшего message_event и задумался, надо ли мне обрабатывать ошибку, возникающую в результате попытки отредактировать слишком старое сообщение. Заглянул под капот — такой реализации нет. Т.е., скорее всего, мне просто вернётся VKApiError[909]. Верно ли я понимаю? От этого зависит, надо ли мне писать обёртку, обрабатывающую 909 или нет.

![image](https://user-images.githubusercontent.com/22418658/209611545-c848c473-0413-4bff-9767-0b21191e03f2.png)

**Comment by axd1x8a** [comment]
Нет, обрабатывать ошибки вы должны сами.
[Вот, как вы можете это сделать](https://vkbottle.readthedocs.io/ru/latest/tutorial/error-handling/)
