### ISSUE TITLE
Баг: {краткое описание}

### ISSUE THREAD

**Issue by usir123** [vkbottle/vkbottle#605]
**Опишите баг:** ...
В сообщении имееется клавиатура, но при этом в событии флаг keyboard - None
**Ожидаемое поведение:** ...
возвращение клавиатуры, а не None
**Фактическое поведение:** ...

**Ваш код (опционально)**: ...
https://pastebin.com/aud4xywK

**Заполните поля технической информации:**

---
vkbottle: 4.3.12
vkbottle-types: 5.131.146
OS: Windows 10

---

**Comment by axd1x8a** [comment]
Поменяйте флаги событий, найти их можно в докуменции вк.

**Comment by usir123** [comment]
каким образом можно поменять флаги?

**Comment by axd1x8a** [comment]
https://github.com/vkbottle/vkbottle/blob/994fd9902abaa1e7830e6d373d1d496c786a2abc/vkbottle/polling/user_polling.py#L33
