### ISSUE TITLE
Как вытащить message_id последнего сообщения бота?

### ISSUE THREAD

**Issue by ghost** [vkbottle/vkbottle#612]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by axd1x8a** [comment]
При разработке vkbottle расчет был на то, что пользователь знает основы python и ООП, а так же пишет в [рекомендуемых IDE](https://vkbottle.readthedocs.io/ru/latest/tutorial/recommended-ide/).

В вашем случае нужно всего-лишь обратиться к атрибуту объекта, очень странно, что вы этого не знаете, но все равно пытаетесь писать ботов.

**Comment by barsikus007** [comment]
попробуйте s = str(message1) 👍

**Comment by ghost** [comment]
> основы python и ООП

С C++ пересел на python из-за разнообразия библиотек, и работаю в основном из знаний о C++

**Comment by luwqz1** [comment]
@Der439 message.message_id, а так твой код парсит репрезентацию объекта MessagesSendUserIdsResponseItem

**Comment by ronmount** [comment]
@Der439 охуеть

**Comment by ghost** [comment]
> @Der439 охуеть

что?

**Comment by ronmount** [comment]
@Der439 Да не, просто не обратил внимания на твой опыт, я забыл что в си плас плас нет ооп и всё просто перегоняется в строки и парсится по-байтово

**Comment by ghost** [comment]
> @Der439 Да не, просто не обратил внимания на твой опыт, я забыл что в си плас плас нет ооп и всё просто перегоняется в строки и парсится по-байтово

Я понимаю что в C++ есть ооп, но я плохо понял как работать с ООП в python

**Comment by ronmount** [comment]
> Я понимаю что в C++ есть ооп, но я плохо понял как работать с ООП в python

Хорошая идея начать изучение языка с разработки бота! Удачи в начинаниях!
