### ISSUE TITLE
Вопрос: Как отправить сообщенте с клавиатурой в виде ответа на нажатие callback кнопки?

### ISSUE THREAD

**Issue by KOMPuteRSH4IK** [vkbottle/vkbottle#613]
Как отправить сообщенте с клавиатурой в виде ответа на нажатие callback кнопки?

**Comment by luwqz1** [comment]
@KOMPuteRSH4IK Прочитать документацию — ❌
Написать новый issue — ✅

**Comment by axd1x8a** [comment]
https://github.com/vkbottle/vkbottle/blob/master/examples/high-level/callback_buttons.py
