### ISSUE TITLE
нехватка параметра transcript в голосовых сообщениях

### ISSUE THREAD

**Issue by mrtnvgr** [vkbottle/vkbottle#621]
В классе голосовых сообщений (`MessagesAudioMessage`) нету параметра `transcript`.

_А также в [официальной документации](https://dev.vk.com/reference/objects/audio-message) не упомянуты `transcript` и уже существующий в классе `transcript_error`._

vkbottle/types#39

**Comment by mrtnvgr** [comment]
Такая же ситуация и с `transcript_state`

**Comment by axd1x8a** [comment]
Откройте ишью в [схеме апи вконтакте](https://github.com/VKCOM/vk-api-schema/issues), а потом предоставьте пример этих объектов.

**Comment by mrtnvgr** [comment]
> Откройте ишью в [схеме апи вконтакте](https://github.com/VKCOM/vk-api-schema/issues)

VKCOM/vk-api-schema#236

**Comment by mrtnvgr** [comment]
> ... предоставьте пример этих объектов.

![](https://i.imgur.com/HeFh25A.png)

Без:
```json
{
  "type": "audio_message",
  "audio_message": {
    "id": "...",
    "owner_id": "...",
    "duration": 4,
    "waveform": [
      17,
      14,
      0,
      6,
    ],
    "link_ogg": "https://psv4.userapi.com/s/v1/amsg/....ogg",
    "link_mp3": "https://psv4.userapi.com/s/v1/amsg/....mp3",
    "locale": "",
    "is_recognized": 0,
    "access_key": "2uCU2...UR4Iz",
    "transcript_state": "done"
  }
}
```

С распознанным текстом:
```json
{
  "type": "audio_message",
  "audio_message": {
    "id": "...",
    "owner_id": "...",
    "duration": 3,
    "waveform": [
      1,
      11,
      11,
      26
    ],
    "link_ogg": "https://psv4.userapi.com/s/v1/amsg/....ogg",
    "link_mp3": "https://psv4.userapi.com/s/v1/amsg/....mp3",
    "locale": "",
    "is_recognized": 0,
    "access_key": "JgBVo...eXf5k",
    "transcript": "Поверка.",
    "transcript_state": "done"
  }
}
```

**Comment by mrtnvgr** [comment]
@FeeeeK есть новости?

**Comment by ronmount** [comment]
@mrtnvgr так в схеме вк нет этого поля, спрашивай у впарашников новости 
https://github.com/VKCOM/vk-api-schema/blob/master/messages/objects.json

**Comment by mrtnvgr** [comment]
> @mrtnvgr так в схеме вк нет этого поля, спрашивай у впарашников новости 
> https://github.com/VKCOM/vk-api-schema/blob/master/messages/objects.json

они уже как полгода никому не отвечают и актива нету вообще

**Comment by ronmount** [comment]
@mrtnvgr что по-твоему должен сделать мейнтейнер библиотеки, которая генерит модели по открытой схеме вконтакте? какие новости должны быть от него?

**Comment by mrtnvgr** [comment]
> @mrtnvgr что по-твоему должен сделать мейнтейнер библиотеки, которая генерит модели по открытой схеме вконтакте? какие новости должны быть от него?

ну во-первых в тайпах уже есть поля которых нет в схеме и я уже сделал пулл реквесты, поэтому я просто хотел получить ответ по ним. Мне кажется что диалог стал агрессивным, простите если я туплю :3

**Comment by axd1x8a** [comment]
Чуть позже вернусь к разработке, у меня пока нет времени совсем.
