### ISSUE TITLE
Предложение: поддержка сервиса распознавания речи ВКонтакте

### ISSUE THREAD

**Issue by snowlue** [vkbottle/vkbottle#624]
На [этой странице документации](https://dev.vk.com/api/voice-tech) представлен сервис распознавания речи. [Секция методов — asr](https://dev.vk.com/method/asr).  
Для его поддержки понадобится:
1. Авторизация в `vkbottle.API` с использованием сервисного ключа доступа (возможно реализована, я не проверял)
2. Новый `Uploader`, например, `SpeechUploader`, через который будет происходить всё действие (из этого следует, что нужно пересмотреть подход к `AnyUploader` или же `SpeechUploader` должен быть некой иной сущностью)
3. Безусловно, асинхронное получение расшифровки ⇒ должен проверяться статус задачи на обработку аудиозаписи методом **asr.checkStatus** — при статусе «finished» возвращается расшифровка
4. Базовые проверки файла перед загрузкой — соответствие формату, длина меньше максимального лимита
5. Бросание исключения при статусах задачи «internal_error», «transcoding_error» и «recognition_error» и при ошибках со стороны ВК под кодами 7701 и 7703

**Comment by axd1x8a** [comment]
У меня нет возможности проверить, но это должно работать. Валидация и так происходит на стороне фреймворка, так что добавлять новые ошибки нет смысла, а статус вы можете получить вызвав соответствующий метод с параметром, полученным из `SpeechUploader.raw_upload()`

**Comment by axd1x8a** [comment]
Пока закрою это ишью, как решенное. Если есть какие-то вопросы - пишите.

**Comment by snowlue** [comment]
Окей👌🏻 Нет возможности сейчас проверить, извиняюсь.
