### ISSUE TITLE
Слишком долгая загрузка текста Callback кнопок в Keyboard

### ISSUE THREAD

**Issue by Koljisto** [vkbottle/vkbottle#625]
Столкнулся с такой ситуацией:
Имеется некоторый код 

```python
@bot.on.raw_event(GroupEventType.MESSAGE_EVENT, dataclass=MessageEvent)
async def handle_message_event(event: MessageEvent):
    # Main menu handlers payload
    if "composition" in event.payload.keys():
        keyboard = (
            Keyboard(one_time=True, inline=False)
            .add(Callback(label="Посмотреть", payload={'view': 1})).row()
            .add(Callback(label="Назад", payload={'back': 1}))
        ).get_json()
        await event.send_message(message="Выбери режим", keyboard=keyboard)

    # Composition menu handler payload
    if "view" in event.payload.keys():
        await event.show_snackbar("Text")
    if "back" in event.payload.keys():
        keyboard = (
            Keyboard(one_time=True, inline=False)
            .add(Callback(label="Состав", payload={'composition': 1}))
        ).get_json()
        await event.send_message(message="Главное меню", keyboard=keyboard)
```
![image](https://user-images.githubusercontent.com/25975085/215051861-d8485559-19a9-4fd4-a53b-7d5a49a0dcb9.png)
При нажатии на кнопку она загружает следующее меню:
![image](https://user-images.githubusercontent.com/25975085/215052024-3a217564-9125-43d8-a41c-51991a0de5b1.png)
Однако вместо полноценного меню название кнопки не видно и отображается лишь иконка загрузки вместо текста. Так может продолжаться около минуты, но позже кнопка загружается и она функциональна. Как это можно исправить чтобы текст кнопки стал доступен сразу, а не через некоторое время?

**Comment by snowlue** [comment]
Попробуйте не event.send_message, а event.edit_message. По крайней мере у меня таких проблем не возникает, и я думаю, что как раз из-за того, что я редактирую текущее сообщение, а не отправляю новое.

То, что спиннер продолжает крутиться на той же самой кнопке, хотя клавиатура была заменена — тут проблема, возможно, веба. Вы пробовали с приложения? Там такая же ситуация?

Если да, то, предполагаю, что проблема на стороне ВКонтакте, т.к., скорее всего, API считает, что если не пришёл ответ на событие message_event (т.е. кнопка не использует messages.sendMessageEventAnswer) или сообщение не было изменено, то нажатие кнопки не отработало, но это, как мы видим в вашем случае, может быть не так.

А если нет, то тут, очевидно, у ВК проблемы с вебом. Так или иначе, попробуйте сменить отправку на редактирование.

**Comment by axd1x8a** [comment]
В [документации](https://dev.vk.com/api/bots/development/keyboard#Действие%20после%20нажатия%20на%20кнопку) указано, что нужно отвечать на евент, отправка сообщения не является ответом.

**Comment by TemurArbuz** [comment]
Как вариант, достаточно отправить show_snackbar
