### ISSUE TITLE
Вопрос: Не обрабатывать ответы бота, как новые евенты

### ISSUE THREAD

**Issue by mrtnvgr** [vkbottle/vkbottle#631]
**Вопрос:**
В ответе может содержаться текст, вызывающий один из хэндлеров, поэтому хотелось бы игнорировать сообщения отправленные через `message.reply` и `message.answer`. Как можно это сделать?

**Comment by axd1x8a** [comment]
Выключить исходящие сообщения в настройках группы.

**Comment by mrtnvgr** [comment]
> Выключить исходящие сообщения в настройках группы.

@FeeeeK мне нужно на юзере
