### ISSUE TITLE
Ошибка в документации

### ISSUE THREAD

**Issue by ghost** [vkbottle/vkbottle#656]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/master.zip`) и проблема осталась

### Описание

В документации написано:
Вложения
Если у вас уже есть ссылка на вложение

Если у вас уже есть ссылка на вложение вида `"type{OWNER_ID}_{ITEM_ID}" `
Но, когда бот ловит документ/фото в диалоге,он не может его отправить параметром attachment, потому что фотография/документ были отосланы в диалоге и считаются закрытым типом вложений. 
Я предлагаю добавить в документацию после того что я написал выше: для вложений типа photo/doc нужно указывать параметр access_key: `"type{OWNER_ID}_{ITEM_ID}_{ACCESS_KEY}" `
(пример: photo41629685_45739401_15ae748282c3ae48ba)

**Comment by axd1x8a** [comment]
Это не ошибка, а стандартный формат аттачментов, подробнее про это можно почитать в документации вк, вкботл не является документацией по vk api.
