### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ydjin0602** [vkbottle/vkbottle#665]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/master.zip`) и проблема осталась

### Описание

Когда используется токен заблокированного пользователя, то ошибка VKAPIError[5] не может зарайзиться, вместо этого выпадает.
```
TypeError: VKAPIError.__init__() got an unexpected keyword argument 'ban_info'
```

**Comment by axd1x8a** [comment]
@LeeeeT that's your kind of thing

**Comment by axd1x8a** [comment]
@ydjin0602 Воспроизводится ли ишью в dev ветке?

**Comment by ydjin0602** [comment]
Да, воспроизводится
