### ISSUE TITLE
Ошибка типизации в методе raw_event() 

### ISSUE THREAD

**Issue by usir123** [vkbottle/vkbottle#694]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

Ошибка типизации в методе raw_event() у юзерботов, требует передать dataclass который не нужен, а так же сам event ожидается в типе str, когда события у юзерботов приходят в типе int.

### Пример кода

```python
from vkbottle.user import User

bot = User("тут был токен")

@bot.on.raw_event(4) # Parameter 'dataclass' unfilled
async def hello(event):
    print(event)

@bot.on.raw_event(4, {}) # Expected type 'str | list[str]', got 'int' instead
async def hello(event):
    print(event)

bot.run_forever()
```

**Comment by axd1x8a** [comment]
Это не баг, в типах указан ABCLabeler, а он рассчитан на обычных ботов.
