### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by markelovstyle** [vkbottle/vkbottle#71]
**Опишите баг**
AttributeError: module 'vkbottle.types.objects' has no attribute 'photos'

**Что должно было случится**
Ошибки быть не должно.

**Ваш код**
https://pastebin.com/nkGKATBs

**Заполните поля:**
 - OS: Ubuntu
 - Version of vkbottle: 2.7

**Дополнительная информация**
...

**Comment by timoniq** [comment]
Будет исправлено в ближайшее время

**Comment by timoniq** [comment]
Исправлено в [реверте](https://github.com/timoniq/vkbottle/commit/2b0af59d0463c0ec625f1de62cef6087a5dc6e29)
