### ISSUE TITLE
KeyError: 'ts'

### ISSUE THREAD

**Issue by mrtnvgr** [vkbottle/vkbottle#718]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

Фикс для #677 не помог.

### Логи

```shell
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code

  File "/home/user/vkreborn/vkreborn/__main__.py", line 35, in <module>
    main()
    └ <function main at 0x7f69855d4540>

  File "/home/user/vkreborn/vkreborn/__main__.py", line 31, in main
    user.run_forever()
    │    └ <function User.run_forever at 0x7f69826c5d00>
    └ <vkbottle.framework.user.user.User object at 0x7f698343cbd0>

  File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/framework/user/user.py", line 116, in run_forever
    except RuntimeError:
  File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/tools/dev/loop_wrapper.py", line 64, in run
    results = self.loop.run_until_complete(
              │    │    └ <function BaseEventLoop.run_until_complete at 0x7f6985b00b80>
              │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
              └ <vkbottle.tools.dev.loop_wrapper.LoopWrapper object at 0x7f698343ca90>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f6985b00ae0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f6985b028e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f6985da4f40>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/framework/user/user.py", line 108, in run_polling
    password: str,
> File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/polling/user_polling.py", line 68, in listen
    if not event.get("ts"):
           │     └ <method 'get' of 'dict' objects>
           └ {'failed': 2, 'error': "Key validation failed: Can't find such key"}

KeyError: 'ts'
```

**Comment by fiersik** [comment]
@mrtnvgr Ох ё...

**Comment by mrtnvgr** [comment]
> @mrtnvgr Ох ё...

За ночь логов вышло на 7GB 🫠

**Comment by luwqz1** [comment]
Кажется, Алиса не знала, что в 3.8 у метода dict.get() параметр default  не имеет значения по дефолту. Ты можешь сделать пр, в котором исправить эту проблему, сделав: event.get("ts", None)

**Comment by mrtnvgr** [comment]
> Кажется, Алиса не знала, что в 3.8 у метода dict.get() параметр default  не имеет значения по дефолту. Ты можешь сделать пр, в котором исправить эту проблему, сделав: event.get("ts", None)

Спасибо за ответ, но причем тут 3.8? На 3.11 параметр None не обязателен.

**Comment by luwqz1** [comment]
> > Кажется, Алиса не знала, что в 3.8 у метода dict.get() параметр default  не имеет значения по дефолту. Ты можешь сделать пр, в котором исправить эту проблему, сделав: event.get("ts", None)
> 
> Спасибо за ответ, но причем тут 3.8? На 3.11 параметр None не обязателен.

В том то и дело. Ботл поддерживает версию python 3.8 и выше. Начиная с 3.9, у метода dict.get() параметр default имеет дефолтное значение `None`, поэтому для 3.8 нужно указать `event.get("ts", None)`

**Comment by mrtnvgr** [comment]
> > > Кажется, Алиса не знала, что в 3.8 у метода dict.get() параметр default  не имеет значения по дефолту. Ты можешь сделать пр, в котором исправить эту проблему, сделав: event.get("ts", None)
> > 
> > Спасибо за ответ, но причем тут 3.8? На 3.11 параметр None не обязателен.
> 
> В том то и дело. Ботл поддерживает версию python 3.8 и выше. Начиная с 3.9, у метода dict.get() параметр default имеет дефолтное значение `None`, поэтому для 3.8 нужно указать `event.get("ts", None)`

Извини, что не уточнил сразу. Я использую 3.11, в логе видно.

**Comment by axd1x8a** [comment]
https://docs.python.org/3/library/stdtypes.html?highlight=dict%20get#dict.get

Тут вы оба не правы. Советую переустановить питон и не использовать сторонние его реализации.

**Comment by luwqz1** [comment]
> > > > Кажется, Алиса не знала, что в 3.8 у метода dict.get() параметр default  не имеет значения по дефолту. Ты можешь сделать пр, в котором исправить эту проблему, сделав: event.get("ts", None)
> > > 
> > > 
> > > Спасибо за ответ, но причем тут 3.8? На 3.11 параметр None не обязателен.
> > 
> > 
> > В том то и дело. Ботл поддерживает версию python 3.8 и выше. Начиная с 3.9, у метода dict.get() параметр default имеет дефолтное значение `None`, поэтому для 3.8 нужно указать `event.get("ts", None)`
> 
> Извини, что не уточнил сразу. Я использую 3.11, в логе видно.


Очень странно... почему get тогда вызвал исключение... По логам действительно видно, что в словаре не лежал 'ts', но почему вместо None вызвалось исключение, очень странно

**Comment by luwqz1** [comment]
@FeeeeK Ладно, значит, я перепутал с чем-то другим

**Comment by mrtnvgr** [comment]
> https://docs.python.org/3/library/stdtypes.html?highlight=dict%20get#dict.get
> 
> Тут вы оба не правы. Советую переустановить питон и не использовать сторонние его реализации.

Питон установлен с официальных репозиториев [Alpine Linux](https://www.alpinelinux.org/). В #677 аналогично с [Void'овских](https://voidlinux.org/).

**Comment by axd1x8a** [comment]
В #677 не было фикса. Попробуйте очистить pycache, иных причин я не вижу.

**Comment by mrtnvgr** [comment]
> В #677 не было фикса.

https://github.com/vkbottle/vkbottle/commit/a48e5c7b2e20fa58fdb50aa285391b5cd2eb9cbe
