### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by markelovstyle** [vkbottle/vkbottle#74]
**Опишите баг**
pydantic.error_wrappers.ValidationError: 1 validation error for GetByIdModel

**Что должно было случится**
Ошибки быть не должно

**Ваш код**
https://pastebin.com/jUvzJipT

**Заполните поля:**
 - OS: Ubuntu 16.04
 - Version of vkbottle: Latest

**Дополнительная информация**
N/A

**Comment by timoniq** [comment]
Дополните ваше issue пришедшим ивентом пожалуйста (`bot = Bot(..., debug="DEBUG")`)

**Comment by markelovstyle** [comment]
UPD (New Exception (vkbottle.bot.Bot)):

Exception: https://pastebin.com/j9MiERh9
Event: https://pastebin.com/g5C5PVNK
