### ISSUE TITLE
Ошибка при обработке постов на стене(GroupEventType.WALL_POST_NEW), с размещенным ТОВАРОМ

### ISSUE THREAD

**Issue by SeregaChipset** [vkbottle/vkbottle#818]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

При обработке постов на стене(GroupEventType.WALL_POST_NEW), с размещенным ТОВАРОМ, возникает ошибка
pydantic.error_wrappers.ValidationError: 1 validation error for WallPostNew
object -> attachments -> 0 -> market -> category -> section
  field required (type=value_error.missing)
с постами, без товаров, все ок.
Я так понимаю, это связанно с обновлением vk api 5.139  где переработан формат метода market.getCategories.
Если в файле objects.py вкботла закомментировать строку section: "MarketSection" в class MarketMarketCategoryOld, ошибка не появляется.

### Пример кода

```python
@wall_labeler.raw_event(GroupEventType.WALL_POST_NEW, dataclass=GroupTypes.WallPostNew)
async def new_post(event: GroupTypes.WallPostNew):
    pass
```

### Логи

```shell
pydantic.error_wrappers.ValidationError: 1 validation error for WallPostNew
object -> attachments -> 0 -> market -> category -> section
  field required (type=value_error.missing)
```

**Comment by timoniq** [comment]
привет. проверьте на последней версии [vkbottle-types](https://github.com/vkbottle/types)
