### ISSUE TITLE
Исправить конфликты с другими библиотеками из-за Pydantic

### ISSUE THREAD

**Issue by carakaton** [vkbottle/vkbottle#870]
### Описание

Сейчас vkbottle конфликтует, например, с aiogram из-за разных версий Pydantic. Хотелось бы, чтобы Вы обновили Pydantic и импортировали объекты из `pydantic.v1` в своей библиотеке. Это можно быстро сделать с помощью команды "Replace in Files".

<img width="527" alt="image" src="https://github.com/vkbottle/vkbottle/assets/89746567/fd35b973-47ad-407b-9472-f972bedfe436">

**Comment by axd1x8a** [comment]
#758

**Comment by vffuunnyy** [comment]
> например, с aiogram из-за разных версий Pydantic

Текущая актуальная версия aiogram поддерживает pydantic только от 2.4.1 до 2.6 версии.
Тут решение либо обновить aiogram до 3.x версии, либо понизить версию vkbottle.

https://github.com/aiogram/aiogram/commit/461e59bbdda94896043fce12a578b25d888da7c8 изменение, как мы видим, произошло разницей в неделю.

**Comment by RousingGibbon** [comment]
+
