### ISSUE TITLE
Хватит настраивать логер за меня.

### ISSUE THREAD

**Issue by igorechek06** [vkbottle/vkbottle#877]
Библиотека не должна трогать и настраивать логер. Это задача программиста который использует вашу библиотеку.

**Comment by axd1x8a** [comment]
Это сделано для экономии времени контрибьюторов и мейнтейнера при взаимодействии с пользователями, которые никогда не слышали о логгинге. Если вы настраиваете его сами, то вам это никак не должно мешать.

**Comment by igorechek06** [comment]
@FeeeeK Проблема в том что по умолчанию он включает режим DEBUG и пишет назойливое сообщение. Если вы хотите использовать логер в библиотеке то вам нужно использовать отдельный инстанс, а не менять глобальные настройки.

**Comment by vffuunnyy** [comment]
@igorechek06 как было упомянуто в чатике: сделайте `logging.getLogger("vkbottle").setLevel(logging.INFO)`

**Comment by monosans** [comment]
Теперь еще и навязывается colorama, из-за чего у меня сломался [rich](https://github.com/Textualize/rich), класс.

Надеюсь, этот код кому-то поможет:

```python
import logging

# Настраиваем логгинг как вам нужно до первого импорта vkbottle
logging.basicConfig(level=logging.INFO)

vkbottle_logger = logging.getLogger("vkbottle")

# Глушим "используйте loguru вместо logging"
vkbottle_logger.setLevel(logging.WARNING)

# Импортируем вторжение vkbottle в настройки логгинга
import vkbottle.modules

# Изгоняем нечисть
logging.root.handlers[0].setFormatter(None)

# Возвращаем уровень логгирования
vkbottle_logger.setLevel(logging.NOTSET)
```

**Comment by axd1x8a** [comment]
PR с выносом этих настроек в отдельную функцию приветствуется
