### ISSUE TITLE
Code refactor -> tools.keyboard.action

### ISSUE THREAD

**Issue by Oidaho** [vkbottle/vkbottle#927]
### 📄 Небольшой рефактор.
Я не считаю это прям очень необходимой фичей, да и фичей это назвать сложно.
Я просто копался в исходном коде и решил "размять руку", попробовав привнести что-то новое.
На мой взгляд, такой вариант исполнения **action** больше вписывается в парадигму наследования и ООП.

❗ Из изменений:
 - Согласно PEP8 убрал использование type, как отдельной переменной, во избежание путаницы и возможных ошибок интерпретации.
 - Метод **get_data()** заменен на свойство **data** . Это просто удобнее.
 - Класс ABCAction переименован в BaseAction. Изначально ABC используется для абстрактных классов.
 - Присвоение типа происходит теперь за счет супер-инициализации. 
 

 ** Это чисто проба пера, та что буду рад, если этим рефактором я подкину хотя бы мысли по обновлению проектной стилистики и т.п.

### Пример кода

```python3
from typing import Union, Optional

Payload = Union[str, dict]


class BaseAction(object):
    def __init__(self, action_type: str):
        self.type = action_type

    @property
    def data(self) -> dict:
        data = {key: value for key, value in vars(self).items()}
        return data


class Text(BaseAction):
    def __init__(self, label: str, payload: Payload[Optional] = None):
        super().__init__("text")

        self.label = label
        self.payload = payload


class OpenLink(BaseAction):
    def __init__(self, url: str, label: str, payload: Payload[Optional] = None):
        super().__init__("open_link")

        self.link = url
        self.label = label
        self.payload = payload


class Location(BaseAction):
    def __init__(self, url: str, label: str, payload: Payload[Optional] = None):
        super().__init__("location")

        self.link = url
        self.label = label
        self.payload = payload


class VKPay(BaseAction):
    def __init__(
        self, payment_hash: str, label: str, payload: Payload[Optional] = None
    ):
        super().__init__("vkpay")

        self.hash = payment_hash
        self.label = label
        self.payload = payload


class VKApp(BaseAction):
    def __init__(
        self,
        app_hash: str,
        label: str,
        app_id: int,
        owner_id: int,
        payload: Payload[Optional] = None,
    ):
        super().__init__("open_app")

        self.hash = app_hash
        self.label = label
        self.payload = payload
        self.app_id = app_id
        self.owner_id = owner_id


class Callback(BaseAction):
    def __init__(self, label: str, payload: Payload[Optional] = None):
        super().__init__("callback")

        self.label = label
        self.payload = payload


__all__ = (
    "BaseAction",
    "Callback",
    "Location",
    "OpenLink",
    "Text",
    "VKApp",
    "VKPay",
)
```

**Comment by axd1x8a** [comment]
1. Любое изменение публичного API фреймворка без веской на то причины нежелательно. "Просто удобно" веской причиной не является, помимо этого, в проперти не должно выполняться каких-либо операций, так что `get_data()` там не просто так.
2. В `type` проблемы никакой нет, это константа для класса и она нигде не перекрывает `type` из стандартной библиотеки

**Comment by luwqz1** [comment]
@Oidaho что это?
