### ISSUE TITLE
Обновление версии pydantic для vkbottle

### ISSUE THREAD

**Issue by YakovSava** [vkbottle/vkbottle#961]
### Описание

В одном из моих проектов, используется одновременно 2 фреймворка которые требуют `pydantic`, однако тут возникает конфликт версий между ними, я бы хотел поинтересоваться, планируется ли переход на новые версии `pydantic` (2.4.2+) если да, то можно ли помочь отправив ПР, если нет то почему? 
**Заранее спасибо за ответ**

**Comment by luwqz1** [comment]
#758
