### ISSUE TITLE
Как получить ссылку на капчу?

### ISSUE THREAD

**Issue by font2mass** [vkbottle/vkbottle#969]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

Здравствуйте.

Иногда ВК запрашивает капчу. Обычно ошибка выглядит так:
`2024-06-22 09:23:54.422 | WARNING  | vkbottle.exception_factory.base_exceptions:__init__:18 - VK API Error 14 has extra kwargs: {'is_refresh_enabled': True, 'captcha_ratio': 2.6, 'is_sound_captcha_available': False}`

Ссылки тут нет.
Единственный вариант увидеть ссылку, который я нашёл, - переключить логгер в режим "дебаг", но тогда в логи идёт большой поток информации, что совсем не удобно.

Как правильно получить ссылку на капчу?

**Comment by luwqz1** [comment]
@font2mass да хер его знает

**Comment by axd1x8a** [comment]
https://vkbottle.readthedocs.io/ru/dev/low-level/api/
`CaptchaError` содержит в себе изображение и все необходимое для решении капчи.
