### ISSUE TITLE
Когда будет поддержка pydantic'a 2 версий?

### ISSUE THREAD

**Issue by FlameHaker** [vkbottle/vkbottle#989]
### Описание

Я не могу перейти на другую версию библиотеки из-за вашей старой версий pydantic'a. 

![image](https://github.com/user-attachments/assets/12f60fc7-5990-45b4-9a2e-fd9097fd7ab6)

**Comment by luwqz1** [comment]
Поставь с гитхаба
`poetry add git+https://github.com/vkbottle/vkbottle#master`

**Comment by FlameHaker** [comment]
Это никак не спас, но приходиться сидеть на немного версий ниже

**Comment by axd1x8a** [comment]
> Это никак не спас, но приходиться сидеть на немного версий ниже

Вам это мешает?

**Comment by luwqz1** [comment]
> Это никак не спас, но приходиться сидеть на немного версий ниже

почему? покажи логи

**Comment by vffuunnyy** [comment]
> Это никак не спас, но приходиться сидеть на немного версий ниже

Несколько дней назад обновили пакеты так, чтобы была поддержка pydantic до 3 версии. Не несите чепухи, sir.

**Comment by biddyvetements** [comment]
Same, когда добавят поддержку pydantic v2?
