### ISSUE TITLE
Переход на pydantic v2

### ISSUE THREAD

**Issue by introquest** [vkbottle/vkbottle#995]
### Описание

Подавляющее большинство уже перешло на pydantic (>=2,<3)
Как быстрое решение позволящее использовать [vkbottle](https://github.com/vkbottle/vkbottle) с другими современными библиотеками можно использовать [обратную совместимость](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features). 

### Пример кода

```python3
from pydantic.v1 import BaseModel
```

**Comment by luwqz1** [comment]
`pip install git+https://github.com/vkbottle/vkbottle#dev`
