### ISSUE TITLE
Проблема ssl сертификата aiohttp

### ISSUE THREAD

**Issue by DarkCatTrue** [vkbottle/vkbottle#997]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

При запуске стандартного кода из документации выдаёт следующую ошибку:

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.vk.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')]

Я  проверял ваш ответ на подобную проблему, и решил тоже проверить передачу сертификата через Openssl. Сертификат передаётся, однако я всё равно не понимаю из-за чего тогда выдётся эта ошибка.

Более подробно расписал на StackOverFlow: https://ru.stackoverflow.com/questions/1590765/

**Comment by LeeeeT** [comment]
Запустите [вот этот скрипт](https://github.com/asheroto/Root-Certificate-Updater), чтобы обновить сертификаты.

**Comment by Sicquze** [comment]
@LeeeeT .

**Comment by DarkCatTrue** [comment]
Ну короче, обновление сертификатов ни на что не повлияло по итогу. Решил через openssl установить сертификат который мне выдало. Сохранил в блокноте в расширении .crt . Далее закинул его в доверенные корневые сертификаты и всё заработало.

**Comment by writervox** [comment]
Привет, была похожая проблема. Опишу свой случай для тех, кто наткнется на этот пост позже. 

`aiohttp` использовал хранилище сертификатов моей Windows, в то время как библиотека `Сertifi`, необходимая для корректной работы с SSL-ами, содержит свой собственный набор доверенных сертификатов, независимо от Windows. Я явно сказал библиотеке `aiohttp` использовать именно _его_ через `ssl.create_default_context(cafile=certifi.where())`, минуя системное хранилище Windows, где что-то было не так. 

Поэтому просто сделал так (пример с моим ВК ботом):

```
import ssl, certifi, aiohttp
from vkbottle import Bot

ssl_ctx = ssl.create_default_context(cafile=certifi.where())

bot = Bot(token="твой_токен")

async def on_startup():
    connector = aiohttp.TCPConnector(ssl=ssl_ctx)
    bot.api.http_client.session = aiohttp.ClientSession(connector=connector)

```

Удачи!
